// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockComplianceStore is an autogenerated mock type for the ComplianceStore type
type MockComplianceStore struct {
	mock.Mock
}

type MockComplianceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplianceStore) EXPECT() *MockComplianceStore_Expecter {
	return &MockComplianceStore_Expecter{mock: &_m.Mock}
}

// FindExport provides a mock function with given fields: ctx, tenant, id
func (_m *MockComplianceStore) FindExport(ctx context.Context, tenant valueobject.TenantID, id string) (command.RegulatoryExport, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindExport")
	}

	var r0 command.RegulatoryExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.RegulatoryExport, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.RegulatoryExport); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.RegulatoryExport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceStore_FindExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExport'
type MockComplianceStore_FindExport_Call struct {
	*mock.Call
}

// FindExport is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockComplianceStore_Expecter) FindExport(ctx interface{}, tenant interface{}, id interface{}) *MockComplianceStore_FindExport_Call {
	return &MockComplianceStore_FindExport_Call{Call: _e.mock.On("FindExport", ctx, tenant, id)}
}

func (_c *MockComplianceStore_FindExport_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockComplianceStore_FindExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockComplianceStore_FindExport_Call) Return(_a0 command.RegulatoryExport, _a1 error) *MockComplianceStore_FindExport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceStore_FindExport_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.RegulatoryExport, error)) *MockComplianceStore_FindExport_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDecision provides a mock function with given fields: ctx, decision
func (_m *MockComplianceStore) RecordDecision(ctx context.Context, decision command.ScreeningDecision) error {
	ret := _m.Called(ctx, decision)

	if len(ret) == 0 {
		panic("no return value specified for RecordDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.ScreeningDecision) error); ok {
		r0 = rf(ctx, decision)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceStore_RecordDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDecision'
type MockComplianceStore_RecordDecision_Call struct {
	*mock.Call
}

// RecordDecision is a helper method to define mock.On call
//   - ctx context.Context
//   - decision command.ScreeningDecision
func (_e *MockComplianceStore_Expecter) RecordDecision(ctx interface{}, decision interface{}) *MockComplianceStore_RecordDecision_Call {
	return &MockComplianceStore_RecordDecision_Call{Call: _e.mock.On("RecordDecision", ctx, decision)}
}

func (_c *MockComplianceStore_RecordDecision_Call) Run(run func(ctx context.Context, decision command.ScreeningDecision)) *MockComplianceStore_RecordDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.ScreeningDecision))
	})
	return _c
}

func (_c *MockComplianceStore_RecordDecision_Call) Return(_a0 error) *MockComplianceStore_RecordDecision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceStore_RecordDecision_Call) RunAndReturn(run func(context.Context, command.ScreeningDecision) error) *MockComplianceStore_RecordDecision_Call {
	_c.Call.Return(run)
	return _c
}

// SaveExport provides a mock function with given fields: ctx, export
func (_m *MockComplianceStore) SaveExport(ctx context.Context, export command.RegulatoryExport) error {
	ret := _m.Called(ctx, export)

	if len(ret) == 0 {
		panic("no return value specified for SaveExport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.RegulatoryExport) error); ok {
		r0 = rf(ctx, export)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceStore_SaveExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveExport'
type MockComplianceStore_SaveExport_Call struct {
	*mock.Call
}

// SaveExport is a helper method to define mock.On call
//   - ctx context.Context
//   - export command.RegulatoryExport
func (_e *MockComplianceStore_Expecter) SaveExport(ctx interface{}, export interface{}) *MockComplianceStore_SaveExport_Call {
	return &MockComplianceStore_SaveExport_Call{Call: _e.mock.On("SaveExport", ctx, export)}
}

func (_c *MockComplianceStore_SaveExport_Call) Run(run func(ctx context.Context, export command.RegulatoryExport)) *MockComplianceStore_SaveExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.RegulatoryExport))
	})
	return _c
}

func (_c *MockComplianceStore_SaveExport_Call) Return(_a0 error) *MockComplianceStore_SaveExport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceStore_SaveExport_Call) RunAndReturn(run func(context.Context, command.RegulatoryExport) error) *MockComplianceStore_SaveExport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComplianceStore creates a new instance of MockComplianceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplianceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplianceStore {
	mock := &MockComplianceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
