// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	time "time"
)

// MockDisputeStore is an autogenerated mock type for the DisputeStore type
type MockDisputeStore struct {
	mock.Mock
}

type MockDisputeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisputeStore) EXPECT() *MockDisputeStore_Expecter {
	return &MockDisputeStore_Expecter{mock: &_m.Mock}
}

// CreateDispute provides a mock function with given fields: ctx, dispute
func (_m *MockDisputeStore) CreateDispute(ctx context.Context, dispute entity.Dispute) error {
	ret := _m.Called(ctx, dispute)

	if len(ret) == 0 {
		panic("no return value specified for CreateDispute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Dispute) error); ok {
		r0 = rf(ctx, dispute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDisputeStore_CreateDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDispute'
type MockDisputeStore_CreateDispute_Call struct {
	*mock.Call
}

// CreateDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - dispute entity.Dispute
func (_e *MockDisputeStore_Expecter) CreateDispute(ctx interface{}, dispute interface{}) *MockDisputeStore_CreateDispute_Call {
	return &MockDisputeStore_CreateDispute_Call{Call: _e.mock.On("CreateDispute", ctx, dispute)}
}

func (_c *MockDisputeStore_CreateDispute_Call) Run(run func(ctx context.Context, dispute entity.Dispute)) *MockDisputeStore_CreateDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Dispute))
	})
	return _c
}

func (_c *MockDisputeStore_CreateDispute_Call) Return(_a0 error) *MockDisputeStore_CreateDispute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisputeStore_CreateDispute_Call) RunAndReturn(run func(context.Context, entity.Dispute) error) *MockDisputeStore_CreateDispute_Call {
	_c.Call.Return(run)
	return _c
}

// FindDispute provides a mock function with given fields: ctx, id
func (_m *MockDisputeStore) FindDispute(ctx context.Context, id string) (entity.Dispute, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindDispute")
	}

	var r0 entity.Dispute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Dispute, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Dispute); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Dispute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeStore_FindDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDispute'
type MockDisputeStore_FindDispute_Call struct {
	*mock.Call
}

// FindDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDisputeStore_Expecter) FindDispute(ctx interface{}, id interface{}) *MockDisputeStore_FindDispute_Call {
	return &MockDisputeStore_FindDispute_Call{Call: _e.mock.On("FindDispute", ctx, id)}
}

func (_c *MockDisputeStore_FindDispute_Call) Run(run func(ctx context.Context, id string)) *MockDisputeStore_FindDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDisputeStore_FindDispute_Call) Return(_a0 entity.Dispute, _a1 error) *MockDisputeStore_FindDispute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeStore_FindDispute_Call) RunAndReturn(run func(context.Context, string) (entity.Dispute, error)) *MockDisputeStore_FindDispute_Call {
	_c.Call.Return(run)
	return _c
}

// ListDisputes provides a mock function with given fields: ctx, status, from, to, cursor, limit
func (_m *MockDisputeStore) ListDisputes(ctx context.Context, status string, from time.Time, to time.Time, cursor string, limit int) ([]entity.Dispute, string, error) {
	ret := _m.Called(ctx, status, from, to, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDisputes")
	}

	var r0 []entity.Dispute
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string, int) ([]entity.Dispute, string, error)); ok {
		return rf(ctx, status, from, to, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string, int) []entity.Dispute); ok {
		r0 = rf(ctx, status, from, to, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Dispute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, string, int) string); ok {
		r1 = rf(ctx, status, from, to, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time, time.Time, string, int) error); ok {
		r2 = rf(ctx, status, from, to, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDisputeStore_ListDisputes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDisputes'
type MockDisputeStore_ListDisputes_Call struct {
	*mock.Call
}

// ListDisputes is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - from time.Time
//   - to time.Time
//   - cursor string
//   - limit int
func (_e *MockDisputeStore_Expecter) ListDisputes(ctx interface{}, status interface{}, from interface{}, to interface{}, cursor interface{}, limit interface{}) *MockDisputeStore_ListDisputes_Call {
	return &MockDisputeStore_ListDisputes_Call{Call: _e.mock.On("ListDisputes", ctx, status, from, to, cursor, limit)}
}

func (_c *MockDisputeStore_ListDisputes_Call) Run(run func(ctx context.Context, status string, from time.Time, to time.Time, cursor string, limit int)) *MockDisputeStore_ListDisputes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time), args[4].(string), args[5].(int))
	})
	return _c
}

func (_c *MockDisputeStore_ListDisputes_Call) Return(_a0 []entity.Dispute, _a1 string, _a2 error) *MockDisputeStore_ListDisputes_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDisputeStore_ListDisputes_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time, string, int) ([]entity.Dispute, string, error)) *MockDisputeStore_ListDisputes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDispute provides a mock function with given fields: ctx, dispute
func (_m *MockDisputeStore) UpdateDispute(ctx context.Context, dispute entity.Dispute) error {
	ret := _m.Called(ctx, dispute)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDispute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Dispute) error); ok {
		r0 = rf(ctx, dispute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDisputeStore_UpdateDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDispute'
type MockDisputeStore_UpdateDispute_Call struct {
	*mock.Call
}

// UpdateDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - dispute entity.Dispute
func (_e *MockDisputeStore_Expecter) UpdateDispute(ctx interface{}, dispute interface{}) *MockDisputeStore_UpdateDispute_Call {
	return &MockDisputeStore_UpdateDispute_Call{Call: _e.mock.On("UpdateDispute", ctx, dispute)}
}

func (_c *MockDisputeStore_UpdateDispute_Call) Run(run func(ctx context.Context, dispute entity.Dispute)) *MockDisputeStore_UpdateDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Dispute))
	})
	return _c
}

func (_c *MockDisputeStore_UpdateDispute_Call) Return(_a0 error) *MockDisputeStore_UpdateDispute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisputeStore_UpdateDispute_Call) RunAndReturn(run func(context.Context, entity.Dispute) error) *MockDisputeStore_UpdateDispute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDisputeStore creates a new instance of MockDisputeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisputeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisputeStore {
	mock := &MockDisputeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
