// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockIntentStore is an autogenerated mock type for the IntentStore type
type MockIntentStore struct {
	mock.Mock
}

type MockIntentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntentStore) EXPECT() *MockIntentStore_Expecter {
	return &MockIntentStore_Expecter{mock: &_m.Mock}
}

// CreateIntent provides a mock function with given fields: ctx, record
func (_m *MockIntentStore) CreateIntent(ctx context.Context, record command.IntentRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.IntentRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntentStore_CreateIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntent'
type MockIntentStore_CreateIntent_Call struct {
	*mock.Call
}

// CreateIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.IntentRecord
func (_e *MockIntentStore_Expecter) CreateIntent(ctx interface{}, record interface{}) *MockIntentStore_CreateIntent_Call {
	return &MockIntentStore_CreateIntent_Call{Call: _e.mock.On("CreateIntent", ctx, record)}
}

func (_c *MockIntentStore_CreateIntent_Call) Run(run func(ctx context.Context, record command.IntentRecord)) *MockIntentStore_CreateIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.IntentRecord))
	})
	return _c
}

func (_c *MockIntentStore_CreateIntent_Call) Return(_a0 error) *MockIntentStore_CreateIntent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntentStore_CreateIntent_Call) RunAndReturn(run func(context.Context, command.IntentRecord) error) *MockIntentStore_CreateIntent_Call {
	_c.Call.Return(run)
	return _c
}

// FindIntent provides a mock function with given fields: ctx, tenant, id
func (_m *MockIntentStore) FindIntent(ctx context.Context, tenant valueobject.TenantID, id string) (command.IntentRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindIntent")
	}

	var r0 command.IntentRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.IntentRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.IntentRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.IntentRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntentStore_FindIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIntent'
type MockIntentStore_FindIntent_Call struct {
	*mock.Call
}

// FindIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockIntentStore_Expecter) FindIntent(ctx interface{}, tenant interface{}, id interface{}) *MockIntentStore_FindIntent_Call {
	return &MockIntentStore_FindIntent_Call{Call: _e.mock.On("FindIntent", ctx, tenant, id)}
}

func (_c *MockIntentStore_FindIntent_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockIntentStore_FindIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockIntentStore_FindIntent_Call) Return(_a0 command.IntentRecord, _a1 error) *MockIntentStore_FindIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntentStore_FindIntent_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.IntentRecord, error)) *MockIntentStore_FindIntent_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntents provides a mock function with given fields: ctx, tenant, limit
func (_m *MockIntentStore) ListIntents(ctx context.Context, tenant valueobject.TenantID, limit int) ([]command.IntentRecord, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListIntents")
	}

	var r0 []command.IntentRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]command.IntentRecord, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []command.IntentRecord); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.IntentRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIntentStore_ListIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntents'
type MockIntentStore_ListIntents_Call struct {
	*mock.Call
}

// ListIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockIntentStore_Expecter) ListIntents(ctx interface{}, tenant interface{}, limit interface{}) *MockIntentStore_ListIntents_Call {
	return &MockIntentStore_ListIntents_Call{Call: _e.mock.On("ListIntents", ctx, tenant, limit)}
}

func (_c *MockIntentStore_ListIntents_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockIntentStore_ListIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockIntentStore_ListIntents_Call) Return(_a0 []command.IntentRecord, _a1 error) *MockIntentStore_ListIntents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIntentStore_ListIntents_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]command.IntentRecord, error)) *MockIntentStore_ListIntents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIntent provides a mock function with given fields: ctx, record
func (_m *MockIntentStore) UpdateIntent(ctx context.Context, record command.IntentRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIntent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.IntentRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIntentStore_UpdateIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIntent'
type MockIntentStore_UpdateIntent_Call struct {
	*mock.Call
}

// UpdateIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.IntentRecord
func (_e *MockIntentStore_Expecter) UpdateIntent(ctx interface{}, record interface{}) *MockIntentStore_UpdateIntent_Call {
	return &MockIntentStore_UpdateIntent_Call{Call: _e.mock.On("UpdateIntent", ctx, record)}
}

func (_c *MockIntentStore_UpdateIntent_Call) Run(run func(ctx context.Context, record command.IntentRecord)) *MockIntentStore_UpdateIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.IntentRecord))
	})
	return _c
}

func (_c *MockIntentStore_UpdateIntent_Call) Return(_a0 error) *MockIntentStore_UpdateIntent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIntentStore_UpdateIntent_Call) RunAndReturn(run func(context.Context, command.IntentRecord) error) *MockIntentStore_UpdateIntent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIntentStore creates a new instance of MockIntentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntentStore {
	mock := &MockIntentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
