// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"
)

// MockPeriodStore is an autogenerated mock type for the PeriodStore type
type MockPeriodStore struct {
	mock.Mock
}

type MockPeriodStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeriodStore) EXPECT() *MockPeriodStore_Expecter {
	return &MockPeriodStore_Expecter{mock: &_m.Mock}
}

// FindPeriod provides a mock function with given fields: ctx, tenant, ledger, id
func (_m *MockPeriodStore) FindPeriod(ctx context.Context, tenant string, ledger string, id string) (entity.PeriodData, error) {
	ret := _m.Called(ctx, tenant, ledger, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPeriod")
	}

	var r0 entity.PeriodData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (entity.PeriodData, error)); ok {
		return rf(ctx, tenant, ledger, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) entity.PeriodData); ok {
		r0 = rf(ctx, tenant, ledger, id)
	} else {
		r0 = ret.Get(0).(entity.PeriodData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenant, ledger, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPeriodStore_FindPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPeriod'
type MockPeriodStore_FindPeriod_Call struct {
	*mock.Call
}

// FindPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant string
//   - ledger string
//   - id string
func (_e *MockPeriodStore_Expecter) FindPeriod(ctx interface{}, tenant interface{}, ledger interface{}, id interface{}) *MockPeriodStore_FindPeriod_Call {
	return &MockPeriodStore_FindPeriod_Call{Call: _e.mock.On("FindPeriod", ctx, tenant, ledger, id)}
}

func (_c *MockPeriodStore_FindPeriod_Call) Run(run func(ctx context.Context, tenant string, ledger string, id string)) *MockPeriodStore_FindPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPeriodStore_FindPeriod_Call) Return(_a0 entity.PeriodData, _a1 error) *MockPeriodStore_FindPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPeriodStore_FindPeriod_Call) RunAndReturn(run func(context.Context, string, string, string) (entity.PeriodData, error)) *MockPeriodStore_FindPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ListPeriods provides a mock function with given fields: ctx, tenant, ledger, limit
func (_m *MockPeriodStore) ListPeriods(ctx context.Context, tenant string, ledger string, limit int) ([]entity.PeriodData, error) {
	ret := _m.Called(ctx, tenant, ledger, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPeriods")
	}

	var r0 []entity.PeriodData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]entity.PeriodData, error)); ok {
		return rf(ctx, tenant, ledger, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []entity.PeriodData); ok {
		r0 = rf(ctx, tenant, ledger, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PeriodData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, tenant, ledger, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPeriodStore_ListPeriods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPeriods'
type MockPeriodStore_ListPeriods_Call struct {
	*mock.Call
}

// ListPeriods is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant string
//   - ledger string
//   - limit int
func (_e *MockPeriodStore_Expecter) ListPeriods(ctx interface{}, tenant interface{}, ledger interface{}, limit interface{}) *MockPeriodStore_ListPeriods_Call {
	return &MockPeriodStore_ListPeriods_Call{Call: _e.mock.On("ListPeriods", ctx, tenant, ledger, limit)}
}

func (_c *MockPeriodStore_ListPeriods_Call) Run(run func(ctx context.Context, tenant string, ledger string, limit int)) *MockPeriodStore_ListPeriods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockPeriodStore_ListPeriods_Call) Return(_a0 []entity.PeriodData, _a1 error) *MockPeriodStore_ListPeriods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPeriodStore_ListPeriods_Call) RunAndReturn(run func(context.Context, string, string, int) ([]entity.PeriodData, error)) *MockPeriodStore_ListPeriods_Call {
	_c.Call.Return(run)
	return _c
}

// SavePeriod provides a mock function with given fields: ctx, period
func (_m *MockPeriodStore) SavePeriod(ctx context.Context, period entity.PeriodData) error {
	ret := _m.Called(ctx, period)

	if len(ret) == 0 {
		panic("no return value specified for SavePeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PeriodData) error); ok {
		r0 = rf(ctx, period)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPeriodStore_SavePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePeriod'
type MockPeriodStore_SavePeriod_Call struct {
	*mock.Call
}

// SavePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - period entity.PeriodData
func (_e *MockPeriodStore_Expecter) SavePeriod(ctx interface{}, period interface{}) *MockPeriodStore_SavePeriod_Call {
	return &MockPeriodStore_SavePeriod_Call{Call: _e.mock.On("SavePeriod", ctx, period)}
}

func (_c *MockPeriodStore_SavePeriod_Call) Run(run func(ctx context.Context, period entity.PeriodData)) *MockPeriodStore_SavePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.PeriodData))
	})
	return _c
}

func (_c *MockPeriodStore_SavePeriod_Call) Return(_a0 error) *MockPeriodStore_SavePeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPeriodStore_SavePeriod_Call) RunAndReturn(run func(context.Context, entity.PeriodData) error) *MockPeriodStore_SavePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeriodStore creates a new instance of MockPeriodStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeriodStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeriodStore {
	mock := &MockPeriodStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
