// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockRefundStore is an autogenerated mock type for the RefundStore type
type MockRefundStore struct {
	mock.Mock
}

type MockRefundStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundStore) EXPECT() *MockRefundStore_Expecter {
	return &MockRefundStore_Expecter{mock: &_m.Mock}
}

// CreateRefund provides a mock function with given fields: ctx, record
func (_m *MockRefundStore) CreateRefund(ctx context.Context, record command.RefundRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.RefundRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefundStore_CreateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefund'
type MockRefundStore_CreateRefund_Call struct {
	*mock.Call
}

// CreateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.RefundRecord
func (_e *MockRefundStore_Expecter) CreateRefund(ctx interface{}, record interface{}) *MockRefundStore_CreateRefund_Call {
	return &MockRefundStore_CreateRefund_Call{Call: _e.mock.On("CreateRefund", ctx, record)}
}

func (_c *MockRefundStore_CreateRefund_Call) Run(run func(ctx context.Context, record command.RefundRecord)) *MockRefundStore_CreateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.RefundRecord))
	})
	return _c
}

func (_c *MockRefundStore_CreateRefund_Call) Return(_a0 error) *MockRefundStore_CreateRefund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefundStore_CreateRefund_Call) RunAndReturn(run func(context.Context, command.RefundRecord) error) *MockRefundStore_CreateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefund provides a mock function with given fields: ctx, tenant, id
func (_m *MockRefundStore) FindRefund(ctx context.Context, tenant valueobject.TenantID, id string) (command.RefundRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindRefund")
	}

	var r0 command.RefundRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.RefundRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.RefundRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.RefundRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundStore_FindRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefund'
type MockRefundStore_FindRefund_Call struct {
	*mock.Call
}

// FindRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockRefundStore_Expecter) FindRefund(ctx interface{}, tenant interface{}, id interface{}) *MockRefundStore_FindRefund_Call {
	return &MockRefundStore_FindRefund_Call{Call: _e.mock.On("FindRefund", ctx, tenant, id)}
}

func (_c *MockRefundStore_FindRefund_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockRefundStore_FindRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockRefundStore_FindRefund_Call) Return(_a0 command.RefundRecord, _a1 error) *MockRefundStore_FindRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundStore_FindRefund_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.RefundRecord, error)) *MockRefundStore_FindRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefunds provides a mock function with given fields: ctx, tenant, limit
func (_m *MockRefundStore) ListRefunds(ctx context.Context, tenant valueobject.TenantID, limit int) ([]command.RefundRecord, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []command.RefundRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]command.RefundRecord, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []command.RefundRecord); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.RefundRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundStore_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockRefundStore_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockRefundStore_Expecter) ListRefunds(ctx interface{}, tenant interface{}, limit interface{}) *MockRefundStore_ListRefunds_Call {
	return &MockRefundStore_ListRefunds_Call{Call: _e.mock.On("ListRefunds", ctx, tenant, limit)}
}

func (_c *MockRefundStore_ListRefunds_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockRefundStore_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockRefundStore_ListRefunds_Call) Return(_a0 []command.RefundRecord, _a1 error) *MockRefundStore_ListRefunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundStore_ListRefunds_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]command.RefundRecord, error)) *MockRefundStore_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// SumPriorRefunds provides a mock function with given fields: ctx, tenant, originalTxn
func (_m *MockRefundStore) SumPriorRefunds(ctx context.Context, tenant valueobject.TenantID, originalTxn string) (int64, error) {
	ret := _m.Called(ctx, tenant, originalTxn)

	if len(ret) == 0 {
		panic("no return value specified for SumPriorRefunds")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (int64, error)); ok {
		return rf(ctx, tenant, originalTxn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) int64); ok {
		r0 = rf(ctx, tenant, originalTxn)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, originalTxn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundStore_SumPriorRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPriorRefunds'
type MockRefundStore_SumPriorRefunds_Call struct {
	*mock.Call
}

// SumPriorRefunds is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - originalTxn string
func (_e *MockRefundStore_Expecter) SumPriorRefunds(ctx interface{}, tenant interface{}, originalTxn interface{}) *MockRefundStore_SumPriorRefunds_Call {
	return &MockRefundStore_SumPriorRefunds_Call{Call: _e.mock.On("SumPriorRefunds", ctx, tenant, originalTxn)}
}

func (_c *MockRefundStore_SumPriorRefunds_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, originalTxn string)) *MockRefundStore_SumPriorRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockRefundStore_SumPriorRefunds_Call) Return(_a0 int64, _a1 error) *MockRefundStore_SumPriorRefunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundStore_SumPriorRefunds_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (int64, error)) *MockRefundStore_SumPriorRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefundStore creates a new instance of MockRefundStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundStore {
	mock := &MockRefundStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
