// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockReportStore is an autogenerated mock type for the ReportStore type
type MockReportStore struct {
	mock.Mock
}

type MockReportStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportStore) EXPECT() *MockReportStore_Expecter {
	return &MockReportStore_Expecter{mock: &_m.Mock}
}

// CreateReport provides a mock function with given fields: ctx, record
func (_m *MockReportStore) CreateReport(ctx context.Context, record command.ReportRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.ReportRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportStore_CreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReport'
type MockReportStore_CreateReport_Call struct {
	*mock.Call
}

// CreateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.ReportRecord
func (_e *MockReportStore_Expecter) CreateReport(ctx interface{}, record interface{}) *MockReportStore_CreateReport_Call {
	return &MockReportStore_CreateReport_Call{Call: _e.mock.On("CreateReport", ctx, record)}
}

func (_c *MockReportStore_CreateReport_Call) Run(run func(ctx context.Context, record command.ReportRecord)) *MockReportStore_CreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.ReportRecord))
	})
	return _c
}

func (_c *MockReportStore_CreateReport_Call) Return(_a0 error) *MockReportStore_CreateReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportStore_CreateReport_Call) RunAndReturn(run func(context.Context, command.ReportRecord) error) *MockReportStore_CreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// FindReport provides a mock function with given fields: ctx, tenant, id
func (_m *MockReportStore) FindReport(ctx context.Context, tenant valueobject.TenantID, id string) (command.ReportRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindReport")
	}

	var r0 command.ReportRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.ReportRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.ReportRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.ReportRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportStore_FindReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReport'
type MockReportStore_FindReport_Call struct {
	*mock.Call
}

// FindReport is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockReportStore_Expecter) FindReport(ctx interface{}, tenant interface{}, id interface{}) *MockReportStore_FindReport_Call {
	return &MockReportStore_FindReport_Call{Call: _e.mock.On("FindReport", ctx, tenant, id)}
}

func (_c *MockReportStore_FindReport_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockReportStore_FindReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockReportStore_FindReport_Call) Return(_a0 command.ReportRecord, _a1 error) *MockReportStore_FindReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportStore_FindReport_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.ReportRecord, error)) *MockReportStore_FindReport_Call {
	_c.Call.Return(run)
	return _c
}

// ListReports provides a mock function with given fields: ctx, tenant, limit
func (_m *MockReportStore) ListReports(ctx context.Context, tenant valueobject.TenantID, limit int) ([]command.ReportRecord, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 []command.ReportRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]command.ReportRecord, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []command.ReportRecord); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.ReportRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportStore_ListReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReports'
type MockReportStore_ListReports_Call struct {
	*mock.Call
}

// ListReports is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockReportStore_Expecter) ListReports(ctx interface{}, tenant interface{}, limit interface{}) *MockReportStore_ListReports_Call {
	return &MockReportStore_ListReports_Call{Call: _e.mock.On("ListReports", ctx, tenant, limit)}
}

func (_c *MockReportStore_ListReports_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockReportStore_ListReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockReportStore_ListReports_Call) Return(_a0 []command.ReportRecord, _a1 error) *MockReportStore_ListReports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportStore_ListReports_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]command.ReportRecord, error)) *MockReportStore_ListReports_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReport provides a mock function with given fields: ctx, record
func (_m *MockReportStore) UpdateReport(ctx context.Context, record command.ReportRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.ReportRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportStore_UpdateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReport'
type MockReportStore_UpdateReport_Call struct {
	*mock.Call
}

// UpdateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.ReportRecord
func (_e *MockReportStore_Expecter) UpdateReport(ctx interface{}, record interface{}) *MockReportStore_UpdateReport_Call {
	return &MockReportStore_UpdateReport_Call{Call: _e.mock.On("UpdateReport", ctx, record)}
}

func (_c *MockReportStore_UpdateReport_Call) Run(run func(ctx context.Context, record command.ReportRecord)) *MockReportStore_UpdateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.ReportRecord))
	})
	return _c
}

func (_c *MockReportStore_UpdateReport_Call) Return(_a0 error) *MockReportStore_UpdateReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportStore_UpdateReport_Call) RunAndReturn(run func(context.Context, command.ReportRecord) error) *MockReportStore_UpdateReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportStore creates a new instance of MockReportStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportStore {
	mock := &MockReportStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
