// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockSubscriptionStore is an autogenerated mock type for the SubscriptionStore type
type MockSubscriptionStore struct {
	mock.Mock
}

type MockSubscriptionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionStore) EXPECT() *MockSubscriptionStore_Expecter {
	return &MockSubscriptionStore_Expecter{mock: &_m.Mock}
}

// CreateSubscription provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionStore) CreateSubscription(ctx context.Context, sub command.Subscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Subscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionStore_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MockSubscriptionStore_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - sub command.Subscription
func (_e *MockSubscriptionStore_Expecter) CreateSubscription(ctx interface{}, sub interface{}) *MockSubscriptionStore_CreateSubscription_Call {
	return &MockSubscriptionStore_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, sub)}
}

func (_c *MockSubscriptionStore_CreateSubscription_Call) Run(run func(ctx context.Context, sub command.Subscription)) *MockSubscriptionStore_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionStore_CreateSubscription_Call) Return(_a0 error) *MockSubscriptionStore_CreateSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionStore_CreateSubscription_Call) RunAndReturn(run func(context.Context, command.Subscription) error) *MockSubscriptionStore_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function with given fields: ctx, tenant, id
func (_m *MockSubscriptionStore) DeleteSubscription(ctx context.Context, tenant valueobject.TenantID, id string) error {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) error); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionStore_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockSubscriptionStore_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockSubscriptionStore_Expecter) DeleteSubscription(ctx interface{}, tenant interface{}, id interface{}) *MockSubscriptionStore_DeleteSubscription_Call {
	return &MockSubscriptionStore_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", ctx, tenant, id)}
}

func (_c *MockSubscriptionStore_DeleteSubscription_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockSubscriptionStore_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionStore_DeleteSubscription_Call) Return(_a0 error) *MockSubscriptionStore_DeleteSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionStore_DeleteSubscription_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) error) *MockSubscriptionStore_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// FindSubscription provides a mock function with given fields: ctx, tenant, id
func (_m *MockSubscriptionStore) FindSubscription(ctx context.Context, tenant valueobject.TenantID, id string) (command.Subscription, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindSubscription")
	}

	var r0 command.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.Subscription, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.Subscription); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionStore_FindSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSubscription'
type MockSubscriptionStore_FindSubscription_Call struct {
	*mock.Call
}

// FindSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockSubscriptionStore_Expecter) FindSubscription(ctx interface{}, tenant interface{}, id interface{}) *MockSubscriptionStore_FindSubscription_Call {
	return &MockSubscriptionStore_FindSubscription_Call{Call: _e.mock.On("FindSubscription", ctx, tenant, id)}
}

func (_c *MockSubscriptionStore_FindSubscription_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockSubscriptionStore_FindSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionStore_FindSubscription_Call) Return(_a0 command.Subscription, _a1 error) *MockSubscriptionStore_FindSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionStore_FindSubscription_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.Subscription, error)) *MockSubscriptionStore_FindSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// ListDueSubscriptions provides a mock function with given fields: ctx, tenant, now
func (_m *MockSubscriptionStore) ListDueSubscriptions(ctx context.Context, tenant valueobject.TenantID, now time.Time) ([]command.Subscription, error) {
	ret := _m.Called(ctx, tenant, now)

	if len(ret) == 0 {
		panic("no return value specified for ListDueSubscriptions")
	}

	var r0 []command.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, time.Time) ([]command.Subscription, error)); ok {
		return rf(ctx, tenant, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, time.Time) []command.Subscription); ok {
		r0 = rf(ctx, tenant, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, time.Time) error); ok {
		r1 = rf(ctx, tenant, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionStore_ListDueSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDueSubscriptions'
type MockSubscriptionStore_ListDueSubscriptions_Call struct {
	*mock.Call
}

// ListDueSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - now time.Time
func (_e *MockSubscriptionStore_Expecter) ListDueSubscriptions(ctx interface{}, tenant interface{}, now interface{}) *MockSubscriptionStore_ListDueSubscriptions_Call {
	return &MockSubscriptionStore_ListDueSubscriptions_Call{Call: _e.mock.On("ListDueSubscriptions", ctx, tenant, now)}
}

func (_c *MockSubscriptionStore_ListDueSubscriptions_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, now time.Time)) *MockSubscriptionStore_ListDueSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSubscriptionStore_ListDueSubscriptions_Call) Return(_a0 []command.Subscription, _a1 error) *MockSubscriptionStore_ListDueSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionStore_ListDueSubscriptions_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, time.Time) ([]command.Subscription, error)) *MockSubscriptionStore_ListDueSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscription provides a mock function with given fields: ctx, sub
func (_m *MockSubscriptionStore) UpdateSubscription(ctx context.Context, sub command.Subscription) error {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Subscription) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionStore_UpdateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscription'
type MockSubscriptionStore_UpdateSubscription_Call struct {
	*mock.Call
}

// UpdateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - sub command.Subscription
func (_e *MockSubscriptionStore_Expecter) UpdateSubscription(ctx interface{}, sub interface{}) *MockSubscriptionStore_UpdateSubscription_Call {
	return &MockSubscriptionStore_UpdateSubscription_Call{Call: _e.mock.On("UpdateSubscription", ctx, sub)}
}

func (_c *MockSubscriptionStore_UpdateSubscription_Call) Run(run func(ctx context.Context, sub command.Subscription)) *MockSubscriptionStore_UpdateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionStore_UpdateSubscription_Call) Return(_a0 error) *MockSubscriptionStore_UpdateSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionStore_UpdateSubscription_Call) RunAndReturn(run func(context.Context, command.Subscription) error) *MockSubscriptionStore_UpdateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionStore creates a new instance of MockSubscriptionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionStore {
	mock := &MockSubscriptionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
