// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockTenantStore is an autogenerated mock type for the TenantStore type
type MockTenantStore struct {
	mock.Mock
}

type MockTenantStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantStore) EXPECT() *MockTenantStore_Expecter {
	return &MockTenantStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tenant
func (_m *MockTenantStore) Create(ctx context.Context, tenant entity.TenantData) (entity.TenantData, error) {
	ret := _m.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.TenantData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TenantData) (entity.TenantData, error)); ok {
		return rf(ctx, tenant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.TenantData) entity.TenantData); ok {
		r0 = rf(ctx, tenant)
	} else {
		r0 = ret.Get(0).(entity.TenantData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.TenantData) error); ok {
		r1 = rf(ctx, tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTenantStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant entity.TenantData
func (_e *MockTenantStore_Expecter) Create(ctx interface{}, tenant interface{}) *MockTenantStore_Create_Call {
	return &MockTenantStore_Create_Call{Call: _e.mock.On("Create", ctx, tenant)}
}

func (_c *MockTenantStore_Create_Call) Run(run func(ctx context.Context, tenant entity.TenantData)) *MockTenantStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TenantData))
	})
	return _c
}

func (_c *MockTenantStore_Create_Call) Return(_a0 entity.TenantData, _a1 error) *MockTenantStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantStore_Create_Call) RunAndReturn(run func(context.Context, entity.TenantData) (entity.TenantData, error)) *MockTenantStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTenantStore) FindByID(ctx context.Context, id valueobject.TenantID) (entity.TenantData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.TenantData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID) (entity.TenantData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID) entity.TenantData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.TenantData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTenantStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.TenantID
func (_e *MockTenantStore_Expecter) FindByID(ctx interface{}, id interface{}) *MockTenantStore_FindByID_Call {
	return &MockTenantStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTenantStore_FindByID_Call) Run(run func(ctx context.Context, id valueobject.TenantID)) *MockTenantStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID))
	})
	return _c
}

func (_c *MockTenantStore_FindByID_Call) Return(_a0 entity.TenantData, _a1 error) *MockTenantStore_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantStore_FindByID_Call) RunAndReturn(run func(context.Context, valueobject.TenantID) (entity.TenantData, error)) *MockTenantStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAliases provides a mock function with given fields: ctx
func (_m *MockTenantStore) ListAliases(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAliases")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantStore_ListAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAliases'
type MockTenantStore_ListAliases_Call struct {
	*mock.Call
}

// ListAliases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantStore_Expecter) ListAliases(ctx interface{}) *MockTenantStore_ListAliases_Call {
	return &MockTenantStore_ListAliases_Call{Call: _e.mock.On("ListAliases", ctx)}
}

func (_c *MockTenantStore_ListAliases_Call) Run(run func(ctx context.Context)) *MockTenantStore_ListAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantStore_ListAliases_Call) Return(_a0 []string, _a1 error) *MockTenantStore_ListAliases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantStore_ListAliases_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockTenantStore_ListAliases_Call {
	_c.Call.Return(run)
	return _c
}

// ListNames provides a mock function with given fields: ctx
func (_m *MockTenantStore) ListNames(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantStore_ListNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNames'
type MockTenantStore_ListNames_Call struct {
	*mock.Call
}

// ListNames is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantStore_Expecter) ListNames(ctx interface{}) *MockTenantStore_ListNames_Call {
	return &MockTenantStore_ListNames_Call{Call: _e.mock.On("ListNames", ctx)}
}

func (_c *MockTenantStore_ListNames_Call) Run(run func(ctx context.Context)) *MockTenantStore_ListNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantStore_ListNames_Call) Return(_a0 []string, _a1 error) *MockTenantStore_ListNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantStore_ListNames_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockTenantStore_ListNames_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenants provides a mock function with given fields: ctx
func (_m *MockTenantStore) ListTenants(ctx context.Context) ([]entity.TenantData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTenants")
	}

	var r0 []entity.TenantData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.TenantData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.TenantData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TenantData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantStore_ListTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenants'
type MockTenantStore_ListTenants_Call struct {
	*mock.Call
}

// ListTenants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantStore_Expecter) ListTenants(ctx interface{}) *MockTenantStore_ListTenants_Call {
	return &MockTenantStore_ListTenants_Call{Call: _e.mock.On("ListTenants", ctx)}
}

func (_c *MockTenantStore_ListTenants_Call) Run(run func(ctx context.Context)) *MockTenantStore_ListTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantStore_ListTenants_Call) Return(_a0 []entity.TenantData, _a1 error) *MockTenantStore_ListTenants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantStore_ListTenants_Call) RunAndReturn(run func(context.Context) ([]entity.TenantData, error)) *MockTenantStore_ListTenants_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function with given fields: ctx, tenant, expectedVersion
func (_m *MockTenantStore) UpdateSettings(ctx context.Context, tenant entity.TenantData, expectedVersion int64) error {
	ret := _m.Called(ctx, tenant, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.TenantData, int64) error); ok {
		r0 = rf(ctx, tenant, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTenantStore_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type MockTenantStore_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant entity.TenantData
//   - expectedVersion int64
func (_e *MockTenantStore_Expecter) UpdateSettings(ctx interface{}, tenant interface{}, expectedVersion interface{}) *MockTenantStore_UpdateSettings_Call {
	return &MockTenantStore_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", ctx, tenant, expectedVersion)}
}

func (_c *MockTenantStore_UpdateSettings_Call) Run(run func(ctx context.Context, tenant entity.TenantData, expectedVersion int64)) *MockTenantStore_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TenantData), args[2].(int64))
	})
	return _c
}

func (_c *MockTenantStore_UpdateSettings_Call) Return(_a0 error) *MockTenantStore_UpdateSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTenantStore_UpdateSettings_Call) RunAndReturn(run func(context.Context, entity.TenantData, int64) error) *MockTenantStore_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantStore creates a new instance of MockTenantStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantStore {
	mock := &MockTenantStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
