// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	command "github.com/kadekutama/go-template/internal/application/command"

	mock "github.com/stretchr/testify/mock"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockTopupStore is an autogenerated mock type for the TopupStore type
type MockTopupStore struct {
	mock.Mock
}

type MockTopupStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopupStore) EXPECT() *MockTopupStore_Expecter {
	return &MockTopupStore_Expecter{mock: &_m.Mock}
}

// CreateTopup provides a mock function with given fields: ctx, record
func (_m *MockTopupStore) CreateTopup(ctx context.Context, record command.TopupRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.TopupRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopupStore_CreateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopup'
type MockTopupStore_CreateTopup_Call struct {
	*mock.Call
}

// CreateTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.TopupRecord
func (_e *MockTopupStore_Expecter) CreateTopup(ctx interface{}, record interface{}) *MockTopupStore_CreateTopup_Call {
	return &MockTopupStore_CreateTopup_Call{Call: _e.mock.On("CreateTopup", ctx, record)}
}

func (_c *MockTopupStore_CreateTopup_Call) Run(run func(ctx context.Context, record command.TopupRecord)) *MockTopupStore_CreateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.TopupRecord))
	})
	return _c
}

func (_c *MockTopupStore_CreateTopup_Call) Return(_a0 error) *MockTopupStore_CreateTopup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopupStore_CreateTopup_Call) RunAndReturn(run func(context.Context, command.TopupRecord) error) *MockTopupStore_CreateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// FindTopup provides a mock function with given fields: ctx, tenant, id
func (_m *MockTopupStore) FindTopup(ctx context.Context, tenant valueobject.TenantID, id string) (command.TopupRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindTopup")
	}

	var r0 command.TopupRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (command.TopupRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) command.TopupRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(command.TopupRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopupStore_FindTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTopup'
type MockTopupStore_FindTopup_Call struct {
	*mock.Call
}

// FindTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockTopupStore_Expecter) FindTopup(ctx interface{}, tenant interface{}, id interface{}) *MockTopupStore_FindTopup_Call {
	return &MockTopupStore_FindTopup_Call{Call: _e.mock.On("FindTopup", ctx, tenant, id)}
}

func (_c *MockTopupStore_FindTopup_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockTopupStore_FindTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockTopupStore_FindTopup_Call) Return(_a0 command.TopupRecord, _a1 error) *MockTopupStore_FindTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopupStore_FindTopup_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (command.TopupRecord, error)) *MockTopupStore_FindTopup_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopups provides a mock function with given fields: ctx, tenant, limit
func (_m *MockTopupStore) ListTopups(ctx context.Context, tenant valueobject.TenantID, limit int) ([]command.TopupRecord, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTopups")
	}

	var r0 []command.TopupRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]command.TopupRecord, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []command.TopupRecord); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.TopupRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopupStore_ListTopups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopups'
type MockTopupStore_ListTopups_Call struct {
	*mock.Call
}

// ListTopups is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockTopupStore_Expecter) ListTopups(ctx interface{}, tenant interface{}, limit interface{}) *MockTopupStore_ListTopups_Call {
	return &MockTopupStore_ListTopups_Call{Call: _e.mock.On("ListTopups", ctx, tenant, limit)}
}

func (_c *MockTopupStore_ListTopups_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockTopupStore_ListTopups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockTopupStore_ListTopups_Call) Return(_a0 []command.TopupRecord, _a1 error) *MockTopupStore_ListTopups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopupStore_ListTopups_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]command.TopupRecord, error)) *MockTopupStore_ListTopups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopup provides a mock function with given fields: ctx, record
func (_m *MockTopupStore) UpdateTopup(ctx context.Context, record command.TopupRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.TopupRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopupStore_UpdateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopup'
type MockTopupStore_UpdateTopup_Call struct {
	*mock.Call
}

// UpdateTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - record command.TopupRecord
func (_e *MockTopupStore_Expecter) UpdateTopup(ctx interface{}, record interface{}) *MockTopupStore_UpdateTopup_Call {
	return &MockTopupStore_UpdateTopup_Call{Call: _e.mock.On("UpdateTopup", ctx, record)}
}

func (_c *MockTopupStore_UpdateTopup_Call) Run(run func(ctx context.Context, record command.TopupRecord)) *MockTopupStore_UpdateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.TopupRecord))
	})
	return _c
}

func (_c *MockTopupStore_UpdateTopup_Call) Return(_a0 error) *MockTopupStore_UpdateTopup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopupStore_UpdateTopup_Call) RunAndReturn(run func(context.Context, command.TopupRecord) error) *MockTopupStore_UpdateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopupStore creates a new instance of MockTopupStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopupStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopupStore {
	mock := &MockTopupStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
