// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockcommand

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockTransferStore is an autogenerated mock type for the TransferStore type
type MockTransferStore struct {
	mock.Mock
}

type MockTransferStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferStore) EXPECT() *MockTransferStore_Expecter {
	return &MockTransferStore_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function with given fields: ctx, batch, items
func (_m *MockTransferStore) CreateBatch(ctx context.Context, batch port.BatchRecord, items []port.BatchItem) error {
	ret := _m.Called(ctx, batch, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchRecord, []port.BatchItem) error); ok {
		r0 = rf(ctx, batch, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStore_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockTransferStore_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch port.BatchRecord
//   - items []port.BatchItem
func (_e *MockTransferStore_Expecter) CreateBatch(ctx interface{}, batch interface{}, items interface{}) *MockTransferStore_CreateBatch_Call {
	return &MockTransferStore_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, batch, items)}
}

func (_c *MockTransferStore_CreateBatch_Call) Run(run func(ctx context.Context, batch port.BatchRecord, items []port.BatchItem)) *MockTransferStore_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BatchRecord), args[2].([]port.BatchItem))
	})
	return _c
}

func (_c *MockTransferStore_CreateBatch_Call) Return(_a0 error) *MockTransferStore_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStore_CreateBatch_Call) RunAndReturn(run func(context.Context, port.BatchRecord, []port.BatchItem) error) *MockTransferStore_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransfer provides a mock function with given fields: ctx, record
func (_m *MockTransferStore) CreateTransfer(ctx context.Context, record port.TransferRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStore_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type MockTransferStore_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - record port.TransferRecord
func (_e *MockTransferStore_Expecter) CreateTransfer(ctx interface{}, record interface{}) *MockTransferStore_CreateTransfer_Call {
	return &MockTransferStore_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, record)}
}

func (_c *MockTransferStore_CreateTransfer_Call) Run(run func(ctx context.Context, record port.TransferRecord)) *MockTransferStore_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferRecord))
	})
	return _c
}

func (_c *MockTransferStore_CreateTransfer_Call) Return(_a0 error) *MockTransferStore_CreateTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStore_CreateTransfer_Call) RunAndReturn(run func(context.Context, port.TransferRecord) error) *MockTransferStore_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// FindBatch provides a mock function with given fields: ctx, tenant, id
func (_m *MockTransferStore) FindBatch(ctx context.Context, tenant valueobject.TenantID, id string) (port.BatchRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindBatch")
	}

	var r0 port.BatchRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.BatchRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.BatchRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(port.BatchRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferStore_FindBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBatch'
type MockTransferStore_FindBatch_Call struct {
	*mock.Call
}

// FindBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockTransferStore_Expecter) FindBatch(ctx interface{}, tenant interface{}, id interface{}) *MockTransferStore_FindBatch_Call {
	return &MockTransferStore_FindBatch_Call{Call: _e.mock.On("FindBatch", ctx, tenant, id)}
}

func (_c *MockTransferStore_FindBatch_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockTransferStore_FindBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockTransferStore_FindBatch_Call) Return(_a0 port.BatchRecord, _a1 error) *MockTransferStore_FindBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferStore_FindBatch_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.BatchRecord, error)) *MockTransferStore_FindBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindTransfer provides a mock function with given fields: ctx, tenant, id
func (_m *MockTransferStore) FindTransfer(ctx context.Context, tenant valueobject.TenantID, id string) (port.TransferRecord, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindTransfer")
	}

	var r0 port.TransferRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.TransferRecord, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.TransferRecord); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(port.TransferRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferStore_FindTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTransfer'
type MockTransferStore_FindTransfer_Call struct {
	*mock.Call
}

// FindTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
func (_e *MockTransferStore_Expecter) FindTransfer(ctx interface{}, tenant interface{}, id interface{}) *MockTransferStore_FindTransfer_Call {
	return &MockTransferStore_FindTransfer_Call{Call: _e.mock.On("FindTransfer", ctx, tenant, id)}
}

func (_c *MockTransferStore_FindTransfer_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string)) *MockTransferStore_FindTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockTransferStore_FindTransfer_Call) Return(_a0 port.TransferRecord, _a1 error) *MockTransferStore_FindTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferStore_FindTransfer_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.TransferRecord, error)) *MockTransferStore_FindTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// ListBatchItems provides a mock function with given fields: ctx, tenant, batchID
func (_m *MockTransferStore) ListBatchItems(ctx context.Context, tenant valueobject.TenantID, batchID string) ([]port.BatchItem, error) {
	ret := _m.Called(ctx, tenant, batchID)

	if len(ret) == 0 {
		panic("no return value specified for ListBatchItems")
	}

	var r0 []port.BatchItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) ([]port.BatchItem, error)); ok {
		return rf(ctx, tenant, batchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) []port.BatchItem); ok {
		r0 = rf(ctx, tenant, batchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.BatchItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, batchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferStore_ListBatchItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBatchItems'
type MockTransferStore_ListBatchItems_Call struct {
	*mock.Call
}

// ListBatchItems is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - batchID string
func (_e *MockTransferStore_Expecter) ListBatchItems(ctx interface{}, tenant interface{}, batchID interface{}) *MockTransferStore_ListBatchItems_Call {
	return &MockTransferStore_ListBatchItems_Call{Call: _e.mock.On("ListBatchItems", ctx, tenant, batchID)}
}

func (_c *MockTransferStore_ListBatchItems_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, batchID string)) *MockTransferStore_ListBatchItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockTransferStore_ListBatchItems_Call) Return(_a0 []port.BatchItem, _a1 error) *MockTransferStore_ListBatchItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferStore_ListBatchItems_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) ([]port.BatchItem, error)) *MockTransferStore_ListBatchItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfers provides a mock function with given fields: ctx, filter
func (_m *MockTransferStore) ListTransfers(ctx context.Context, filter port.TransferListFilter) ([]port.TransferRecord, string, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTransfers")
	}

	var r0 []port.TransferRecord
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferListFilter) ([]port.TransferRecord, string, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferListFilter) []port.TransferRecord); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.TransferRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferListFilter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, port.TransferListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransferStore_ListTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfers'
type MockTransferStore_ListTransfers_Call struct {
	*mock.Call
}

// ListTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter port.TransferListFilter
func (_e *MockTransferStore_Expecter) ListTransfers(ctx interface{}, filter interface{}) *MockTransferStore_ListTransfers_Call {
	return &MockTransferStore_ListTransfers_Call{Call: _e.mock.On("ListTransfers", ctx, filter)}
}

func (_c *MockTransferStore_ListTransfers_Call) Run(run func(ctx context.Context, filter port.TransferListFilter)) *MockTransferStore_ListTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferListFilter))
	})
	return _c
}

func (_c *MockTransferStore_ListTransfers_Call) Return(_a0 []port.TransferRecord, _a1 string, _a2 error) *MockTransferStore_ListTransfers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransferStore_ListTransfers_Call) RunAndReturn(run func(context.Context, port.TransferListFilter) ([]port.TransferRecord, string, error)) *MockTransferStore_ListTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatchItem provides a mock function with given fields: ctx, tenant, batchID, index, status, errorCode
func (_m *MockTransferStore) UpdateBatchItem(ctx context.Context, tenant valueobject.TenantID, batchID string, index int, status string, errorCode string) error {
	ret := _m.Called(ctx, tenant, batchID, index, status, errorCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatchItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, int, string, string) error); ok {
		r0 = rf(ctx, tenant, batchID, index, status, errorCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStore_UpdateBatchItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatchItem'
type MockTransferStore_UpdateBatchItem_Call struct {
	*mock.Call
}

// UpdateBatchItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - batchID string
//   - index int
//   - status string
//   - errorCode string
func (_e *MockTransferStore_Expecter) UpdateBatchItem(ctx interface{}, tenant interface{}, batchID interface{}, index interface{}, status interface{}, errorCode interface{}) *MockTransferStore_UpdateBatchItem_Call {
	return &MockTransferStore_UpdateBatchItem_Call{Call: _e.mock.On("UpdateBatchItem", ctx, tenant, batchID, index, status, errorCode)}
}

func (_c *MockTransferStore_UpdateBatchItem_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, batchID string, index int, status string, errorCode string)) *MockTransferStore_UpdateBatchItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(int), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockTransferStore_UpdateBatchItem_Call) Return(_a0 error) *MockTransferStore_UpdateBatchItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStore_UpdateBatchItem_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, int, string, string) error) *MockTransferStore_UpdateBatchItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatchState provides a mock function with given fields: ctx, tenant, id, state
func (_m *MockTransferStore) UpdateBatchState(ctx context.Context, tenant valueobject.TenantID, id string, state string) error {
	ret := _m.Called(ctx, tenant, id, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatchState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string) error); ok {
		r0 = rf(ctx, tenant, id, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStore_UpdateBatchState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatchState'
type MockTransferStore_UpdateBatchState_Call struct {
	*mock.Call
}

// UpdateBatchState is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id string
//   - state string
func (_e *MockTransferStore_Expecter) UpdateBatchState(ctx interface{}, tenant interface{}, id interface{}, state interface{}) *MockTransferStore_UpdateBatchState_Call {
	return &MockTransferStore_UpdateBatchState_Call{Call: _e.mock.On("UpdateBatchState", ctx, tenant, id, state)}
}

func (_c *MockTransferStore_UpdateBatchState_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id string, state string)) *MockTransferStore_UpdateBatchState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTransferStore_UpdateBatchState_Call) Return(_a0 error) *MockTransferStore_UpdateBatchState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStore_UpdateBatchState_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, string) error) *MockTransferStore_UpdateBatchState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransfer provides a mock function with given fields: ctx, record
func (_m *MockTransferStore) UpdateTransfer(ctx context.Context, record port.TransferRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStore_UpdateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransfer'
type MockTransferStore_UpdateTransfer_Call struct {
	*mock.Call
}

// UpdateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - record port.TransferRecord
func (_e *MockTransferStore_Expecter) UpdateTransfer(ctx interface{}, record interface{}) *MockTransferStore_UpdateTransfer_Call {
	return &MockTransferStore_UpdateTransfer_Call{Call: _e.mock.On("UpdateTransfer", ctx, record)}
}

func (_c *MockTransferStore_UpdateTransfer_Call) Run(run func(ctx context.Context, record port.TransferRecord)) *MockTransferStore_UpdateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferRecord))
	})
	return _c
}

func (_c *MockTransferStore_UpdateTransfer_Call) Return(_a0 error) *MockTransferStore_UpdateTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStore_UpdateTransfer_Call) RunAndReturn(run func(context.Context, port.TransferRecord) error) *MockTransferStore_UpdateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferStore creates a new instance of MockTransferStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferStore {
	mock := &MockTransferStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
