// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockconsumer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPSender is an autogenerated mock type for the HTTPSender type
type MockHTTPSender struct {
	mock.Mock
}

type MockHTTPSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPSender) EXPECT() *MockHTTPSender_Expecter {
	return &MockHTTPSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, url, headers, body
func (_m *MockHTTPSender) Send(ctx context.Context, url string, headers map[string]string, body []byte) error {
	ret := _m.Called(ctx, url, headers, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, []byte) error); ok {
		r0 = rf(ctx, url, headers, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockHTTPSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - headers map[string]string
//   - body []byte
func (_e *MockHTTPSender_Expecter) Send(ctx interface{}, url interface{}, headers interface{}, body interface{}) *MockHTTPSender_Send_Call {
	return &MockHTTPSender_Send_Call{Call: _e.mock.On("Send", ctx, url, headers, body)}
}

func (_c *MockHTTPSender_Send_Call) Run(run func(ctx context.Context, url string, headers map[string]string, body []byte)) *MockHTTPSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string), args[3].([]byte))
	})
	return _c
}

func (_c *MockHTTPSender_Send_Call) Return(_a0 error) *MockHTTPSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPSender_Send_Call) RunAndReturn(run func(context.Context, string, map[string]string, []byte) error) *MockHTTPSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPSender creates a new instance of MockHTTPSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPSender {
	mock := &MockHTTPSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
