// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocketcd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLeaderElector is an autogenerated mock type for the LeaderElector type
type MockLeaderElector struct {
	mock.Mock
}

type MockLeaderElector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderElector) EXPECT() *MockLeaderElector_Expecter {
	return &MockLeaderElector_Expecter{mock: &_m.Mock}
}

// Campaign provides a mock function with given fields: ctx, candidateID
func (_m *MockLeaderElector) Campaign(ctx context.Context, candidateID string) error {
	ret := _m.Called(ctx, candidateID)

	if len(ret) == 0 {
		panic("no return value specified for Campaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, candidateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderElector_Campaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Campaign'
type MockLeaderElector_Campaign_Call struct {
	*mock.Call
}

// Campaign is a helper method to define mock.On call
//   - ctx context.Context
//   - candidateID string
func (_e *MockLeaderElector_Expecter) Campaign(ctx interface{}, candidateID interface{}) *MockLeaderElector_Campaign_Call {
	return &MockLeaderElector_Campaign_Call{Call: _e.mock.On("Campaign", ctx, candidateID)}
}

func (_c *MockLeaderElector_Campaign_Call) Run(run func(ctx context.Context, candidateID string)) *MockLeaderElector_Campaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLeaderElector_Campaign_Call) Return(_a0 error) *MockLeaderElector_Campaign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderElector_Campaign_Call) RunAndReturn(run func(context.Context, string) error) *MockLeaderElector_Campaign_Call {
	_c.Call.Return(run)
	return _c
}

// Leader provides a mock function with given fields: ctx
func (_m *MockLeaderElector) Leader(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Leader")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderElector_Leader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leader'
type MockLeaderElector_Leader_Call struct {
	*mock.Call
}

// Leader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLeaderElector_Expecter) Leader(ctx interface{}) *MockLeaderElector_Leader_Call {
	return &MockLeaderElector_Leader_Call{Call: _e.mock.On("Leader", ctx)}
}

func (_c *MockLeaderElector_Leader_Call) Run(run func(ctx context.Context)) *MockLeaderElector_Leader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLeaderElector_Leader_Call) Return(_a0 string, _a1 error) *MockLeaderElector_Leader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderElector_Leader_Call) RunAndReturn(run func(context.Context) (string, error)) *MockLeaderElector_Leader_Call {
	_c.Call.Return(run)
	return _c
}

// Prefix provides a mock function with no fields
func (_m *MockLeaderElector) Prefix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prefix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLeaderElector_Prefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prefix'
type MockLeaderElector_Prefix_Call struct {
	*mock.Call
}

// Prefix is a helper method to define mock.On call
func (_e *MockLeaderElector_Expecter) Prefix() *MockLeaderElector_Prefix_Call {
	return &MockLeaderElector_Prefix_Call{Call: _e.mock.On("Prefix")}
}

func (_c *MockLeaderElector_Prefix_Call) Run(run func()) *MockLeaderElector_Prefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLeaderElector_Prefix_Call) Return(_a0 string) *MockLeaderElector_Prefix_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderElector_Prefix_Call) RunAndReturn(run func() string) *MockLeaderElector_Prefix_Call {
	_c.Call.Return(run)
	return _c
}

// Resign provides a mock function with given fields: ctx
func (_m *MockLeaderElector) Resign(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderElector_Resign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resign'
type MockLeaderElector_Resign_Call struct {
	*mock.Call
}

// Resign is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLeaderElector_Expecter) Resign(ctx interface{}) *MockLeaderElector_Resign_Call {
	return &MockLeaderElector_Resign_Call{Call: _e.mock.On("Resign", ctx)}
}

func (_c *MockLeaderElector_Resign_Call) Run(run func(ctx context.Context)) *MockLeaderElector_Resign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLeaderElector_Resign_Call) Return(_a0 error) *MockLeaderElector_Resign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderElector_Resign_Call) RunAndReturn(run func(context.Context) error) *MockLeaderElector_Resign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLeaderElector creates a new instance of MockLeaderElector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderElector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderElector {
	mock := &MockLeaderElector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
