// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocketcd

import mock "github.com/stretchr/testify/mock"

// MockWatchHandler is an autogenerated mock type for the WatchHandler type
type MockWatchHandler struct {
	mock.Mock
}

type MockWatchHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchHandler) EXPECT() *MockWatchHandler_Expecter {
	return &MockWatchHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: key, value
func (_m *MockWatchHandler) Execute(key []byte, value []byte) {
	_m.Called(key, value)
}

// MockWatchHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockWatchHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - key []byte
//   - value []byte
func (_e *MockWatchHandler_Expecter) Execute(key interface{}, value interface{}) *MockWatchHandler_Execute_Call {
	return &MockWatchHandler_Execute_Call{Call: _e.mock.On("Execute", key, value)}
}

func (_c *MockWatchHandler_Execute_Call) Run(run func(key []byte, value []byte)) *MockWatchHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockWatchHandler_Execute_Call) Return() *MockWatchHandler_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWatchHandler_Execute_Call) RunAndReturn(run func([]byte, []byte)) *MockWatchHandler_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockWatchHandler creates a new instance of MockWatchHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchHandler {
	mock := &MockWatchHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
