// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocketcd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	etcd "github.com/kadekutama/go-template/internal/infrastructure/coordination/etcd"
)

// MockWatcher is an autogenerated mock type for the Watcher type
type MockWatcher struct {
	mock.Mock
}

type MockWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatcher) EXPECT() *MockWatcher_Expecter {
	return &MockWatcher_Expecter{mock: &_m.Mock}
}

// Cached provides a mock function with given fields: key
func (_m *MockWatcher) Cached(key string) ([]byte, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Cached")
	}

	var r0 []byte
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockWatcher_Cached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cached'
type MockWatcher_Cached_Call struct {
	*mock.Call
}

// Cached is a helper method to define mock.On call
//   - key string
func (_e *MockWatcher_Expecter) Cached(key interface{}) *MockWatcher_Cached_Call {
	return &MockWatcher_Cached_Call{Call: _e.mock.On("Cached", key)}
}

func (_c *MockWatcher_Cached_Call) Run(run func(key string)) *MockWatcher_Cached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWatcher_Cached_Call) Return(_a0 []byte, _a1 bool) *MockWatcher_Cached_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWatcher_Cached_Call) RunAndReturn(run func(string) ([]byte, bool)) *MockWatcher_Cached_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MockWatcher) Err() <-chan error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 <-chan error
	if rf, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	return r0
}

// MockWatcher_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockWatcher_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockWatcher_Expecter) Err() *MockWatcher_Err_Call {
	return &MockWatcher_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockWatcher_Err_Call) Run(run func()) *MockWatcher_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcher_Err_Call) Return(_a0 <-chan error) *MockWatcher_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWatcher_Err_Call) RunAndReturn(run func() <-chan error) *MockWatcher_Err_Call {
	_c.Call.Return(run)
	return _c
}

// WatchPrefix provides a mock function with given fields: ctx, prefix, onChange
func (_m *MockWatcher) WatchPrefix(ctx context.Context, prefix string, onChange etcd.WatchHandler) error {
	ret := _m.Called(ctx, prefix, onChange)

	if len(ret) == 0 {
		panic("no return value specified for WatchPrefix")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, etcd.WatchHandler) error); ok {
		r0 = rf(ctx, prefix, onChange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWatcher_WatchPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchPrefix'
type MockWatcher_WatchPrefix_Call struct {
	*mock.Call
}

// WatchPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - onChange etcd.WatchHandler
func (_e *MockWatcher_Expecter) WatchPrefix(ctx interface{}, prefix interface{}, onChange interface{}) *MockWatcher_WatchPrefix_Call {
	return &MockWatcher_WatchPrefix_Call{Call: _e.mock.On("WatchPrefix", ctx, prefix, onChange)}
}

func (_c *MockWatcher_WatchPrefix_Call) Run(run func(ctx context.Context, prefix string, onChange etcd.WatchHandler)) *MockWatcher_WatchPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(etcd.WatchHandler))
	})
	return _c
}

func (_c *MockWatcher_WatchPrefix_Call) Return(_a0 error) *MockWatcher_WatchPrefix_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWatcher_WatchPrefix_Call) RunAndReturn(run func(context.Context, string, etcd.WatchHandler) error) *MockWatcher_WatchPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWatcher creates a new instance of MockWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatcher {
	mock := &MockWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
