DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'ledgers', 'accounts', 'postings', 'entries', 'holds',
        'checkpoints', 'idempotency_records', 'outbox_events', 'tenants',
        'workflows', 'recon_sources', 'recon_match_groups', 'recon_breaks',
        'periods', 'reports', 'approvals', 'inbox_receipts', 'audit_refs'
    ] LOOP
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
        EXECUTE format('ALTER TABLE IF EXISTS %I NO FORCE ROW LEVEL SECURITY', t);
    END LOOP;
END
$$;

ALTER TABLE IF EXISTS audit_refs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inbox_receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS approvals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS periods DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recon_breaks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recon_match_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recon_sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workflows DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS outbox_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS idempotency_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS checkpoints DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS holds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS postings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ledgers DISABLE ROW LEVEL SECURITY;
