DROP TRIGGER IF EXISTS trg_entries_balanced ON entries;
DROP FUNCTION IF EXISTS check_posting_balanced();
DROP TRIGGER IF EXISTS trg_entries_immutable ON entries;
DROP TRIGGER IF EXISTS trg_postings_immutable ON postings;
DROP FUNCTION IF EXISTS prevent_posted_mutation();
DROP TABLE IF EXISTS checkpoints;
DROP TABLE IF EXISTS holds;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS postings;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS ledgers;
