// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "github.com/kadekutama/go-template/internal/application/service"
)

// MockUsageStore is an autogenerated mock type for the UsageStore type
type MockUsageStore struct {
	mock.Mock
}

type MockUsageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageStore) EXPECT() *MockUsageStore_Expecter {
	return &MockUsageStore_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function with given fields: ctx, event
func (_m *MockUsageStore) AppendEvent(ctx context.Context, event service.UsageEvent) (bool, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UsageEvent) (bool, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UsageEvent) bool); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UsageEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsageStore_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type MockUsageStore_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event service.UsageEvent
func (_e *MockUsageStore_Expecter) AppendEvent(ctx interface{}, event interface{}) *MockUsageStore_AppendEvent_Call {
	return &MockUsageStore_AppendEvent_Call{Call: _e.mock.On("AppendEvent", ctx, event)}
}

func (_c *MockUsageStore_AppendEvent_Call) Run(run func(ctx context.Context, event service.UsageEvent)) *MockUsageStore_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.UsageEvent))
	})
	return _c
}

func (_c *MockUsageStore_AppendEvent_Call) Return(_a0 bool, _a1 error) *MockUsageStore_AppendEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsageStore_AppendEvent_Call) RunAndReturn(run func(context.Context, service.UsageEvent) (bool, error)) *MockUsageStore_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DayTotals provides a mock function with given fields: ctx, tenantID, day
func (_m *MockUsageStore) DayTotals(ctx context.Context, tenantID string, day string) (map[service.UsageKind]int64, error) {
	ret := _m.Called(ctx, tenantID, day)

	if len(ret) == 0 {
		panic("no return value specified for DayTotals")
	}

	var r0 map[service.UsageKind]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[service.UsageKind]int64, error)); ok {
		return rf(ctx, tenantID, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[service.UsageKind]int64); ok {
		r0 = rf(ctx, tenantID, day)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[service.UsageKind]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsageStore_DayTotals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DayTotals'
type MockUsageStore_DayTotals_Call struct {
	*mock.Call
}

// DayTotals is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - day string
func (_e *MockUsageStore_Expecter) DayTotals(ctx interface{}, tenantID interface{}, day interface{}) *MockUsageStore_DayTotals_Call {
	return &MockUsageStore_DayTotals_Call{Call: _e.mock.On("DayTotals", ctx, tenantID, day)}
}

func (_c *MockUsageStore_DayTotals_Call) Run(run func(ctx context.Context, tenantID string, day string)) *MockUsageStore_DayTotals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUsageStore_DayTotals_Call) Return(_a0 map[service.UsageKind]int64, _a1 error) *MockUsageStore_DayTotals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsageStore_DayTotals_Call) RunAndReturn(run func(context.Context, string, string) (map[service.UsageKind]int64, error)) *MockUsageStore_DayTotals_Call {
	_c.Call.Return(run)
	return _c
}

// PeriodLines provides a mock function with given fields: ctx, tenantID, fromDay, toDay
func (_m *MockUsageStore) PeriodLines(ctx context.Context, tenantID string, fromDay string, toDay string) ([]service.DailyUsage, error) {
	ret := _m.Called(ctx, tenantID, fromDay, toDay)

	if len(ret) == 0 {
		panic("no return value specified for PeriodLines")
	}

	var r0 []service.DailyUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]service.DailyUsage, error)); ok {
		return rf(ctx, tenantID, fromDay, toDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []service.DailyUsage); ok {
		r0 = rf(ctx, tenantID, fromDay, toDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.DailyUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, fromDay, toDay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsageStore_PeriodLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodLines'
type MockUsageStore_PeriodLines_Call struct {
	*mock.Call
}

// PeriodLines is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - fromDay string
//   - toDay string
func (_e *MockUsageStore_Expecter) PeriodLines(ctx interface{}, tenantID interface{}, fromDay interface{}, toDay interface{}) *MockUsageStore_PeriodLines_Call {
	return &MockUsageStore_PeriodLines_Call{Call: _e.mock.On("PeriodLines", ctx, tenantID, fromDay, toDay)}
}

func (_c *MockUsageStore_PeriodLines_Call) Run(run func(ctx context.Context, tenantID string, fromDay string, toDay string)) *MockUsageStore_PeriodLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUsageStore_PeriodLines_Call) Return(_a0 []service.DailyUsage, _a1 error) *MockUsageStore_PeriodLines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsageStore_PeriodLines_Call) RunAndReturn(run func(context.Context, string, string, string) ([]service.DailyUsage, error)) *MockUsageStore_PeriodLines_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsageStore creates a new instance of MockUsageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageStore {
	mock := &MockUsageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
