// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, account
func (_m *MockAccountRepository) Create(ctx context.Context, account entity.AccountData) (entity.AccountData, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.AccountData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AccountData) (entity.AccountData, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.AccountData) entity.AccountData); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Get(0).(entity.AccountData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.AccountData) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account entity.AccountData
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, account entity.AccountData)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AccountData))
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(_a0 entity.AccountData, _a1 error) *MockAccountRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(context.Context, entity.AccountData) (entity.AccountData, error)) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenant, id
func (_m *MockAccountRepository) FindByID(ctx context.Context, tenant valueobject.TenantID, id valueobject.AccountID) (entity.AccountData, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.AccountData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID) (entity.AccountData, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID) entity.AccountData); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(entity.AccountData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.AccountID) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAccountRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id valueobject.AccountID
func (_e *MockAccountRepository_Expecter) FindByID(ctx interface{}, tenant interface{}, id interface{}) *MockAccountRepository_FindByID_Call {
	return &MockAccountRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenant, id)}
}

func (_c *MockAccountRepository_FindByID_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id valueobject.AccountID)) *MockAccountRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.AccountID))
	})
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) Return(_a0 entity.AccountData, _a1 error) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_FindByID_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.AccountID) (entity.AccountData, error)) *MockAccountRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTenant provides a mock function with given fields: ctx, tenant, cursor, limit
func (_m *MockAccountRepository) FindByTenant(ctx context.Context, tenant valueobject.TenantID, cursor string, limit int) ([]entity.AccountData, string, error) {
	ret := _m.Called(ctx, tenant, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByTenant")
	}

	var r0 []entity.AccountData
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, int) ([]entity.AccountData, string, error)); ok {
		return rf(ctx, tenant, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, int) []entity.AccountData); ok {
		r0 = rf(ctx, tenant, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AccountData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, int) string); ok {
		r1 = rf(ctx, tenant, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, valueobject.TenantID, string, int) error); ok {
		r2 = rf(ctx, tenant, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccountRepository_FindByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTenant'
type MockAccountRepository_FindByTenant_Call struct {
	*mock.Call
}

// FindByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - cursor string
//   - limit int
func (_e *MockAccountRepository_Expecter) FindByTenant(ctx interface{}, tenant interface{}, cursor interface{}, limit interface{}) *MockAccountRepository_FindByTenant_Call {
	return &MockAccountRepository_FindByTenant_Call{Call: _e.mock.On("FindByTenant", ctx, tenant, cursor, limit)}
}

func (_c *MockAccountRepository_FindByTenant_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, cursor string, limit int)) *MockAccountRepository_FindByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockAccountRepository_FindByTenant_Call) Return(_a0 []entity.AccountData, _a1 string, _a2 error) *MockAccountRepository_FindByTenant_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAccountRepository_FindByTenant_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, int) ([]entity.AccountData, string, error)) *MockAccountRepository_FindByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetadata provides a mock function with given fields: ctx, account, expectedVersion
func (_m *MockAccountRepository) UpdateMetadata(ctx context.Context, account entity.AccountData, expectedVersion int64) error {
	ret := _m.Called(ctx, account, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AccountData, int64) error); ok {
		r0 = rf(ctx, account, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_UpdateMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetadata'
type MockAccountRepository_UpdateMetadata_Call struct {
	*mock.Call
}

// UpdateMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - account entity.AccountData
//   - expectedVersion int64
func (_e *MockAccountRepository_Expecter) UpdateMetadata(ctx interface{}, account interface{}, expectedVersion interface{}) *MockAccountRepository_UpdateMetadata_Call {
	return &MockAccountRepository_UpdateMetadata_Call{Call: _e.mock.On("UpdateMetadata", ctx, account, expectedVersion)}
}

func (_c *MockAccountRepository_UpdateMetadata_Call) Run(run func(ctx context.Context, account entity.AccountData, expectedVersion int64)) *MockAccountRepository_UpdateMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.AccountData), args[2].(int64))
	})
	return _c
}

func (_c *MockAccountRepository_UpdateMetadata_Call) Return(_a0 error) *MockAccountRepository_UpdateMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_UpdateMetadata_Call) RunAndReturn(run func(context.Context, entity.AccountData, int64) error) *MockAccountRepository_UpdateMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tenant, id, status, expectedVersion
func (_m *MockAccountRepository) UpdateStatus(ctx context.Context, tenant valueobject.TenantID, id valueobject.AccountID, status valueobject.AccountStatus, expectedVersion int64) error {
	ret := _m.Called(ctx, tenant, id, status, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID, valueobject.AccountStatus, int64) error); ok {
		r0 = rf(ctx, tenant, id, status, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAccountRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id valueobject.AccountID
//   - status valueobject.AccountStatus
//   - expectedVersion int64
func (_e *MockAccountRepository_Expecter) UpdateStatus(ctx interface{}, tenant interface{}, id interface{}, status interface{}, expectedVersion interface{}) *MockAccountRepository_UpdateStatus_Call {
	return &MockAccountRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tenant, id, status, expectedVersion)}
}

func (_c *MockAccountRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id valueobject.AccountID, status valueobject.AccountStatus, expectedVersion int64)) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.AccountID), args[3].(valueobject.AccountStatus), args[4].(int64))
	})
	return _c
}

func (_c *MockAccountRepository_UpdateStatus_Call) Return(_a0 error) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.AccountID, valueobject.AccountStatus, int64) error) *MockAccountRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
