// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/kadekutama/go-template/internal/domain/repository"
)

// MockAMLProvider is an autogenerated mock type for the AMLProvider type
type MockAMLProvider struct {
	mock.Mock
}

type MockAMLProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAMLProvider) EXPECT() *MockAMLProvider_Expecter {
	return &MockAMLProvider_Expecter{mock: &_m.Mock}
}

// Screen provides a mock function with given fields: ctx, req
func (_m *MockAMLProvider) Screen(ctx context.Context, req repository.ScreeningRequest) (repository.ScreeningDecision, string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Screen")
	}

	var r0 repository.ScreeningDecision
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScreeningRequest) (repository.ScreeningDecision, string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScreeningRequest) repository.ScreeningDecision); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(repository.ScreeningDecision)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ScreeningRequest) string); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ScreeningRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAMLProvider_Screen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Screen'
type MockAMLProvider_Screen_Call struct {
	*mock.Call
}

// Screen is a helper method to define mock.On call
//   - ctx context.Context
//   - req repository.ScreeningRequest
func (_e *MockAMLProvider_Expecter) Screen(ctx interface{}, req interface{}) *MockAMLProvider_Screen_Call {
	return &MockAMLProvider_Screen_Call{Call: _e.mock.On("Screen", ctx, req)}
}

func (_c *MockAMLProvider_Screen_Call) Run(run func(ctx context.Context, req repository.ScreeningRequest)) *MockAMLProvider_Screen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ScreeningRequest))
	})
	return _c
}

func (_c *MockAMLProvider_Screen_Call) Return(_a0 repository.ScreeningDecision, _a1 string, _a2 error) *MockAMLProvider_Screen_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAMLProvider_Screen_Call) RunAndReturn(run func(context.Context, repository.ScreeningRequest) (repository.ScreeningDecision, string, error)) *MockAMLProvider_Screen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAMLProvider creates a new instance of MockAMLProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAMLProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAMLProvider {
	mock := &MockAMLProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
