// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockEntryReader is an autogenerated mock type for the EntryReader type
type MockEntryReader struct {
	mock.Mock
}

type MockEntryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntryReader) EXPECT() *MockEntryReader_Expecter {
	return &MockEntryReader_Expecter{mock: &_m.Mock}
}

// FindByAccount provides a mock function with given fields: ctx, tenant, account, cursor, limit
func (_m *MockEntryReader) FindByAccount(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID, cursor string, limit int) ([]entity.Entry, string, error) {
	ret := _m.Called(ctx, tenant, account, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccount")
	}

	var r0 []entity.Entry
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) ([]entity.Entry, string, error)); ok {
		return rf(ctx, tenant, account, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) []entity.Entry); ok {
		r0 = rf(ctx, tenant, account, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) string); ok {
		r1 = rf(ctx, tenant, account, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) error); ok {
		r2 = rf(ctx, tenant, account, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEntryReader_FindByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccount'
type MockEntryReader_FindByAccount_Call struct {
	*mock.Call
}

// FindByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - account valueobject.AccountID
//   - cursor string
//   - limit int
func (_e *MockEntryReader_Expecter) FindByAccount(ctx interface{}, tenant interface{}, account interface{}, cursor interface{}, limit interface{}) *MockEntryReader_FindByAccount_Call {
	return &MockEntryReader_FindByAccount_Call{Call: _e.mock.On("FindByAccount", ctx, tenant, account, cursor, limit)}
}

func (_c *MockEntryReader_FindByAccount_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID, cursor string, limit int)) *MockEntryReader_FindByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.AccountID), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockEntryReader_FindByAccount_Call) Return(_a0 []entity.Entry, _a1 string, _a2 error) *MockEntryReader_FindByAccount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEntryReader_FindByAccount_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) ([]entity.Entry, string, error)) *MockEntryReader_FindByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPosting provides a mock function with given fields: ctx, tenant, posting
func (_m *MockEntryReader) FindByPosting(ctx context.Context, tenant valueobject.TenantID, posting valueobject.PostingID) ([]entity.Entry, error) {
	ret := _m.Called(ctx, tenant, posting)

	if len(ret) == 0 {
		panic("no return value specified for FindByPosting")
	}

	var r0 []entity.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.PostingID) ([]entity.Entry, error)); ok {
		return rf(ctx, tenant, posting)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.PostingID) []entity.Entry); ok {
		r0 = rf(ctx, tenant, posting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.PostingID) error); ok {
		r1 = rf(ctx, tenant, posting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEntryReader_FindByPosting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPosting'
type MockEntryReader_FindByPosting_Call struct {
	*mock.Call
}

// FindByPosting is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - posting valueobject.PostingID
func (_e *MockEntryReader_Expecter) FindByPosting(ctx interface{}, tenant interface{}, posting interface{}) *MockEntryReader_FindByPosting_Call {
	return &MockEntryReader_FindByPosting_Call{Call: _e.mock.On("FindByPosting", ctx, tenant, posting)}
}

func (_c *MockEntryReader_FindByPosting_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, posting valueobject.PostingID)) *MockEntryReader_FindByPosting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.PostingID))
	})
	return _c
}

func (_c *MockEntryReader_FindByPosting_Call) Return(_a0 []entity.Entry, _a1 error) *MockEntryReader_FindByPosting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEntryReader_FindByPosting_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.PostingID) ([]entity.Entry, error)) *MockEntryReader_FindByPosting_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEntryReader creates a new instance of MockEntryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntryReader {
	mock := &MockEntryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
