// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockHoldRepository is an autogenerated mock type for the HoldRepository type
type MockHoldRepository struct {
	mock.Mock
}

type MockHoldRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHoldRepository) EXPECT() *MockHoldRepository_Expecter {
	return &MockHoldRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, hold
func (_m *MockHoldRepository) Create(ctx context.Context, hold entity.HoldData) (entity.HoldData, error) {
	ret := _m.Called(ctx, hold)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.HoldData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.HoldData) (entity.HoldData, error)); ok {
		return rf(ctx, hold)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.HoldData) entity.HoldData); ok {
		r0 = rf(ctx, hold)
	} else {
		r0 = ret.Get(0).(entity.HoldData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.HoldData) error); ok {
		r1 = rf(ctx, hold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHoldRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHoldRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - hold entity.HoldData
func (_e *MockHoldRepository_Expecter) Create(ctx interface{}, hold interface{}) *MockHoldRepository_Create_Call {
	return &MockHoldRepository_Create_Call{Call: _e.mock.On("Create", ctx, hold)}
}

func (_c *MockHoldRepository_Create_Call) Run(run func(ctx context.Context, hold entity.HoldData)) *MockHoldRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.HoldData))
	})
	return _c
}

func (_c *MockHoldRepository_Create_Call) Return(_a0 entity.HoldData, _a1 error) *MockHoldRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHoldRepository_Create_Call) RunAndReturn(run func(context.Context, entity.HoldData) (entity.HoldData, error)) *MockHoldRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByAccount provides a mock function with given fields: ctx, tenant, account
func (_m *MockHoldRepository) FindActiveByAccount(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID) ([]entity.HoldData, error) {
	ret := _m.Called(ctx, tenant, account)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByAccount")
	}

	var r0 []entity.HoldData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID) ([]entity.HoldData, error)); ok {
		return rf(ctx, tenant, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID) []entity.HoldData); ok {
		r0 = rf(ctx, tenant, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.HoldData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.AccountID) error); ok {
		r1 = rf(ctx, tenant, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHoldRepository_FindActiveByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByAccount'
type MockHoldRepository_FindActiveByAccount_Call struct {
	*mock.Call
}

// FindActiveByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - account valueobject.AccountID
func (_e *MockHoldRepository_Expecter) FindActiveByAccount(ctx interface{}, tenant interface{}, account interface{}) *MockHoldRepository_FindActiveByAccount_Call {
	return &MockHoldRepository_FindActiveByAccount_Call{Call: _e.mock.On("FindActiveByAccount", ctx, tenant, account)}
}

func (_c *MockHoldRepository_FindActiveByAccount_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID)) *MockHoldRepository_FindActiveByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.AccountID))
	})
	return _c
}

func (_c *MockHoldRepository_FindActiveByAccount_Call) Return(_a0 []entity.HoldData, _a1 error) *MockHoldRepository_FindActiveByAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHoldRepository_FindActiveByAccount_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.AccountID) ([]entity.HoldData, error)) *MockHoldRepository_FindActiveByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenant, id
func (_m *MockHoldRepository) FindByID(ctx context.Context, tenant valueobject.TenantID, id valueobject.HoldID) (entity.HoldData, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.HoldData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.HoldID) (entity.HoldData, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.HoldID) entity.HoldData); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(entity.HoldData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.HoldID) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHoldRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHoldRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id valueobject.HoldID
func (_e *MockHoldRepository_Expecter) FindByID(ctx interface{}, tenant interface{}, id interface{}) *MockHoldRepository_FindByID_Call {
	return &MockHoldRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenant, id)}
}

func (_c *MockHoldRepository_FindByID_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id valueobject.HoldID)) *MockHoldRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.HoldID))
	})
	return _c
}

func (_c *MockHoldRepository_FindByID_Call) Return(_a0 entity.HoldData, _a1 error) *MockHoldRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHoldRepository_FindByID_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.HoldID) (entity.HoldData, error)) *MockHoldRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, hold, expectedVersion
func (_m *MockHoldRepository) Update(ctx context.Context, hold entity.HoldData, expectedVersion int64) error {
	ret := _m.Called(ctx, hold, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.HoldData, int64) error); ok {
		r0 = rf(ctx, hold, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHoldRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHoldRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - hold entity.HoldData
//   - expectedVersion int64
func (_e *MockHoldRepository_Expecter) Update(ctx interface{}, hold interface{}, expectedVersion interface{}) *MockHoldRepository_Update_Call {
	return &MockHoldRepository_Update_Call{Call: _e.mock.On("Update", ctx, hold, expectedVersion)}
}

func (_c *MockHoldRepository_Update_Call) Run(run func(ctx context.Context, hold entity.HoldData, expectedVersion int64)) *MockHoldRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.HoldData), args[2].(int64))
	})
	return _c
}

func (_c *MockHoldRepository_Update_Call) Return(_a0 error) *MockHoldRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHoldRepository_Update_Call) RunAndReturn(run func(context.Context, entity.HoldData, int64) error) *MockHoldRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHoldRepository creates a new instance of MockHoldRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHoldRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHoldRepository {
	mock := &MockHoldRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
