// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockLedgerRepository is an autogenerated mock type for the LedgerRepository type
type MockLedgerRepository struct {
	mock.Mock
}

type MockLedgerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerRepository) EXPECT() *MockLedgerRepository_Expecter {
	return &MockLedgerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ledger
func (_m *MockLedgerRepository) Create(ctx context.Context, ledger entity.Ledger) (entity.Ledger, error) {
	ret := _m.Called(ctx, ledger)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.Ledger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ledger) (entity.Ledger, error)); ok {
		return rf(ctx, ledger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Ledger) entity.Ledger); ok {
		r0 = rf(ctx, ledger)
	} else {
		r0 = ret.Get(0).(entity.Ledger)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Ledger) error); ok {
		r1 = rf(ctx, ledger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLedgerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ledger entity.Ledger
func (_e *MockLedgerRepository_Expecter) Create(ctx interface{}, ledger interface{}) *MockLedgerRepository_Create_Call {
	return &MockLedgerRepository_Create_Call{Call: _e.mock.On("Create", ctx, ledger)}
}

func (_c *MockLedgerRepository_Create_Call) Run(run func(ctx context.Context, ledger entity.Ledger)) *MockLedgerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Ledger))
	})
	return _c
}

func (_c *MockLedgerRepository_Create_Call) Return(_a0 entity.Ledger, _a1 error) *MockLedgerRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerRepository_Create_Call) RunAndReturn(run func(context.Context, entity.Ledger) (entity.Ledger, error)) *MockLedgerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenant, id
func (_m *MockLedgerRepository) FindByID(ctx context.Context, tenant valueobject.TenantID, id valueobject.LedgerID) (entity.Ledger, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.Ledger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.LedgerID) (entity.Ledger, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.LedgerID) entity.Ledger); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(entity.Ledger)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.LedgerID) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockLedgerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id valueobject.LedgerID
func (_e *MockLedgerRepository_Expecter) FindByID(ctx interface{}, tenant interface{}, id interface{}) *MockLedgerRepository_FindByID_Call {
	return &MockLedgerRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenant, id)}
}

func (_c *MockLedgerRepository_FindByID_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id valueobject.LedgerID)) *MockLedgerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.LedgerID))
	})
	return _c
}

func (_c *MockLedgerRepository_FindByID_Call) Return(_a0 entity.Ledger, _a1 error) *MockLedgerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerRepository_FindByID_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.LedgerID) (entity.Ledger, error)) *MockLedgerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTenant provides a mock function with given fields: ctx, tenant
func (_m *MockLedgerRepository) ListByTenant(ctx context.Context, tenant valueobject.TenantID) ([]entity.Ledger, error) {
	ret := _m.Called(ctx, tenant)

	if len(ret) == 0 {
		panic("no return value specified for ListByTenant")
	}

	var r0 []entity.Ledger
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID) ([]entity.Ledger, error)); ok {
		return rf(ctx, tenant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID) []entity.Ledger); ok {
		r0 = rf(ctx, tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ledger)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID) error); ok {
		r1 = rf(ctx, tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerRepository_ListByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTenant'
type MockLedgerRepository_ListByTenant_Call struct {
	*mock.Call
}

// ListByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
func (_e *MockLedgerRepository_Expecter) ListByTenant(ctx interface{}, tenant interface{}) *MockLedgerRepository_ListByTenant_Call {
	return &MockLedgerRepository_ListByTenant_Call{Call: _e.mock.On("ListByTenant", ctx, tenant)}
}

func (_c *MockLedgerRepository_ListByTenant_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID)) *MockLedgerRepository_ListByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID))
	})
	return _c
}

func (_c *MockLedgerRepository_ListByTenant_Call) Return(_a0 []entity.Ledger, _a1 error) *MockLedgerRepository_ListByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerRepository_ListByTenant_Call) RunAndReturn(run func(context.Context, valueobject.TenantID) ([]entity.Ledger, error)) *MockLedgerRepository_ListByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerRepository creates a new instance of MockLedgerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerRepository {
	mock := &MockLedgerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
