// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockdomain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockPostingRepository is an autogenerated mock type for the PostingRepository type
type MockPostingRepository struct {
	mock.Mock
}

type MockPostingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostingRepository) EXPECT() *MockPostingRepository_Expecter {
	return &MockPostingRepository_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx, posting
func (_m *MockPostingRepository) Commit(ctx context.Context, posting entity.PostingData) (entity.PostingData, error) {
	ret := _m.Called(ctx, posting)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 entity.PostingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PostingData) (entity.PostingData, error)); ok {
		return rf(ctx, posting)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PostingData) entity.PostingData); ok {
		r0 = rf(ctx, posting)
	} else {
		r0 = ret.Get(0).(entity.PostingData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PostingData) error); ok {
		r1 = rf(ctx, posting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostingRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockPostingRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - posting entity.PostingData
func (_e *MockPostingRepository_Expecter) Commit(ctx interface{}, posting interface{}) *MockPostingRepository_Commit_Call {
	return &MockPostingRepository_Commit_Call{Call: _e.mock.On("Commit", ctx, posting)}
}

func (_c *MockPostingRepository_Commit_Call) Run(run func(ctx context.Context, posting entity.PostingData)) *MockPostingRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.PostingData))
	})
	return _c
}

func (_c *MockPostingRepository_Commit_Call) Return(_a0 entity.PostingData, _a1 error) *MockPostingRepository_Commit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostingRepository_Commit_Call) RunAndReturn(run func(context.Context, entity.PostingData) (entity.PostingData, error)) *MockPostingRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAccount provides a mock function with given fields: ctx, tenant, account, cursor, limit
func (_m *MockPostingRepository) FindByAccount(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID, cursor string, limit int) ([]entity.PostingData, string, error) {
	ret := _m.Called(ctx, tenant, account, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByAccount")
	}

	var r0 []entity.PostingData
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) ([]entity.PostingData, string, error)); ok {
		return rf(ctx, tenant, account, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) []entity.PostingData); ok {
		r0 = rf(ctx, tenant, account, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PostingData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) string); ok {
		r1 = rf(ctx, tenant, account, cursor, limit)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) error); ok {
		r2 = rf(ctx, tenant, account, cursor, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPostingRepository_FindByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAccount'
type MockPostingRepository_FindByAccount_Call struct {
	*mock.Call
}

// FindByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - account valueobject.AccountID
//   - cursor string
//   - limit int
func (_e *MockPostingRepository_Expecter) FindByAccount(ctx interface{}, tenant interface{}, account interface{}, cursor interface{}, limit interface{}) *MockPostingRepository_FindByAccount_Call {
	return &MockPostingRepository_FindByAccount_Call{Call: _e.mock.On("FindByAccount", ctx, tenant, account, cursor, limit)}
}

func (_c *MockPostingRepository_FindByAccount_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, account valueobject.AccountID, cursor string, limit int)) *MockPostingRepository_FindByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.AccountID), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockPostingRepository_FindByAccount_Call) Return(_a0 []entity.PostingData, _a1 string, _a2 error) *MockPostingRepository_FindByAccount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPostingRepository_FindByAccount_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.AccountID, string, int) ([]entity.PostingData, string, error)) *MockPostingRepository_FindByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalReference provides a mock function with given fields: ctx, tenant, reference
func (_m *MockPostingRepository) FindByExternalReference(ctx context.Context, tenant valueobject.TenantID, reference string) (entity.PostingData, error) {
	ret := _m.Called(ctx, tenant, reference)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalReference")
	}

	var r0 entity.PostingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (entity.PostingData, error)); ok {
		return rf(ctx, tenant, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) entity.PostingData); ok {
		r0 = rf(ctx, tenant, reference)
	} else {
		r0 = ret.Get(0).(entity.PostingData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostingRepository_FindByExternalReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalReference'
type MockPostingRepository_FindByExternalReference_Call struct {
	*mock.Call
}

// FindByExternalReference is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - reference string
func (_e *MockPostingRepository_Expecter) FindByExternalReference(ctx interface{}, tenant interface{}, reference interface{}) *MockPostingRepository_FindByExternalReference_Call {
	return &MockPostingRepository_FindByExternalReference_Call{Call: _e.mock.On("FindByExternalReference", ctx, tenant, reference)}
}

func (_c *MockPostingRepository_FindByExternalReference_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, reference string)) *MockPostingRepository_FindByExternalReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockPostingRepository_FindByExternalReference_Call) Return(_a0 entity.PostingData, _a1 error) *MockPostingRepository_FindByExternalReference_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostingRepository_FindByExternalReference_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (entity.PostingData, error)) *MockPostingRepository_FindByExternalReference_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenant, id
func (_m *MockPostingRepository) FindByID(ctx context.Context, tenant valueobject.TenantID, id valueobject.PostingID) (entity.PostingData, error) {
	ret := _m.Called(ctx, tenant, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.PostingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.PostingID) (entity.PostingData, error)); ok {
		return rf(ctx, tenant, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, valueobject.PostingID) entity.PostingData); ok {
		r0 = rf(ctx, tenant, id)
	} else {
		r0 = ret.Get(0).(entity.PostingData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, valueobject.PostingID) error); ok {
		r1 = rf(ctx, tenant, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPostingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - id valueobject.PostingID
func (_e *MockPostingRepository_Expecter) FindByID(ctx interface{}, tenant interface{}, id interface{}) *MockPostingRepository_FindByID_Call {
	return &MockPostingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenant, id)}
}

func (_c *MockPostingRepository_FindByID_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, id valueobject.PostingID)) *MockPostingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(valueobject.PostingID))
	})
	return _c
}

func (_c *MockPostingRepository_FindByID_Call) Return(_a0 entity.PostingData, _a1 error) *MockPostingRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostingRepository_FindByID_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, valueobject.PostingID) (entity.PostingData, error)) *MockPostingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostingRepository creates a new instance of MockPostingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostingRepository {
	mock := &MockPostingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
