// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockstore

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockExpiringStore is an autogenerated mock type for the ExpiringStore type
type MockExpiringStore struct {
	mock.Mock
}

type MockExpiringStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpiringStore) EXPECT() *MockExpiringStore_Expecter {
	return &MockExpiringStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockExpiringStore) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpiringStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpiringStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockExpiringStore_Expecter) Delete(ctx interface{}, key interface{}) *MockExpiringStore_Delete_Call {
	return &MockExpiringStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockExpiringStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockExpiringStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpiringStore_Delete_Call) Return(_a0 error) *MockExpiringStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpiringStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockExpiringStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockExpiringStore) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpiringStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExpiringStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockExpiringStore_Expecter) Get(ctx interface{}, key interface{}) *MockExpiringStore_Get_Call {
	return &MockExpiringStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockExpiringStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockExpiringStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpiringStore_Get_Call) Return(_a0 []byte, _a1 error) *MockExpiringStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpiringStore_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockExpiringStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockExpiringStore) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExpiringStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockExpiringStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *MockExpiringStore_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockExpiringStore_Set_Call {
	return &MockExpiringStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockExpiringStore_Set_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *MockExpiringStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockExpiringStore_Set_Call) Return(_a0 error) *MockExpiringStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExpiringStore_Set_Call) RunAndReturn(run func(context.Context, string, []byte, time.Duration) error) *MockExpiringStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function with given fields: ctx, key
func (_m *MockExpiringStore) TTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpiringStore_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type MockExpiringStore_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockExpiringStore_Expecter) TTL(ctx interface{}, key interface{}) *MockExpiringStore_TTL_Call {
	return &MockExpiringStore_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *MockExpiringStore_TTL_Call) Run(run func(ctx context.Context, key string)) *MockExpiringStore_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExpiringStore_TTL_Call) Return(_a0 time.Duration, _a1 error) *MockExpiringStore_TTL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpiringStore_TTL_Call) RunAndReturn(run func(context.Context, string) (time.Duration, error)) *MockExpiringStore_TTL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpiringStore creates a new instance of MockExpiringStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpiringStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpiringStore {
	mock := &MockExpiringStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
