// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockaudit

import (
	context "context"

	audit "github.com/kadekutama/go-template/internal/infrastructure/audit"

	mock "github.com/stretchr/testify/mock"
)

// MockLokiExporter is an autogenerated mock type for the LokiExporter type
type MockLokiExporter struct {
	mock.Mock
}

type MockLokiExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLokiExporter) EXPECT() *MockLokiExporter_Expecter {
	return &MockLokiExporter_Expecter{mock: &_m.Mock}
}

// ExportAudit provides a mock function with given fields: ctx, entry
func (_m *MockLokiExporter) ExportAudit(ctx context.Context, entry audit.StoredEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for ExportAudit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, audit.StoredEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLokiExporter_ExportAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportAudit'
type MockLokiExporter_ExportAudit_Call struct {
	*mock.Call
}

// ExportAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - entry audit.StoredEntry
func (_e *MockLokiExporter_Expecter) ExportAudit(ctx interface{}, entry interface{}) *MockLokiExporter_ExportAudit_Call {
	return &MockLokiExporter_ExportAudit_Call{Call: _e.mock.On("ExportAudit", ctx, entry)}
}

func (_c *MockLokiExporter_ExportAudit_Call) Run(run func(ctx context.Context, entry audit.StoredEntry)) *MockLokiExporter_ExportAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(audit.StoredEntry))
	})
	return _c
}

func (_c *MockLokiExporter_ExportAudit_Call) Return(_a0 error) *MockLokiExporter_ExportAudit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLokiExporter_ExportAudit_Call) RunAndReturn(run func(context.Context, audit.StoredEntry) error) *MockLokiExporter_ExportAudit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLokiExporter creates a new instance of MockLokiExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLokiExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLokiExporter {
	mock := &MockLokiExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
