// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockseed

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	seed "github.com/kadekutama/go-template/internal/infrastructure/database/seed"
)

// MockLedgerStore is an autogenerated mock type for the LedgerStore type
type MockLedgerStore struct {
	mock.Mock
}

type MockLedgerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerStore) EXPECT() *MockLedgerStore_Expecter {
	return &MockLedgerStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ledger
func (_m *MockLedgerStore) Create(ctx context.Context, ledger seed.LedgerSeed) error {
	ret := _m.Called(ctx, ledger)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, seed.LedgerSeed) error); ok {
		r0 = rf(ctx, ledger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLedgerStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ledger seed.LedgerSeed
func (_e *MockLedgerStore_Expecter) Create(ctx interface{}, ledger interface{}) *MockLedgerStore_Create_Call {
	return &MockLedgerStore_Create_Call{Call: _e.mock.On("Create", ctx, ledger)}
}

func (_c *MockLedgerStore_Create_Call) Run(run func(ctx context.Context, ledger seed.LedgerSeed)) *MockLedgerStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(seed.LedgerSeed))
	})
	return _c
}

func (_c *MockLedgerStore_Create_Call) Return(_a0 error) *MockLedgerStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerStore_Create_Call) RunAndReturn(run func(context.Context, seed.LedgerSeed) error) *MockLedgerStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *MockLedgerStore) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockLedgerStore_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLedgerStore_Expecter) Exists(ctx interface{}, id interface{}) *MockLedgerStore_Exists_Call {
	return &MockLedgerStore_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockLedgerStore_Exists_Call) Run(run func(ctx context.Context, id string)) *MockLedgerStore_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLedgerStore_Exists_Call) Return(_a0 bool, _a1 error) *MockLedgerStore_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerStore_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockLedgerStore_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerStore creates a new instance of MockLedgerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerStore {
	mock := &MockLedgerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
