// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockseed

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	seed "github.com/kadekutama/go-template/internal/infrastructure/database/seed"
)

// MockPostingStore is an autogenerated mock type for the PostingStore type
type MockPostingStore struct {
	mock.Mock
}

type MockPostingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostingStore) EXPECT() *MockPostingStore_Expecter {
	return &MockPostingStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, posting
func (_m *MockPostingStore) Create(ctx context.Context, posting seed.PostingSeed) error {
	ret := _m.Called(ctx, posting)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, seed.PostingSeed) error); ok {
		r0 = rf(ctx, posting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostingStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostingStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - posting seed.PostingSeed
func (_e *MockPostingStore_Expecter) Create(ctx interface{}, posting interface{}) *MockPostingStore_Create_Call {
	return &MockPostingStore_Create_Call{Call: _e.mock.On("Create", ctx, posting)}
}

func (_c *MockPostingStore_Create_Call) Run(run func(ctx context.Context, posting seed.PostingSeed)) *MockPostingStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(seed.PostingSeed))
	})
	return _c
}

func (_c *MockPostingStore_Create_Call) Return(_a0 error) *MockPostingStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostingStore_Create_Call) RunAndReturn(run func(context.Context, seed.PostingSeed) error) *MockPostingStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *MockPostingStore) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostingStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockPostingStore_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPostingStore_Expecter) Exists(ctx interface{}, id interface{}) *MockPostingStore_Exists_Call {
	return &MockPostingStore_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockPostingStore_Exists_Call) Run(run func(ctx context.Context, id string)) *MockPostingStore_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPostingStore_Exists_Call) Return(_a0 bool, _a1 error) *MockPostingStore_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostingStore_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockPostingStore_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostingStore creates a new instance of MockPostingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostingStore {
	mock := &MockPostingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
