// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockvalkey

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockScriptRunner is an autogenerated mock type for the ScriptRunner type
type MockScriptRunner struct {
	mock.Mock
}

type MockScriptRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScriptRunner) EXPECT() *MockScriptRunner_Expecter {
	return &MockScriptRunner_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function with given fields: ctx, script, keys, args
func (_m *MockScriptRunner) Eval(ctx context.Context, script string, keys []string, args ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, script, keys)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) (interface{}, error)); ok {
		return rf(ctx, script, keys, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) interface{}); ok {
		r0 = rf(ctx, script, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, ...interface{}) error); ok {
		r1 = rf(ctx, script, keys, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScriptRunner_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type MockScriptRunner_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
//   - keys []string
//   - args ...interface{}
func (_e *MockScriptRunner_Expecter) Eval(ctx interface{}, script interface{}, keys interface{}, args ...interface{}) *MockScriptRunner_Eval_Call {
	return &MockScriptRunner_Eval_Call{Call: _e.mock.On("Eval",
		append([]interface{}{ctx, script, keys}, args...)...)}
}

func (_c *MockScriptRunner_Eval_Call) Run(run func(ctx context.Context, script string, keys []string, args ...interface{})) *MockScriptRunner_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]string), variadicArgs...)
	})
	return _c
}

func (_c *MockScriptRunner_Eval_Call) Return(_a0 interface{}, _a1 error) *MockScriptRunner_Eval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScriptRunner_Eval_Call) RunAndReturn(run func(context.Context, string, []string, ...interface{}) (interface{}, error)) *MockScriptRunner_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScriptRunner creates a new instance of MockScriptRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScriptRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScriptRunner {
	mock := &MockScriptRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
