// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockAccountCommandUseCases is an autogenerated mock type for the AccountCommandUseCases type
type MockAccountCommandUseCases struct {
	mock.Mock
}

type MockAccountCommandUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountCommandUseCases) EXPECT() *MockAccountCommandUseCases_Expecter {
	return &MockAccountCommandUseCases_Expecter{mock: &_m.Mock}
}

// CloseAccount provides a mock function with given fields: ctx, req
func (_m *MockAccountCommandUseCases) CloseAccount(ctx context.Context, req port.AccountLifecycleRequest) (port.AccountResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CloseAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) port.AccountResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.AccountLifecycleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountCommandUseCases_CloseAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAccount'
type MockAccountCommandUseCases_CloseAccount_Call struct {
	*mock.Call
}

// CloseAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.AccountLifecycleRequest
func (_e *MockAccountCommandUseCases_Expecter) CloseAccount(ctx interface{}, req interface{}) *MockAccountCommandUseCases_CloseAccount_Call {
	return &MockAccountCommandUseCases_CloseAccount_Call{Call: _e.mock.On("CloseAccount", ctx, req)}
}

func (_c *MockAccountCommandUseCases_CloseAccount_Call) Run(run func(ctx context.Context, req port.AccountLifecycleRequest)) *MockAccountCommandUseCases_CloseAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.AccountLifecycleRequest))
	})
	return _c
}

func (_c *MockAccountCommandUseCases_CloseAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountCommandUseCases_CloseAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountCommandUseCases_CloseAccount_Call) RunAndReturn(run func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)) *MockAccountCommandUseCases_CloseAccount_Call {
	_c.Call.Return(run)
	return _c
}

// FreezeAccount provides a mock function with given fields: ctx, req
func (_m *MockAccountCommandUseCases) FreezeAccount(ctx context.Context, req port.AccountLifecycleRequest) (port.AccountResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FreezeAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) port.AccountResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.AccountLifecycleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountCommandUseCases_FreezeAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FreezeAccount'
type MockAccountCommandUseCases_FreezeAccount_Call struct {
	*mock.Call
}

// FreezeAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.AccountLifecycleRequest
func (_e *MockAccountCommandUseCases_Expecter) FreezeAccount(ctx interface{}, req interface{}) *MockAccountCommandUseCases_FreezeAccount_Call {
	return &MockAccountCommandUseCases_FreezeAccount_Call{Call: _e.mock.On("FreezeAccount", ctx, req)}
}

func (_c *MockAccountCommandUseCases_FreezeAccount_Call) Run(run func(ctx context.Context, req port.AccountLifecycleRequest)) *MockAccountCommandUseCases_FreezeAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.AccountLifecycleRequest))
	})
	return _c
}

func (_c *MockAccountCommandUseCases_FreezeAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountCommandUseCases_FreezeAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountCommandUseCases_FreezeAccount_Call) RunAndReturn(run func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)) *MockAccountCommandUseCases_FreezeAccount_Call {
	_c.Call.Return(run)
	return _c
}

// OpenAccount provides a mock function with given fields: ctx, req
func (_m *MockAccountCommandUseCases) OpenAccount(ctx context.Context, req port.OpenAccountRequest) (port.AccountResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for OpenAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.OpenAccountRequest) (port.AccountResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.OpenAccountRequest) port.AccountResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.OpenAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountCommandUseCases_OpenAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAccount'
type MockAccountCommandUseCases_OpenAccount_Call struct {
	*mock.Call
}

// OpenAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.OpenAccountRequest
func (_e *MockAccountCommandUseCases_Expecter) OpenAccount(ctx interface{}, req interface{}) *MockAccountCommandUseCases_OpenAccount_Call {
	return &MockAccountCommandUseCases_OpenAccount_Call{Call: _e.mock.On("OpenAccount", ctx, req)}
}

func (_c *MockAccountCommandUseCases_OpenAccount_Call) Run(run func(ctx context.Context, req port.OpenAccountRequest)) *MockAccountCommandUseCases_OpenAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.OpenAccountRequest))
	})
	return _c
}

func (_c *MockAccountCommandUseCases_OpenAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountCommandUseCases_OpenAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountCommandUseCases_OpenAccount_Call) RunAndReturn(run func(context.Context, port.OpenAccountRequest) (port.AccountResult, error)) *MockAccountCommandUseCases_OpenAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UnfreezeAccount provides a mock function with given fields: ctx, req
func (_m *MockAccountCommandUseCases) UnfreezeAccount(ctx context.Context, req port.AccountLifecycleRequest) (port.AccountResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnfreezeAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountLifecycleRequest) port.AccountResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.AccountLifecycleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountCommandUseCases_UnfreezeAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnfreezeAccount'
type MockAccountCommandUseCases_UnfreezeAccount_Call struct {
	*mock.Call
}

// UnfreezeAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.AccountLifecycleRequest
func (_e *MockAccountCommandUseCases_Expecter) UnfreezeAccount(ctx interface{}, req interface{}) *MockAccountCommandUseCases_UnfreezeAccount_Call {
	return &MockAccountCommandUseCases_UnfreezeAccount_Call{Call: _e.mock.On("UnfreezeAccount", ctx, req)}
}

func (_c *MockAccountCommandUseCases_UnfreezeAccount_Call) Run(run func(ctx context.Context, req port.AccountLifecycleRequest)) *MockAccountCommandUseCases_UnfreezeAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.AccountLifecycleRequest))
	})
	return _c
}

func (_c *MockAccountCommandUseCases_UnfreezeAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountCommandUseCases_UnfreezeAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountCommandUseCases_UnfreezeAccount_Call) RunAndReturn(run func(context.Context, port.AccountLifecycleRequest) (port.AccountResult, error)) *MockAccountCommandUseCases_UnfreezeAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function with given fields: ctx, req
func (_m *MockAccountCommandUseCases) UpdateAccount(ctx context.Context, req port.UpdateAccountRequest) (port.AccountResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.UpdateAccountRequest) (port.AccountResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.UpdateAccountRequest) port.AccountResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.UpdateAccountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountCommandUseCases_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockAccountCommandUseCases_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.UpdateAccountRequest
func (_e *MockAccountCommandUseCases_Expecter) UpdateAccount(ctx interface{}, req interface{}) *MockAccountCommandUseCases_UpdateAccount_Call {
	return &MockAccountCommandUseCases_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, req)}
}

func (_c *MockAccountCommandUseCases_UpdateAccount_Call) Run(run func(ctx context.Context, req port.UpdateAccountRequest)) *MockAccountCommandUseCases_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.UpdateAccountRequest))
	})
	return _c
}

func (_c *MockAccountCommandUseCases_UpdateAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountCommandUseCases_UpdateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountCommandUseCases_UpdateAccount_Call) RunAndReturn(run func(context.Context, port.UpdateAccountRequest) (port.AccountResult, error)) *MockAccountCommandUseCases_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountCommandUseCases creates a new instance of MockAccountCommandUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountCommandUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountCommandUseCases {
	mock := &MockAccountCommandUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
