// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockAccountQueryUseCases is an autogenerated mock type for the AccountQueryUseCases type
type MockAccountQueryUseCases struct {
	mock.Mock
}

type MockAccountQueryUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountQueryUseCases) EXPECT() *MockAccountQueryUseCases_Expecter {
	return &MockAccountQueryUseCases_Expecter{mock: &_m.Mock}
}

// GetAccount provides a mock function with given fields: ctx, query
func (_m *MockAccountQueryUseCases) GetAccount(ctx context.Context, query port.AccountQuery) (port.AccountResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 port.AccountResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountQuery) (port.AccountResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountQuery) port.AccountResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.AccountResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.AccountQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountQueryUseCases_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountQueryUseCases_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.AccountQuery
func (_e *MockAccountQueryUseCases_Expecter) GetAccount(ctx interface{}, query interface{}) *MockAccountQueryUseCases_GetAccount_Call {
	return &MockAccountQueryUseCases_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, query)}
}

func (_c *MockAccountQueryUseCases_GetAccount_Call) Run(run func(ctx context.Context, query port.AccountQuery)) *MockAccountQueryUseCases_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.AccountQuery))
	})
	return _c
}

func (_c *MockAccountQueryUseCases_GetAccount_Call) Return(_a0 port.AccountResult, _a1 error) *MockAccountQueryUseCases_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountQueryUseCases_GetAccount_Call) RunAndReturn(run func(context.Context, port.AccountQuery) (port.AccountResult, error)) *MockAccountQueryUseCases_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx, query
func (_m *MockAccountQueryUseCases) ListAccounts(ctx context.Context, query port.AccountListQuery) (port.AccountPage, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 port.AccountPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountListQuery) (port.AccountPage, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.AccountListQuery) port.AccountPage); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.AccountPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.AccountListQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountQueryUseCases_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockAccountQueryUseCases_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.AccountListQuery
func (_e *MockAccountQueryUseCases_Expecter) ListAccounts(ctx interface{}, query interface{}) *MockAccountQueryUseCases_ListAccounts_Call {
	return &MockAccountQueryUseCases_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, query)}
}

func (_c *MockAccountQueryUseCases_ListAccounts_Call) Run(run func(ctx context.Context, query port.AccountListQuery)) *MockAccountQueryUseCases_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.AccountListQuery))
	})
	return _c
}

func (_c *MockAccountQueryUseCases_ListAccounts_Call) Return(_a0 port.AccountPage, _a1 error) *MockAccountQueryUseCases_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountQueryUseCases_ListAccounts_Call) RunAndReturn(run func(context.Context, port.AccountListQuery) (port.AccountPage, error)) *MockAccountQueryUseCases_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountQueryUseCases creates a new instance of MockAccountQueryUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountQueryUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountQueryUseCases {
	mock := &MockAccountQueryUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
