// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockComplianceQueryUseCases is an autogenerated mock type for the ComplianceQueryUseCases type
type MockComplianceQueryUseCases struct {
	mock.Mock
}

type MockComplianceQueryUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplianceQueryUseCases) EXPECT() *MockComplianceQueryUseCases_Expecter {
	return &MockComplianceQueryUseCases_Expecter{mock: &_m.Mock}
}

// ReportStatus provides a mock function with given fields: ctx, tenant, reportID
func (_m *MockComplianceQueryUseCases) ReportStatus(ctx context.Context, tenant valueobject.TenantID, reportID string) (port.ReportResult, error) {
	ret := _m.Called(ctx, tenant, reportID)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 port.ReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.ReportResult, error)); ok {
		return rf(ctx, tenant, reportID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.ReportResult); ok {
		r0 = rf(ctx, tenant, reportID)
	} else {
		r0 = ret.Get(0).(port.ReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, reportID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceQueryUseCases_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockComplianceQueryUseCases_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - reportID string
func (_e *MockComplianceQueryUseCases_Expecter) ReportStatus(ctx interface{}, tenant interface{}, reportID interface{}) *MockComplianceQueryUseCases_ReportStatus_Call {
	return &MockComplianceQueryUseCases_ReportStatus_Call{Call: _e.mock.On("ReportStatus", ctx, tenant, reportID)}
}

func (_c *MockComplianceQueryUseCases_ReportStatus_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, reportID string)) *MockComplianceQueryUseCases_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockComplianceQueryUseCases_ReportStatus_Call) Return(_a0 port.ReportResult, _a1 error) *MockComplianceQueryUseCases_ReportStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceQueryUseCases_ReportStatus_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.ReportResult, error)) *MockComplianceQueryUseCases_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComplianceQueryUseCases creates a new instance of MockComplianceQueryUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplianceQueryUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplianceQueryUseCases {
	mock := &MockComplianceQueryUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
