// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockComplianceCommandUseCases is an autogenerated mock type for the ComplianceCommandUseCases type
type MockComplianceCommandUseCases struct {
	mock.Mock
}

type MockComplianceCommandUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplianceCommandUseCases) EXPECT() *MockComplianceCommandUseCases_Expecter {
	return &MockComplianceCommandUseCases_Expecter{mock: &_m.Mock}
}

// AcknowledgeBreak provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) AcknowledgeBreak(ctx context.Context, req port.BreakResolutionRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeBreak")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BreakResolutionRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_AcknowledgeBreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeBreak'
type MockComplianceCommandUseCases_AcknowledgeBreak_Call struct {
	*mock.Call
}

// AcknowledgeBreak is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.BreakResolutionRequest
func (_e *MockComplianceCommandUseCases_Expecter) AcknowledgeBreak(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_AcknowledgeBreak_Call {
	return &MockComplianceCommandUseCases_AcknowledgeBreak_Call{Call: _e.mock.On("AcknowledgeBreak", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_AcknowledgeBreak_Call) Run(run func(ctx context.Context, req port.BreakResolutionRequest)) *MockComplianceCommandUseCases_AcknowledgeBreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BreakResolutionRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_AcknowledgeBreak_Call) Return(_a0 error) *MockComplianceCommandUseCases_AcknowledgeBreak_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_AcknowledgeBreak_Call) RunAndReturn(run func(context.Context, port.BreakResolutionRequest) error) *MockComplianceCommandUseCases_AcknowledgeBreak_Call {
	_c.Call.Return(run)
	return _c
}

// ClosePeriod provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) ClosePeriod(ctx context.Context, req port.PeriodRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ClosePeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PeriodRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_ClosePeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePeriod'
type MockComplianceCommandUseCases_ClosePeriod_Call struct {
	*mock.Call
}

// ClosePeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PeriodRequest
func (_e *MockComplianceCommandUseCases_Expecter) ClosePeriod(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_ClosePeriod_Call {
	return &MockComplianceCommandUseCases_ClosePeriod_Call{Call: _e.mock.On("ClosePeriod", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_ClosePeriod_Call) Run(run func(ctx context.Context, req port.PeriodRequest)) *MockComplianceCommandUseCases_ClosePeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PeriodRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_ClosePeriod_Call) Return(_a0 error) *MockComplianceCommandUseCases_ClosePeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_ClosePeriod_Call) RunAndReturn(run func(context.Context, port.PeriodRequest) error) *MockComplianceCommandUseCases_ClosePeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ExportRegulatoryReport provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) ExportRegulatoryReport(ctx context.Context, req port.RegulatoryExportRequest) (port.ReportResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ExportRegulatoryReport")
	}

	var r0 port.ReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RegulatoryExportRequest) (port.ReportResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RegulatoryExportRequest) port.ReportResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.ReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RegulatoryExportRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceCommandUseCases_ExportRegulatoryReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportRegulatoryReport'
type MockComplianceCommandUseCases_ExportRegulatoryReport_Call struct {
	*mock.Call
}

// ExportRegulatoryReport is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.RegulatoryExportRequest
func (_e *MockComplianceCommandUseCases_Expecter) ExportRegulatoryReport(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_ExportRegulatoryReport_Call {
	return &MockComplianceCommandUseCases_ExportRegulatoryReport_Call{Call: _e.mock.On("ExportRegulatoryReport", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_ExportRegulatoryReport_Call) Run(run func(ctx context.Context, req port.RegulatoryExportRequest)) *MockComplianceCommandUseCases_ExportRegulatoryReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.RegulatoryExportRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_ExportRegulatoryReport_Call) Return(_a0 port.ReportResult, _a1 error) *MockComplianceCommandUseCases_ExportRegulatoryReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceCommandUseCases_ExportRegulatoryReport_Call) RunAndReturn(run func(context.Context, port.RegulatoryExportRequest) (port.ReportResult, error)) *MockComplianceCommandUseCases_ExportRegulatoryReport_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateReport provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) GenerateReport(ctx context.Context, req port.ReportRequest) (port.ReportResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReport")
	}

	var r0 port.ReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ReportRequest) (port.ReportResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ReportRequest) port.ReportResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.ReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ReportRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceCommandUseCases_GenerateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReport'
type MockComplianceCommandUseCases_GenerateReport_Call struct {
	*mock.Call
}

// GenerateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ReportRequest
func (_e *MockComplianceCommandUseCases_Expecter) GenerateReport(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_GenerateReport_Call {
	return &MockComplianceCommandUseCases_GenerateReport_Call{Call: _e.mock.On("GenerateReport", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_GenerateReport_Call) Run(run func(ctx context.Context, req port.ReportRequest)) *MockComplianceCommandUseCases_GenerateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ReportRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_GenerateReport_Call) Return(_a0 port.ReportResult, _a1 error) *MockComplianceCommandUseCases_GenerateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceCommandUseCases_GenerateReport_Call) RunAndReturn(run func(context.Context, port.ReportRequest) (port.ReportResult, error)) *MockComplianceCommandUseCases_GenerateReport_Call {
	_c.Call.Return(run)
	return _c
}

// OpenPeriod provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) OpenPeriod(ctx context.Context, req port.PeriodRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for OpenPeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PeriodRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_OpenPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenPeriod'
type MockComplianceCommandUseCases_OpenPeriod_Call struct {
	*mock.Call
}

// OpenPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PeriodRequest
func (_e *MockComplianceCommandUseCases_Expecter) OpenPeriod(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_OpenPeriod_Call {
	return &MockComplianceCommandUseCases_OpenPeriod_Call{Call: _e.mock.On("OpenPeriod", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_OpenPeriod_Call) Run(run func(ctx context.Context, req port.PeriodRequest)) *MockComplianceCommandUseCases_OpenPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PeriodRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_OpenPeriod_Call) Return(_a0 error) *MockComplianceCommandUseCases_OpenPeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_OpenPeriod_Call) RunAndReturn(run func(context.Context, port.PeriodRequest) error) *MockComplianceCommandUseCases_OpenPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// RecordScreeningDecision provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) RecordScreeningDecision(ctx context.Context, req port.ScreeningRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordScreeningDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ScreeningRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_RecordScreeningDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordScreeningDecision'
type MockComplianceCommandUseCases_RecordScreeningDecision_Call struct {
	*mock.Call
}

// RecordScreeningDecision is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ScreeningRequest
func (_e *MockComplianceCommandUseCases_Expecter) RecordScreeningDecision(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_RecordScreeningDecision_Call {
	return &MockComplianceCommandUseCases_RecordScreeningDecision_Call{Call: _e.mock.On("RecordScreeningDecision", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_RecordScreeningDecision_Call) Run(run func(ctx context.Context, req port.ScreeningRequest)) *MockComplianceCommandUseCases_RecordScreeningDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ScreeningRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_RecordScreeningDecision_Call) Return(_a0 error) *MockComplianceCommandUseCases_RecordScreeningDecision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_RecordScreeningDecision_Call) RunAndReturn(run func(context.Context, port.ScreeningRequest) error) *MockComplianceCommandUseCases_RecordScreeningDecision_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenPeriod provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) ReopenPeriod(ctx context.Context, req port.PeriodRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReopenPeriod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PeriodRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_ReopenPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenPeriod'
type MockComplianceCommandUseCases_ReopenPeriod_Call struct {
	*mock.Call
}

// ReopenPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PeriodRequest
func (_e *MockComplianceCommandUseCases_Expecter) ReopenPeriod(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_ReopenPeriod_Call {
	return &MockComplianceCommandUseCases_ReopenPeriod_Call{Call: _e.mock.On("ReopenPeriod", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_ReopenPeriod_Call) Run(run func(ctx context.Context, req port.PeriodRequest)) *MockComplianceCommandUseCases_ReopenPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PeriodRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_ReopenPeriod_Call) Return(_a0 error) *MockComplianceCommandUseCases_ReopenPeriod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_ReopenPeriod_Call) RunAndReturn(run func(context.Context, port.PeriodRequest) error) *MockComplianceCommandUseCases_ReopenPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveBreak provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) ResolveBreak(ctx context.Context, req port.BreakResolutionRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResolveBreak")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BreakResolutionRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComplianceCommandUseCases_ResolveBreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveBreak'
type MockComplianceCommandUseCases_ResolveBreak_Call struct {
	*mock.Call
}

// ResolveBreak is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.BreakResolutionRequest
func (_e *MockComplianceCommandUseCases_Expecter) ResolveBreak(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_ResolveBreak_Call {
	return &MockComplianceCommandUseCases_ResolveBreak_Call{Call: _e.mock.On("ResolveBreak", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_ResolveBreak_Call) Run(run func(ctx context.Context, req port.BreakResolutionRequest)) *MockComplianceCommandUseCases_ResolveBreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BreakResolutionRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_ResolveBreak_Call) Return(_a0 error) *MockComplianceCommandUseCases_ResolveBreak_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComplianceCommandUseCases_ResolveBreak_Call) RunAndReturn(run func(context.Context, port.BreakResolutionRequest) error) *MockComplianceCommandUseCases_ResolveBreak_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerReconRun provides a mock function with given fields: ctx, req
func (_m *MockComplianceCommandUseCases) TriggerReconRun(ctx context.Context, req port.ReconRunRequest) (port.ReconRunResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for TriggerReconRun")
	}

	var r0 port.ReconRunResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ReconRunRequest) (port.ReconRunResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ReconRunRequest) port.ReconRunResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.ReconRunResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ReconRunRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceCommandUseCases_TriggerReconRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerReconRun'
type MockComplianceCommandUseCases_TriggerReconRun_Call struct {
	*mock.Call
}

// TriggerReconRun is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ReconRunRequest
func (_e *MockComplianceCommandUseCases_Expecter) TriggerReconRun(ctx interface{}, req interface{}) *MockComplianceCommandUseCases_TriggerReconRun_Call {
	return &MockComplianceCommandUseCases_TriggerReconRun_Call{Call: _e.mock.On("TriggerReconRun", ctx, req)}
}

func (_c *MockComplianceCommandUseCases_TriggerReconRun_Call) Run(run func(ctx context.Context, req port.ReconRunRequest)) *MockComplianceCommandUseCases_TriggerReconRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ReconRunRequest))
	})
	return _c
}

func (_c *MockComplianceCommandUseCases_TriggerReconRun_Call) Return(_a0 port.ReconRunResult, _a1 error) *MockComplianceCommandUseCases_TriggerReconRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceCommandUseCases_TriggerReconRun_Call) RunAndReturn(run func(context.Context, port.ReconRunRequest) (port.ReconRunResult, error)) *MockComplianceCommandUseCases_TriggerReconRun_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComplianceCommandUseCases creates a new instance of MockComplianceCommandUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplianceCommandUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplianceCommandUseCases {
	mock := &MockComplianceCommandUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
