// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockDisputeQueryUseCases is an autogenerated mock type for the DisputeQueryUseCases type
type MockDisputeQueryUseCases struct {
	mock.Mock
}

type MockDisputeQueryUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisputeQueryUseCases) EXPECT() *MockDisputeQueryUseCases_Expecter {
	return &MockDisputeQueryUseCases_Expecter{mock: &_m.Mock}
}

// GetDispute provides a mock function with given fields: ctx, query
func (_m *MockDisputeQueryUseCases) GetDispute(ctx context.Context, query port.DisputeQuery) (port.DisputeResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetDispute")
	}

	var r0 port.DisputeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.DisputeQuery) (port.DisputeResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.DisputeQuery) port.DisputeResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.DisputeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.DisputeQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeQueryUseCases_GetDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDispute'
type MockDisputeQueryUseCases_GetDispute_Call struct {
	*mock.Call
}

// GetDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.DisputeQuery
func (_e *MockDisputeQueryUseCases_Expecter) GetDispute(ctx interface{}, query interface{}) *MockDisputeQueryUseCases_GetDispute_Call {
	return &MockDisputeQueryUseCases_GetDispute_Call{Call: _e.mock.On("GetDispute", ctx, query)}
}

func (_c *MockDisputeQueryUseCases_GetDispute_Call) Run(run func(ctx context.Context, query port.DisputeQuery)) *MockDisputeQueryUseCases_GetDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.DisputeQuery))
	})
	return _c
}

func (_c *MockDisputeQueryUseCases_GetDispute_Call) Return(_a0 port.DisputeResult, _a1 error) *MockDisputeQueryUseCases_GetDispute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeQueryUseCases_GetDispute_Call) RunAndReturn(run func(context.Context, port.DisputeQuery) (port.DisputeResult, error)) *MockDisputeQueryUseCases_GetDispute_Call {
	_c.Call.Return(run)
	return _c
}

// ListDisputes provides a mock function with given fields: ctx, filter
func (_m *MockDisputeQueryUseCases) ListDisputes(ctx context.Context, filter port.DisputeListFilter) (port.DisputePage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListDisputes")
	}

	var r0 port.DisputePage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.DisputeListFilter) (port.DisputePage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.DisputeListFilter) port.DisputePage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(port.DisputePage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.DisputeListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeQueryUseCases_ListDisputes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDisputes'
type MockDisputeQueryUseCases_ListDisputes_Call struct {
	*mock.Call
}

// ListDisputes is a helper method to define mock.On call
//   - ctx context.Context
//   - filter port.DisputeListFilter
func (_e *MockDisputeQueryUseCases_Expecter) ListDisputes(ctx interface{}, filter interface{}) *MockDisputeQueryUseCases_ListDisputes_Call {
	return &MockDisputeQueryUseCases_ListDisputes_Call{Call: _e.mock.On("ListDisputes", ctx, filter)}
}

func (_c *MockDisputeQueryUseCases_ListDisputes_Call) Run(run func(ctx context.Context, filter port.DisputeListFilter)) *MockDisputeQueryUseCases_ListDisputes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.DisputeListFilter))
	})
	return _c
}

func (_c *MockDisputeQueryUseCases_ListDisputes_Call) Return(_a0 port.DisputePage, _a1 error) *MockDisputeQueryUseCases_ListDisputes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeQueryUseCases_ListDisputes_Call) RunAndReturn(run func(context.Context, port.DisputeListFilter) (port.DisputePage, error)) *MockDisputeQueryUseCases_ListDisputes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDisputeQueryUseCases creates a new instance of MockDisputeQueryUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisputeQueryUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisputeQueryUseCases {
	mock := &MockDisputeQueryUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
