// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockDisputeCommandUseCases is an autogenerated mock type for the DisputeCommandUseCases type
type MockDisputeCommandUseCases struct {
	mock.Mock
}

type MockDisputeCommandUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisputeCommandUseCases) EXPECT() *MockDisputeCommandUseCases_Expecter {
	return &MockDisputeCommandUseCases_Expecter{mock: &_m.Mock}
}

// CloseDispute provides a mock function with given fields: ctx, cmd
func (_m *MockDisputeCommandUseCases) CloseDispute(ctx context.Context, cmd port.CloseDisputeCommand) (port.DisputeResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CloseDispute")
	}

	var r0 port.DisputeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.CloseDisputeCommand) (port.DisputeResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.CloseDisputeCommand) port.DisputeResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(port.DisputeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.CloseDisputeCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeCommandUseCases_CloseDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDispute'
type MockDisputeCommandUseCases_CloseDispute_Call struct {
	*mock.Call
}

// CloseDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd port.CloseDisputeCommand
func (_e *MockDisputeCommandUseCases_Expecter) CloseDispute(ctx interface{}, cmd interface{}) *MockDisputeCommandUseCases_CloseDispute_Call {
	return &MockDisputeCommandUseCases_CloseDispute_Call{Call: _e.mock.On("CloseDispute", ctx, cmd)}
}

func (_c *MockDisputeCommandUseCases_CloseDispute_Call) Run(run func(ctx context.Context, cmd port.CloseDisputeCommand)) *MockDisputeCommandUseCases_CloseDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.CloseDisputeCommand))
	})
	return _c
}

func (_c *MockDisputeCommandUseCases_CloseDispute_Call) Return(_a0 port.DisputeResult, _a1 error) *MockDisputeCommandUseCases_CloseDispute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeCommandUseCases_CloseDispute_Call) RunAndReturn(run func(context.Context, port.CloseDisputeCommand) (port.DisputeResult, error)) *MockDisputeCommandUseCases_CloseDispute_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDispute provides a mock function with given fields: ctx, cmd
func (_m *MockDisputeCommandUseCases) OpenDispute(ctx context.Context, cmd port.OpenDisputeCommand) (port.DisputeResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for OpenDispute")
	}

	var r0 port.DisputeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.OpenDisputeCommand) (port.DisputeResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.OpenDisputeCommand) port.DisputeResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(port.DisputeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.OpenDisputeCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeCommandUseCases_OpenDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDispute'
type MockDisputeCommandUseCases_OpenDispute_Call struct {
	*mock.Call
}

// OpenDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd port.OpenDisputeCommand
func (_e *MockDisputeCommandUseCases_Expecter) OpenDispute(ctx interface{}, cmd interface{}) *MockDisputeCommandUseCases_OpenDispute_Call {
	return &MockDisputeCommandUseCases_OpenDispute_Call{Call: _e.mock.On("OpenDispute", ctx, cmd)}
}

func (_c *MockDisputeCommandUseCases_OpenDispute_Call) Run(run func(ctx context.Context, cmd port.OpenDisputeCommand)) *MockDisputeCommandUseCases_OpenDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.OpenDisputeCommand))
	})
	return _c
}

func (_c *MockDisputeCommandUseCases_OpenDispute_Call) Return(_a0 port.DisputeResult, _a1 error) *MockDisputeCommandUseCases_OpenDispute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeCommandUseCases_OpenDispute_Call) RunAndReturn(run func(context.Context, port.OpenDisputeCommand) (port.DisputeResult, error)) *MockDisputeCommandUseCases_OpenDispute_Call {
	_c.Call.Return(run)
	return _c
}

// RepresentDispute provides a mock function with given fields: ctx, cmd
func (_m *MockDisputeCommandUseCases) RepresentDispute(ctx context.Context, cmd port.RepresentCommand) (port.DisputeResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RepresentDispute")
	}

	var r0 port.DisputeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RepresentCommand) (port.DisputeResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RepresentCommand) port.DisputeResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(port.DisputeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RepresentCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeCommandUseCases_RepresentDispute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepresentDispute'
type MockDisputeCommandUseCases_RepresentDispute_Call struct {
	*mock.Call
}

// RepresentDispute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd port.RepresentCommand
func (_e *MockDisputeCommandUseCases_Expecter) RepresentDispute(ctx interface{}, cmd interface{}) *MockDisputeCommandUseCases_RepresentDispute_Call {
	return &MockDisputeCommandUseCases_RepresentDispute_Call{Call: _e.mock.On("RepresentDispute", ctx, cmd)}
}

func (_c *MockDisputeCommandUseCases_RepresentDispute_Call) Run(run func(ctx context.Context, cmd port.RepresentCommand)) *MockDisputeCommandUseCases_RepresentDispute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.RepresentCommand))
	})
	return _c
}

func (_c *MockDisputeCommandUseCases_RepresentDispute_Call) Return(_a0 port.DisputeResult, _a1 error) *MockDisputeCommandUseCases_RepresentDispute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeCommandUseCases_RepresentDispute_Call) RunAndReturn(run func(context.Context, port.RepresentCommand) (port.DisputeResult, error)) *MockDisputeCommandUseCases_RepresentDispute_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitEvidence provides a mock function with given fields: ctx, cmd
func (_m *MockDisputeCommandUseCases) SubmitEvidence(ctx context.Context, cmd port.EvidenceCommand) (port.DisputeResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEvidence")
	}

	var r0 port.DisputeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.EvidenceCommand) (port.DisputeResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.EvidenceCommand) port.DisputeResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(port.DisputeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.EvidenceCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDisputeCommandUseCases_SubmitEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitEvidence'
type MockDisputeCommandUseCases_SubmitEvidence_Call struct {
	*mock.Call
}

// SubmitEvidence is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd port.EvidenceCommand
func (_e *MockDisputeCommandUseCases_Expecter) SubmitEvidence(ctx interface{}, cmd interface{}) *MockDisputeCommandUseCases_SubmitEvidence_Call {
	return &MockDisputeCommandUseCases_SubmitEvidence_Call{Call: _e.mock.On("SubmitEvidence", ctx, cmd)}
}

func (_c *MockDisputeCommandUseCases_SubmitEvidence_Call) Run(run func(ctx context.Context, cmd port.EvidenceCommand)) *MockDisputeCommandUseCases_SubmitEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.EvidenceCommand))
	})
	return _c
}

func (_c *MockDisputeCommandUseCases_SubmitEvidence_Call) Return(_a0 port.DisputeResult, _a1 error) *MockDisputeCommandUseCases_SubmitEvidence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDisputeCommandUseCases_SubmitEvidence_Call) RunAndReturn(run func(context.Context, port.EvidenceCommand) (port.DisputeResult, error)) *MockDisputeCommandUseCases_SubmitEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDisputeCommandUseCases creates a new instance of MockDisputeCommandUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisputeCommandUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisputeCommandUseCases {
	mock := &MockDisputeCommandUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
