// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	time "time"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockDistributedLock is an autogenerated mock type for the DistributedLock type
type MockDistributedLock struct {
	mock.Mock
}

type MockDistributedLock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDistributedLock) EXPECT() *MockDistributedLock_Expecter {
	return &MockDistributedLock_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function with given fields: ctx, tenant, key, ttl
func (_m *MockDistributedLock) Acquire(ctx context.Context, tenant valueobject.TenantID, key string, ttl time.Duration) (port.Lock, error) {
	ret := _m.Called(ctx, tenant, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 port.Lock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) (port.Lock, error)); ok {
		return rf(ctx, tenant, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) port.Lock); ok {
		r0 = rf(ctx, tenant, key, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.Lock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, time.Duration) error); ok {
		r1 = rf(ctx, tenant, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDistributedLock_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockDistributedLock_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - key string
//   - ttl time.Duration
func (_e *MockDistributedLock_Expecter) Acquire(ctx interface{}, tenant interface{}, key interface{}, ttl interface{}) *MockDistributedLock_Acquire_Call {
	return &MockDistributedLock_Acquire_Call{Call: _e.mock.On("Acquire", ctx, tenant, key, ttl)}
}

func (_c *MockDistributedLock_Acquire_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, key string, ttl time.Duration)) *MockDistributedLock_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockDistributedLock_Acquire_Call) Return(_a0 port.Lock, _a1 error) *MockDistributedLock_Acquire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDistributedLock_Acquire_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, time.Duration) (port.Lock, error)) *MockDistributedLock_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDistributedLock creates a new instance of MockDistributedLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDistributedLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDistributedLock {
	mock := &MockDistributedLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
