// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockEnvelopeCrypto is an autogenerated mock type for the EnvelopeCrypto type
type MockEnvelopeCrypto struct {
	mock.Mock
}

type MockEnvelopeCrypto_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvelopeCrypto) EXPECT() *MockEnvelopeCrypto_Expecter {
	return &MockEnvelopeCrypto_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ctx, tenant, envelope
func (_m *MockEnvelopeCrypto) Decrypt(ctx context.Context, tenant valueobject.TenantID, envelope port.EncryptedEnvelope) ([]byte, error) {
	ret := _m.Called(ctx, tenant, envelope)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, port.EncryptedEnvelope) ([]byte, error)); ok {
		return rf(ctx, tenant, envelope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, port.EncryptedEnvelope) []byte); ok {
		r0 = rf(ctx, tenant, envelope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, port.EncryptedEnvelope) error); ok {
		r1 = rf(ctx, tenant, envelope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvelopeCrypto_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEnvelopeCrypto_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - envelope port.EncryptedEnvelope
func (_e *MockEnvelopeCrypto_Expecter) Decrypt(ctx interface{}, tenant interface{}, envelope interface{}) *MockEnvelopeCrypto_Decrypt_Call {
	return &MockEnvelopeCrypto_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, tenant, envelope)}
}

func (_c *MockEnvelopeCrypto_Decrypt_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, envelope port.EncryptedEnvelope)) *MockEnvelopeCrypto_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(port.EncryptedEnvelope))
	})
	return _c
}

func (_c *MockEnvelopeCrypto_Decrypt_Call) Return(_a0 []byte, _a1 error) *MockEnvelopeCrypto_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvelopeCrypto_Decrypt_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, port.EncryptedEnvelope) ([]byte, error)) *MockEnvelopeCrypto_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: ctx, tenant, purpose, plaintext
func (_m *MockEnvelopeCrypto) Encrypt(ctx context.Context, tenant valueobject.TenantID, purpose string, plaintext []byte) (port.EncryptedEnvelope, error) {
	ret := _m.Called(ctx, tenant, purpose, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 port.EncryptedEnvelope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, []byte) (port.EncryptedEnvelope, error)); ok {
		return rf(ctx, tenant, purpose, plaintext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, []byte) port.EncryptedEnvelope); ok {
		r0 = rf(ctx, tenant, purpose, plaintext)
	} else {
		r0 = ret.Get(0).(port.EncryptedEnvelope)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, []byte) error); ok {
		r1 = rf(ctx, tenant, purpose, plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvelopeCrypto_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEnvelopeCrypto_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - purpose string
//   - plaintext []byte
func (_e *MockEnvelopeCrypto_Expecter) Encrypt(ctx interface{}, tenant interface{}, purpose interface{}, plaintext interface{}) *MockEnvelopeCrypto_Encrypt_Call {
	return &MockEnvelopeCrypto_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, tenant, purpose, plaintext)}
}

func (_c *MockEnvelopeCrypto_Encrypt_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, purpose string, plaintext []byte)) *MockEnvelopeCrypto_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockEnvelopeCrypto_Encrypt_Call) Return(_a0 port.EncryptedEnvelope, _a1 error) *MockEnvelopeCrypto_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvelopeCrypto_Encrypt_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, []byte) (port.EncryptedEnvelope, error)) *MockEnvelopeCrypto_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnvelopeCrypto creates a new instance of MockEnvelopeCrypto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvelopeCrypto(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvelopeCrypto {
	mock := &MockEnvelopeCrypto{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
