// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockFxRateProvider is an autogenerated mock type for the FxRateProvider type
type MockFxRateProvider struct {
	mock.Mock
}

type MockFxRateProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFxRateProvider) EXPECT() *MockFxRateProvider_Expecter {
	return &MockFxRateProvider_Expecter{mock: &_m.Mock}
}

// GetRate provides a mock function with given fields: ctx, base, quote, at
func (_m *MockFxRateProvider) GetRate(ctx context.Context, base valueobject.AssetCode, quote valueobject.AssetCode, at time.Time) (valueobject.FxRate, error) {
	ret := _m.Called(ctx, base, quote, at)

	if len(ret) == 0 {
		panic("no return value specified for GetRate")
	}

	var r0 valueobject.FxRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.AssetCode, valueobject.AssetCode, time.Time) (valueobject.FxRate, error)); ok {
		return rf(ctx, base, quote, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.AssetCode, valueobject.AssetCode, time.Time) valueobject.FxRate); ok {
		r0 = rf(ctx, base, quote, at)
	} else {
		r0 = ret.Get(0).(valueobject.FxRate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.AssetCode, valueobject.AssetCode, time.Time) error); ok {
		r1 = rf(ctx, base, quote, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFxRateProvider_GetRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRate'
type MockFxRateProvider_GetRate_Call struct {
	*mock.Call
}

// GetRate is a helper method to define mock.On call
//   - ctx context.Context
//   - base valueobject.AssetCode
//   - quote valueobject.AssetCode
//   - at time.Time
func (_e *MockFxRateProvider_Expecter) GetRate(ctx interface{}, base interface{}, quote interface{}, at interface{}) *MockFxRateProvider_GetRate_Call {
	return &MockFxRateProvider_GetRate_Call{Call: _e.mock.On("GetRate", ctx, base, quote, at)}
}

func (_c *MockFxRateProvider_GetRate_Call) Run(run func(ctx context.Context, base valueobject.AssetCode, quote valueobject.AssetCode, at time.Time)) *MockFxRateProvider_GetRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.AssetCode), args[2].(valueobject.AssetCode), args[3].(time.Time))
	})
	return _c
}

func (_c *MockFxRateProvider_GetRate_Call) Return(_a0 valueobject.FxRate, _a1 error) *MockFxRateProvider_GetRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFxRateProvider_GetRate_Call) RunAndReturn(run func(context.Context, valueobject.AssetCode, valueobject.AssetCode, time.Time) (valueobject.FxRate, error)) *MockFxRateProvider_GetRate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFxRateProvider creates a new instance of MockFxRateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFxRateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFxRateProvider {
	mock := &MockFxRateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
