// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockGetPosting is an autogenerated mock type for the GetPosting type
type MockGetPosting struct {
	mock.Mock
}

type MockGetPosting_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPosting) EXPECT() *MockGetPosting_Expecter {
	return &MockGetPosting_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, query
func (_m *MockGetPosting) Execute(ctx context.Context, query port.GetPostingQuery) (port.PostingView, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 port.PostingView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.GetPostingQuery) (port.PostingView, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.GetPostingQuery) port.PostingView); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PostingView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.GetPostingQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetPosting_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetPosting_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.GetPostingQuery
func (_e *MockGetPosting_Expecter) Execute(ctx interface{}, query interface{}) *MockGetPosting_Execute_Call {
	return &MockGetPosting_Execute_Call{Call: _e.mock.On("Execute", ctx, query)}
}

func (_c *MockGetPosting_Execute_Call) Run(run func(ctx context.Context, query port.GetPostingQuery)) *MockGetPosting_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.GetPostingQuery))
	})
	return _c
}

func (_c *MockGetPosting_Execute_Call) Return(_a0 port.PostingView, _a1 error) *MockGetPosting_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetPosting_Execute_Call) RunAndReturn(run func(context.Context, port.GetPostingQuery) (port.PostingView, error)) *MockGetPosting_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetPosting creates a new instance of MockGetPosting. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPosting(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPosting {
	mock := &MockGetPosting{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
