// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockIdempotencyStore is an autogenerated mock type for the IdempotencyStore type
type MockIdempotencyStore struct {
	mock.Mock
}

type MockIdempotencyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyStore) EXPECT() *MockIdempotencyStore_Expecter {
	return &MockIdempotencyStore_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, key, response
func (_m *MockIdempotencyStore) Complete(ctx context.Context, key string, response []byte) error {
	ret := _m.Called(ctx, key, response)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIdempotencyStore_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockIdempotencyStore_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - response []byte
func (_e *MockIdempotencyStore_Expecter) Complete(ctx interface{}, key interface{}, response interface{}) *MockIdempotencyStore_Complete_Call {
	return &MockIdempotencyStore_Complete_Call{Call: _e.mock.On("Complete", ctx, key, response)}
}

func (_c *MockIdempotencyStore_Complete_Call) Run(run func(ctx context.Context, key string, response []byte)) *MockIdempotencyStore_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockIdempotencyStore_Complete_Call) Return(_a0 error) *MockIdempotencyStore_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIdempotencyStore_Complete_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockIdempotencyStore_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function with given fields: ctx, rec
func (_m *MockIdempotencyStore) Reserve(ctx context.Context, rec port.IdempotencyRecord) (port.ReserveOutcome, error) {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 port.ReserveOutcome
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.IdempotencyRecord) (port.ReserveOutcome, error)); ok {
		return rf(ctx, rec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.IdempotencyRecord) port.ReserveOutcome); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Get(0).(port.ReserveOutcome)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.IdempotencyRecord) error); ok {
		r1 = rf(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdempotencyStore_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockIdempotencyStore_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - rec port.IdempotencyRecord
func (_e *MockIdempotencyStore_Expecter) Reserve(ctx interface{}, rec interface{}) *MockIdempotencyStore_Reserve_Call {
	return &MockIdempotencyStore_Reserve_Call{Call: _e.mock.On("Reserve", ctx, rec)}
}

func (_c *MockIdempotencyStore_Reserve_Call) Run(run func(ctx context.Context, rec port.IdempotencyRecord)) *MockIdempotencyStore_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.IdempotencyRecord))
	})
	return _c
}

func (_c *MockIdempotencyStore_Reserve_Call) Return(_a0 port.ReserveOutcome, _a1 error) *MockIdempotencyStore_Reserve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdempotencyStore_Reserve_Call) RunAndReturn(run func(context.Context, port.IdempotencyRecord) (port.ReserveOutcome, error)) *MockIdempotencyStore_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdempotencyStore creates a new instance of MockIdempotencyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
