// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockListEntries is an autogenerated mock type for the ListEntries type
type MockListEntries struct {
	mock.Mock
}

type MockListEntries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListEntries) EXPECT() *MockListEntries_Expecter {
	return &MockListEntries_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, query
func (_m *MockListEntries) Execute(ctx context.Context, query port.EntriesQuery) (port.EntriesPage, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 port.EntriesPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.EntriesQuery) (port.EntriesPage, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.EntriesQuery) port.EntriesPage); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.EntriesPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.EntriesQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListEntries_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListEntries_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.EntriesQuery
func (_e *MockListEntries_Expecter) Execute(ctx interface{}, query interface{}) *MockListEntries_Execute_Call {
	return &MockListEntries_Execute_Call{Call: _e.mock.On("Execute", ctx, query)}
}

func (_c *MockListEntries_Execute_Call) Run(run func(ctx context.Context, query port.EntriesQuery)) *MockListEntries_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.EntriesQuery))
	})
	return _c
}

func (_c *MockListEntries_Execute_Call) Return(_a0 port.EntriesPage, _a1 error) *MockListEntries_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListEntries_Execute_Call) RunAndReturn(run func(context.Context, port.EntriesQuery) (port.EntriesPage, error)) *MockListEntries_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListEntries creates a new instance of MockListEntries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListEntries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListEntries {
	mock := &MockListEntries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
