// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockMessageConsumer is an autogenerated mock type for the MessageConsumer type
type MockMessageConsumer struct {
	mock.Mock
}

type MockMessageConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageConsumer) EXPECT() *MockMessageConsumer_Expecter {
	return &MockMessageConsumer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, tenant, group, subject, handler
func (_m *MockMessageConsumer) Run(ctx context.Context, tenant valueobject.TenantID, group string, subject string, handler port.MessageHandler) error {
	ret := _m.Called(ctx, tenant, group, subject, handler)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string, port.MessageHandler) error); ok {
		r0 = rf(ctx, tenant, group, subject, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageConsumer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockMessageConsumer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - group string
//   - subject string
//   - handler port.MessageHandler
func (_e *MockMessageConsumer_Expecter) Run(ctx interface{}, tenant interface{}, group interface{}, subject interface{}, handler interface{}) *MockMessageConsumer_Run_Call {
	return &MockMessageConsumer_Run_Call{Call: _e.mock.On("Run", ctx, tenant, group, subject, handler)}
}

func (_c *MockMessageConsumer_Run_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, group string, subject string, handler port.MessageHandler)) *MockMessageConsumer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(string), args[4].(port.MessageHandler))
	})
	return _c
}

func (_c *MockMessageConsumer_Run_Call) Return(_a0 error) *MockMessageConsumer_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageConsumer_Run_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, string, port.MessageHandler) error) *MockMessageConsumer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageConsumer creates a new instance of MockMessageConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageConsumer {
	mock := &MockMessageConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
