// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, notification, idempotencyKey
func (_m *MockNotifier) Send(ctx context.Context, notification port.Notification, idempotencyKey string) error {
	ret := _m.Called(ctx, notification, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.Notification, string) error); ok {
		r0 = rf(ctx, notification, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockNotifier_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - notification port.Notification
//   - idempotencyKey string
func (_e *MockNotifier_Expecter) Send(ctx interface{}, notification interface{}, idempotencyKey interface{}) *MockNotifier_Send_Call {
	return &MockNotifier_Send_Call{Call: _e.mock.On("Send", ctx, notification, idempotencyKey)}
}

func (_c *MockNotifier_Send_Call) Run(run func(ctx context.Context, notification port.Notification, idempotencyKey string)) *MockNotifier_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.Notification), args[2].(string))
	})
	return _c
}

func (_c *MockNotifier_Send_Call) Return(_a0 error) *MockNotifier_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_Send_Call) RunAndReturn(run func(context.Context, port.Notification, string) error) *MockNotifier_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
