// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockOAuthProvider is an autogenerated mock type for the OAuthProvider type
type MockOAuthProvider struct {
	mock.Mock
}

type MockOAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthProvider) EXPECT() *MockOAuthProvider_Expecter {
	return &MockOAuthProvider_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function with given fields: ctx, tenant, provider, redirectURL
func (_m *MockOAuthProvider) AuthURL(ctx context.Context, tenant valueobject.TenantID, provider string, redirectURL string) (port.OAuthSession, error) {
	ret := _m.Called(ctx, tenant, provider, redirectURL)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 port.OAuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string) (port.OAuthSession, error)); ok {
		return rf(ctx, tenant, provider, redirectURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string) port.OAuthSession); ok {
		r0 = rf(ctx, tenant, provider, redirectURL)
	} else {
		r0 = ret.Get(0).(port.OAuthSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, string) error); ok {
		r1 = rf(ctx, tenant, provider, redirectURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type MockOAuthProvider_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - provider string
//   - redirectURL string
func (_e *MockOAuthProvider_Expecter) AuthURL(ctx interface{}, tenant interface{}, provider interface{}, redirectURL interface{}) *MockOAuthProvider_AuthURL_Call {
	return &MockOAuthProvider_AuthURL_Call{Call: _e.mock.On("AuthURL", ctx, tenant, provider, redirectURL)}
}

func (_c *MockOAuthProvider_AuthURL_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, provider string, redirectURL string)) *MockOAuthProvider_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockOAuthProvider_AuthURL_Call) Return(_a0 port.OAuthSession, _a1 error) *MockOAuthProvider_AuthURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_AuthURL_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, string) (port.OAuthSession, error)) *MockOAuthProvider_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, tenant, provider, code, state
func (_m *MockOAuthProvider) Exchange(ctx context.Context, tenant valueobject.TenantID, provider string, code string, state string) (port.OAuthIdentity, error) {
	ret := _m.Called(ctx, tenant, provider, code, state)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 port.OAuthIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string, string) (port.OAuthIdentity, error)); ok {
		return rf(ctx, tenant, provider, code, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, string, string) port.OAuthIdentity); ok {
		r0 = rf(ctx, tenant, provider, code, state)
	} else {
		r0 = ret.Get(0).(port.OAuthIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, string, string) error); ok {
		r1 = rf(ctx, tenant, provider, code, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthProvider_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockOAuthProvider_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - provider string
//   - code string
//   - state string
func (_e *MockOAuthProvider_Expecter) Exchange(ctx interface{}, tenant interface{}, provider interface{}, code interface{}, state interface{}) *MockOAuthProvider_Exchange_Call {
	return &MockOAuthProvider_Exchange_Call{Call: _e.mock.On("Exchange", ctx, tenant, provider, code, state)}
}

func (_c *MockOAuthProvider_Exchange_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, provider string, code string, state string)) *MockOAuthProvider_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockOAuthProvider_Exchange_Call) Return(_a0 port.OAuthIdentity, _a1 error) *MockOAuthProvider_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthProvider_Exchange_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, string, string) (port.OAuthIdentity, error)) *MockOAuthProvider_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthProvider creates a new instance of MockOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthProvider {
	mock := &MockOAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
