// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	time "time"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, tenant, key
func (_m *MockObjectStorage) Delete(ctx context.Context, tenant valueobject.TenantID, key string) error {
	ret := _m.Called(ctx, tenant, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) error); ok {
		r0 = rf(ctx, tenant, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - key string
func (_e *MockObjectStorage_Expecter) Delete(ctx interface{}, tenant interface{}, key interface{}) *MockObjectStorage_Delete_Call {
	return &MockObjectStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, tenant, key)}
}

func (_c *MockObjectStorage_Delete_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, key string)) *MockObjectStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Delete_Call) Return(_a0 error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_Delete_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, tenant, key
func (_m *MockObjectStorage) Get(ctx context.Context, tenant valueobject.TenantID, key string) (port.StoredObject, error) {
	ret := _m.Called(ctx, tenant, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 port.StoredObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.StoredObject, error)); ok {
		return rf(ctx, tenant, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.StoredObject); ok {
		r0 = rf(ctx, tenant, key)
	} else {
		r0 = ret.Get(0).(port.StoredObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObjectStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - key string
func (_e *MockObjectStorage_Expecter) Get(ctx interface{}, tenant interface{}, key interface{}) *MockObjectStorage_Get_Call {
	return &MockObjectStorage_Get_Call{Call: _e.mock.On("Get", ctx, tenant, key)}
}

func (_c *MockObjectStorage_Get_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, key string)) *MockObjectStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockObjectStorage_Get_Call) Return(_a0 port.StoredObject, _a1 error) *MockObjectStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_Get_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.StoredObject, error)) *MockObjectStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, tenant, key, object
func (_m *MockObjectStorage) Put(ctx context.Context, tenant valueobject.TenantID, key string, object port.StoredObject) error {
	ret := _m.Called(ctx, tenant, key, object)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, port.StoredObject) error); ok {
		r0 = rf(ctx, tenant, key, object)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - key string
//   - object port.StoredObject
func (_e *MockObjectStorage_Expecter) Put(ctx interface{}, tenant interface{}, key interface{}, object interface{}) *MockObjectStorage_Put_Call {
	return &MockObjectStorage_Put_Call{Call: _e.mock.On("Put", ctx, tenant, key, object)}
}

func (_c *MockObjectStorage_Put_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, key string, object port.StoredObject)) *MockObjectStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(port.StoredObject))
	})
	return _c
}

func (_c *MockObjectStorage_Put_Call) Return(_a0 error) *MockObjectStorage_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStorage_Put_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, port.StoredObject) error) *MockObjectStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SignedURL provides a mock function with given fields: ctx, tenant, key, ttl
func (_m *MockObjectStorage) SignedURL(ctx context.Context, tenant valueobject.TenantID, key string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, tenant, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) (string, error)); ok {
		return rf(ctx, tenant, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) string); ok {
		r0 = rf(ctx, tenant, key, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, time.Duration) error); ok {
		r1 = rf(ctx, tenant, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_SignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignedURL'
type MockObjectStorage_SignedURL_Call struct {
	*mock.Call
}

// SignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - key string
//   - ttl time.Duration
func (_e *MockObjectStorage_Expecter) SignedURL(ctx interface{}, tenant interface{}, key interface{}, ttl interface{}) *MockObjectStorage_SignedURL_Call {
	return &MockObjectStorage_SignedURL_Call{Call: _e.mock.On("SignedURL", ctx, tenant, key, ttl)}
}

func (_c *MockObjectStorage_SignedURL_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, key string, ttl time.Duration)) *MockObjectStorage_SignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockObjectStorage_SignedURL_Call) Return(_a0 string, _a1 error) *MockObjectStorage_SignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_SignedURL_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, time.Duration) (string, error)) *MockObjectStorage_SignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
