// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	time "time"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockPaymentProcessor is an autogenerated mock type for the PaymentProcessor type
type MockPaymentProcessor struct {
	mock.Mock
}

type MockPaymentProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentProcessor) EXPECT() *MockPaymentProcessor_Expecter {
	return &MockPaymentProcessor_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function with given fields: ctx, req
func (_m *MockPaymentProcessor) Charge(ctx context.Context, req port.ChargeRequest) (port.ChargeResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 port.ChargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ChargeRequest) (port.ChargeResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ChargeRequest) port.ChargeResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.ChargeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ChargeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProcessor_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockPaymentProcessor_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ChargeRequest
func (_e *MockPaymentProcessor_Expecter) Charge(ctx interface{}, req interface{}) *MockPaymentProcessor_Charge_Call {
	return &MockPaymentProcessor_Charge_Call{Call: _e.mock.On("Charge", ctx, req)}
}

func (_c *MockPaymentProcessor_Charge_Call) Run(run func(ctx context.Context, req port.ChargeRequest)) *MockPaymentProcessor_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ChargeRequest))
	})
	return _c
}

func (_c *MockPaymentProcessor_Charge_Call) Return(_a0 port.ChargeResult, _a1 error) *MockPaymentProcessor_Charge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProcessor_Charge_Call) RunAndReturn(run func(context.Context, port.ChargeRequest) (port.ChargeResult, error)) *MockPaymentProcessor_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteChallenge provides a mock function with given fields: ctx, completion
func (_m *MockPaymentProcessor) CompleteChallenge(ctx context.Context, completion port.ChallengeCompletion) (port.ChargeResult, error) {
	ret := _m.Called(ctx, completion)

	if len(ret) == 0 {
		panic("no return value specified for CompleteChallenge")
	}

	var r0 port.ChargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ChallengeCompletion) (port.ChargeResult, error)); ok {
		return rf(ctx, completion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ChallengeCompletion) port.ChargeResult); ok {
		r0 = rf(ctx, completion)
	} else {
		r0 = ret.Get(0).(port.ChargeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ChallengeCompletion) error); ok {
		r1 = rf(ctx, completion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProcessor_CompleteChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteChallenge'
type MockPaymentProcessor_CompleteChallenge_Call struct {
	*mock.Call
}

// CompleteChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - completion port.ChallengeCompletion
func (_e *MockPaymentProcessor_Expecter) CompleteChallenge(ctx interface{}, completion interface{}) *MockPaymentProcessor_CompleteChallenge_Call {
	return &MockPaymentProcessor_CompleteChallenge_Call{Call: _e.mock.On("CompleteChallenge", ctx, completion)}
}

func (_c *MockPaymentProcessor_CompleteChallenge_Call) Run(run func(ctx context.Context, completion port.ChallengeCompletion)) *MockPaymentProcessor_CompleteChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ChallengeCompletion))
	})
	return _c
}

func (_c *MockPaymentProcessor_CompleteChallenge_Call) Return(_a0 port.ChargeResult, _a1 error) *MockPaymentProcessor_CompleteChallenge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProcessor_CompleteChallenge_Call) RunAndReturn(run func(context.Context, port.ChallengeCompletion) (port.ChargeResult, error)) *MockPaymentProcessor_CompleteChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, tenant, idempotencyKey, timeout
func (_m *MockPaymentProcessor) GetStatus(ctx context.Context, tenant valueobject.TenantID, idempotencyKey string, timeout time.Duration) (port.ChargeResult, error) {
	ret := _m.Called(ctx, tenant, idempotencyKey, timeout)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 port.ChargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) (port.ChargeResult, error)); ok {
		return rf(ctx, tenant, idempotencyKey, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string, time.Duration) port.ChargeResult); ok {
		r0 = rf(ctx, tenant, idempotencyKey, timeout)
	} else {
		r0 = ret.Get(0).(port.ChargeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string, time.Duration) error); ok {
		r1 = rf(ctx, tenant, idempotencyKey, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProcessor_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockPaymentProcessor_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - idempotencyKey string
//   - timeout time.Duration
func (_e *MockPaymentProcessor_Expecter) GetStatus(ctx interface{}, tenant interface{}, idempotencyKey interface{}, timeout interface{}) *MockPaymentProcessor_GetStatus_Call {
	return &MockPaymentProcessor_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, tenant, idempotencyKey, timeout)}
}

func (_c *MockPaymentProcessor_GetStatus_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, idempotencyKey string, timeout time.Duration)) *MockPaymentProcessor_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockPaymentProcessor_GetStatus_Call) Return(_a0 port.ChargeResult, _a1 error) *MockPaymentProcessor_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProcessor_GetStatus_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string, time.Duration) (port.ChargeResult, error)) *MockPaymentProcessor_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RefundCharge provides a mock function with given fields: ctx, req
func (_m *MockPaymentProcessor) RefundCharge(ctx context.Context, req port.RefundChargeRequest) (port.ChargeResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefundCharge")
	}

	var r0 port.ChargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundChargeRequest) (port.ChargeResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundChargeRequest) port.ChargeResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.ChargeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RefundChargeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProcessor_RefundCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefundCharge'
type MockPaymentProcessor_RefundCharge_Call struct {
	*mock.Call
}

// RefundCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.RefundChargeRequest
func (_e *MockPaymentProcessor_Expecter) RefundCharge(ctx interface{}, req interface{}) *MockPaymentProcessor_RefundCharge_Call {
	return &MockPaymentProcessor_RefundCharge_Call{Call: _e.mock.On("RefundCharge", ctx, req)}
}

func (_c *MockPaymentProcessor_RefundCharge_Call) Run(run func(ctx context.Context, req port.RefundChargeRequest)) *MockPaymentProcessor_RefundCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.RefundChargeRequest))
	})
	return _c
}

func (_c *MockPaymentProcessor_RefundCharge_Call) Return(_a0 port.ChargeResult, _a1 error) *MockPaymentProcessor_RefundCharge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProcessor_RefundCharge_Call) RunAndReturn(run func(context.Context, port.RefundChargeRequest) (port.ChargeResult, error)) *MockPaymentProcessor_RefundCharge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentProcessor creates a new instance of MockPaymentProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentProcessor {
	mock := &MockPaymentProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
