// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockPaymentCommandUseCases is an autogenerated mock type for the PaymentCommandUseCases type
type MockPaymentCommandUseCases struct {
	mock.Mock
}

type MockPaymentCommandUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentCommandUseCases) EXPECT() *MockPaymentCommandUseCases_Expecter {
	return &MockPaymentCommandUseCases_Expecter{mock: &_m.Mock}
}

// CancelIntent provides a mock function with given fields: ctx, query
func (_m *MockPaymentCommandUseCases) CancelIntent(ctx context.Context, query port.PaymentQuery) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PaymentIntentResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CancelIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelIntent'
type MockPaymentCommandUseCases_CancelIntent_Call struct {
	*mock.Call
}

// CancelIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentCommandUseCases_Expecter) CancelIntent(ctx interface{}, query interface{}) *MockPaymentCommandUseCases_CancelIntent_Call {
	return &MockPaymentCommandUseCases_CancelIntent_Call{Call: _e.mock.On("CancelIntent", ctx, query)}
}

func (_c *MockPaymentCommandUseCases_CancelIntent_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentCommandUseCases_CancelIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CancelIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentCommandUseCases_CancelIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CancelIntent_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)) *MockPaymentCommandUseCases_CancelIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPayout provides a mock function with given fields: ctx, query
func (_m *MockPaymentCommandUseCases) CancelPayout(ctx context.Context, query port.PaymentQuery) (port.PayoutResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PayoutResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PayoutResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CancelPayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPayout'
type MockPaymentCommandUseCases_CancelPayout_Call struct {
	*mock.Call
}

// CancelPayout is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentCommandUseCases_Expecter) CancelPayout(ctx interface{}, query interface{}) *MockPaymentCommandUseCases_CancelPayout_Call {
	return &MockPaymentCommandUseCases_CancelPayout_Call{Call: _e.mock.On("CancelPayout", ctx, query)}
}

func (_c *MockPaymentCommandUseCases_CancelPayout_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentCommandUseCases_CancelPayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CancelPayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentCommandUseCases_CancelPayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CancelPayout_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PayoutResult, error)) *MockPaymentCommandUseCases_CancelPayout_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmIntent provides a mock function with given fields: ctx, req
func (_m *MockPaymentCommandUseCases) ConfirmIntent(ctx context.Context, req port.ConfirmIntentRequest) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ConfirmIntentRequest) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ConfirmIntentRequest) port.PaymentIntentResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ConfirmIntentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_ConfirmIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmIntent'
type MockPaymentCommandUseCases_ConfirmIntent_Call struct {
	*mock.Call
}

// ConfirmIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ConfirmIntentRequest
func (_e *MockPaymentCommandUseCases_Expecter) ConfirmIntent(ctx interface{}, req interface{}) *MockPaymentCommandUseCases_ConfirmIntent_Call {
	return &MockPaymentCommandUseCases_ConfirmIntent_Call{Call: _e.mock.On("ConfirmIntent", ctx, req)}
}

func (_c *MockPaymentCommandUseCases_ConfirmIntent_Call) Run(run func(ctx context.Context, req port.ConfirmIntentRequest)) *MockPaymentCommandUseCases_ConfirmIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ConfirmIntentRequest))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_ConfirmIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentCommandUseCases_ConfirmIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_ConfirmIntent_Call) RunAndReturn(run func(context.Context, port.ConfirmIntentRequest) (port.PaymentIntentResult, error)) *MockPaymentCommandUseCases_ConfirmIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntent provides a mock function with given fields: ctx, req
func (_m *MockPaymentCommandUseCases) CreateIntent(ctx context.Context, req port.PaymentIntentRequest) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentIntentRequest) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentIntentRequest) port.PaymentIntentResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentIntentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CreateIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntent'
type MockPaymentCommandUseCases_CreateIntent_Call struct {
	*mock.Call
}

// CreateIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PaymentIntentRequest
func (_e *MockPaymentCommandUseCases_Expecter) CreateIntent(ctx interface{}, req interface{}) *MockPaymentCommandUseCases_CreateIntent_Call {
	return &MockPaymentCommandUseCases_CreateIntent_Call{Call: _e.mock.On("CreateIntent", ctx, req)}
}

func (_c *MockPaymentCommandUseCases_CreateIntent_Call) Run(run func(ctx context.Context, req port.PaymentIntentRequest)) *MockPaymentCommandUseCases_CreateIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentIntentRequest))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentCommandUseCases_CreateIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateIntent_Call) RunAndReturn(run func(context.Context, port.PaymentIntentRequest) (port.PaymentIntentResult, error)) *MockPaymentCommandUseCases_CreateIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayout provides a mock function with given fields: ctx, req
func (_m *MockPaymentCommandUseCases) CreatePayout(ctx context.Context, req port.PayoutRequest) (port.PayoutResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PayoutRequest) (port.PayoutResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PayoutRequest) port.PayoutResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PayoutRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CreatePayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayout'
type MockPaymentCommandUseCases_CreatePayout_Call struct {
	*mock.Call
}

// CreatePayout is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PayoutRequest
func (_e *MockPaymentCommandUseCases_Expecter) CreatePayout(ctx interface{}, req interface{}) *MockPaymentCommandUseCases_CreatePayout_Call {
	return &MockPaymentCommandUseCases_CreatePayout_Call{Call: _e.mock.On("CreatePayout", ctx, req)}
}

func (_c *MockPaymentCommandUseCases_CreatePayout_Call) Run(run func(ctx context.Context, req port.PayoutRequest)) *MockPaymentCommandUseCases_CreatePayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PayoutRequest))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CreatePayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentCommandUseCases_CreatePayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CreatePayout_Call) RunAndReturn(run func(context.Context, port.PayoutRequest) (port.PayoutResult, error)) *MockPaymentCommandUseCases_CreatePayout_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefund provides a mock function with given fields: ctx, req
func (_m *MockPaymentCommandUseCases) CreateRefund(ctx context.Context, req port.RefundRequest) (port.RefundResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}

	var r0 port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundRequest) (port.RefundResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundRequest) port.RefundResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.RefundResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RefundRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CreateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefund'
type MockPaymentCommandUseCases_CreateRefund_Call struct {
	*mock.Call
}

// CreateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.RefundRequest
func (_e *MockPaymentCommandUseCases_Expecter) CreateRefund(ctx interface{}, req interface{}) *MockPaymentCommandUseCases_CreateRefund_Call {
	return &MockPaymentCommandUseCases_CreateRefund_Call{Call: _e.mock.On("CreateRefund", ctx, req)}
}

func (_c *MockPaymentCommandUseCases_CreateRefund_Call) Run(run func(ctx context.Context, req port.RefundRequest)) *MockPaymentCommandUseCases_CreateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.RefundRequest))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateRefund_Call) Return(_a0 port.RefundResult, _a1 error) *MockPaymentCommandUseCases_CreateRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateRefund_Call) RunAndReturn(run func(context.Context, port.RefundRequest) (port.RefundResult, error)) *MockPaymentCommandUseCases_CreateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTopup provides a mock function with given fields: ctx, req
func (_m *MockPaymentCommandUseCases) CreateTopup(ctx context.Context, req port.TopupRequest) (port.TopupResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopup")
	}

	var r0 port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TopupRequest) (port.TopupResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TopupRequest) port.TopupResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TopupResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TopupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentCommandUseCases_CreateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopup'
type MockPaymentCommandUseCases_CreateTopup_Call struct {
	*mock.Call
}

// CreateTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.TopupRequest
func (_e *MockPaymentCommandUseCases_Expecter) CreateTopup(ctx interface{}, req interface{}) *MockPaymentCommandUseCases_CreateTopup_Call {
	return &MockPaymentCommandUseCases_CreateTopup_Call{Call: _e.mock.On("CreateTopup", ctx, req)}
}

func (_c *MockPaymentCommandUseCases_CreateTopup_Call) Run(run func(ctx context.Context, req port.TopupRequest)) *MockPaymentCommandUseCases_CreateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TopupRequest))
	})
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateTopup_Call) Return(_a0 port.TopupResult, _a1 error) *MockPaymentCommandUseCases_CreateTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentCommandUseCases_CreateTopup_Call) RunAndReturn(run func(context.Context, port.TopupRequest) (port.TopupResult, error)) *MockPaymentCommandUseCases_CreateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentCommandUseCases creates a new instance of MockPaymentCommandUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentCommandUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentCommandUseCases {
	mock := &MockPaymentCommandUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
