// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockPaymentUseCases is an autogenerated mock type for the PaymentUseCases type
type MockPaymentUseCases struct {
	mock.Mock
}

type MockPaymentUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentUseCases) EXPECT() *MockPaymentUseCases_Expecter {
	return &MockPaymentUseCases_Expecter{mock: &_m.Mock}
}

// CancelIntent provides a mock function with given fields: ctx, query
func (_m *MockPaymentUseCases) CancelIntent(ctx context.Context, query port.PaymentQuery) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PaymentIntentResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CancelIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelIntent'
type MockPaymentUseCases_CancelIntent_Call struct {
	*mock.Call
}

// CancelIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentUseCases_Expecter) CancelIntent(ctx interface{}, query interface{}) *MockPaymentUseCases_CancelIntent_Call {
	return &MockPaymentUseCases_CancelIntent_Call{Call: _e.mock.On("CancelIntent", ctx, query)}
}

func (_c *MockPaymentUseCases_CancelIntent_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentUseCases_CancelIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentUseCases_CancelIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentUseCases_CancelIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CancelIntent_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)) *MockPaymentUseCases_CancelIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CancelPayout provides a mock function with given fields: ctx, query
func (_m *MockPaymentUseCases) CancelPayout(ctx context.Context, query port.PaymentQuery) (port.PayoutResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PayoutResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PayoutResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CancelPayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPayout'
type MockPaymentUseCases_CancelPayout_Call struct {
	*mock.Call
}

// CancelPayout is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentUseCases_Expecter) CancelPayout(ctx interface{}, query interface{}) *MockPaymentUseCases_CancelPayout_Call {
	return &MockPaymentUseCases_CancelPayout_Call{Call: _e.mock.On("CancelPayout", ctx, query)}
}

func (_c *MockPaymentUseCases_CancelPayout_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentUseCases_CancelPayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentUseCases_CancelPayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentUseCases_CancelPayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CancelPayout_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PayoutResult, error)) *MockPaymentUseCases_CancelPayout_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmIntent provides a mock function with given fields: ctx, req
func (_m *MockPaymentUseCases) ConfirmIntent(ctx context.Context, req port.ConfirmIntentRequest) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ConfirmIntentRequest) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ConfirmIntentRequest) port.PaymentIntentResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ConfirmIntentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_ConfirmIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmIntent'
type MockPaymentUseCases_ConfirmIntent_Call struct {
	*mock.Call
}

// ConfirmIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ConfirmIntentRequest
func (_e *MockPaymentUseCases_Expecter) ConfirmIntent(ctx interface{}, req interface{}) *MockPaymentUseCases_ConfirmIntent_Call {
	return &MockPaymentUseCases_ConfirmIntent_Call{Call: _e.mock.On("ConfirmIntent", ctx, req)}
}

func (_c *MockPaymentUseCases_ConfirmIntent_Call) Run(run func(ctx context.Context, req port.ConfirmIntentRequest)) *MockPaymentUseCases_ConfirmIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ConfirmIntentRequest))
	})
	return _c
}

func (_c *MockPaymentUseCases_ConfirmIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentUseCases_ConfirmIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_ConfirmIntent_Call) RunAndReturn(run func(context.Context, port.ConfirmIntentRequest) (port.PaymentIntentResult, error)) *MockPaymentUseCases_ConfirmIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntent provides a mock function with given fields: ctx, req
func (_m *MockPaymentUseCases) CreateIntent(ctx context.Context, req port.PaymentIntentRequest) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentIntentRequest) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentIntentRequest) port.PaymentIntentResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentIntentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CreateIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntent'
type MockPaymentUseCases_CreateIntent_Call struct {
	*mock.Call
}

// CreateIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PaymentIntentRequest
func (_e *MockPaymentUseCases_Expecter) CreateIntent(ctx interface{}, req interface{}) *MockPaymentUseCases_CreateIntent_Call {
	return &MockPaymentUseCases_CreateIntent_Call{Call: _e.mock.On("CreateIntent", ctx, req)}
}

func (_c *MockPaymentUseCases_CreateIntent_Call) Run(run func(ctx context.Context, req port.PaymentIntentRequest)) *MockPaymentUseCases_CreateIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentIntentRequest))
	})
	return _c
}

func (_c *MockPaymentUseCases_CreateIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentUseCases_CreateIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CreateIntent_Call) RunAndReturn(run func(context.Context, port.PaymentIntentRequest) (port.PaymentIntentResult, error)) *MockPaymentUseCases_CreateIntent_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayout provides a mock function with given fields: ctx, req
func (_m *MockPaymentUseCases) CreatePayout(ctx context.Context, req port.PayoutRequest) (port.PayoutResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PayoutRequest) (port.PayoutResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PayoutRequest) port.PayoutResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PayoutRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CreatePayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayout'
type MockPaymentUseCases_CreatePayout_Call struct {
	*mock.Call
}

// CreatePayout is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.PayoutRequest
func (_e *MockPaymentUseCases_Expecter) CreatePayout(ctx interface{}, req interface{}) *MockPaymentUseCases_CreatePayout_Call {
	return &MockPaymentUseCases_CreatePayout_Call{Call: _e.mock.On("CreatePayout", ctx, req)}
}

func (_c *MockPaymentUseCases_CreatePayout_Call) Run(run func(ctx context.Context, req port.PayoutRequest)) *MockPaymentUseCases_CreatePayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PayoutRequest))
	})
	return _c
}

func (_c *MockPaymentUseCases_CreatePayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentUseCases_CreatePayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CreatePayout_Call) RunAndReturn(run func(context.Context, port.PayoutRequest) (port.PayoutResult, error)) *MockPaymentUseCases_CreatePayout_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefund provides a mock function with given fields: ctx, req
func (_m *MockPaymentUseCases) CreateRefund(ctx context.Context, req port.RefundRequest) (port.RefundResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}

	var r0 port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundRequest) (port.RefundResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RefundRequest) port.RefundResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.RefundResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RefundRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CreateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefund'
type MockPaymentUseCases_CreateRefund_Call struct {
	*mock.Call
}

// CreateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.RefundRequest
func (_e *MockPaymentUseCases_Expecter) CreateRefund(ctx interface{}, req interface{}) *MockPaymentUseCases_CreateRefund_Call {
	return &MockPaymentUseCases_CreateRefund_Call{Call: _e.mock.On("CreateRefund", ctx, req)}
}

func (_c *MockPaymentUseCases_CreateRefund_Call) Run(run func(ctx context.Context, req port.RefundRequest)) *MockPaymentUseCases_CreateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.RefundRequest))
	})
	return _c
}

func (_c *MockPaymentUseCases_CreateRefund_Call) Return(_a0 port.RefundResult, _a1 error) *MockPaymentUseCases_CreateRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CreateRefund_Call) RunAndReturn(run func(context.Context, port.RefundRequest) (port.RefundResult, error)) *MockPaymentUseCases_CreateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTopup provides a mock function with given fields: ctx, req
func (_m *MockPaymentUseCases) CreateTopup(ctx context.Context, req port.TopupRequest) (port.TopupResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopup")
	}

	var r0 port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TopupRequest) (port.TopupResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TopupRequest) port.TopupResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TopupResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TopupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_CreateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopup'
type MockPaymentUseCases_CreateTopup_Call struct {
	*mock.Call
}

// CreateTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.TopupRequest
func (_e *MockPaymentUseCases_Expecter) CreateTopup(ctx interface{}, req interface{}) *MockPaymentUseCases_CreateTopup_Call {
	return &MockPaymentUseCases_CreateTopup_Call{Call: _e.mock.On("CreateTopup", ctx, req)}
}

func (_c *MockPaymentUseCases_CreateTopup_Call) Run(run func(ctx context.Context, req port.TopupRequest)) *MockPaymentUseCases_CreateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TopupRequest))
	})
	return _c
}

func (_c *MockPaymentUseCases_CreateTopup_Call) Return(_a0 port.TopupResult, _a1 error) *MockPaymentUseCases_CreateTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_CreateTopup_Call) RunAndReturn(run func(context.Context, port.TopupRequest) (port.TopupResult, error)) *MockPaymentUseCases_CreateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntent provides a mock function with given fields: ctx, query
func (_m *MockPaymentUseCases) GetIntent(ctx context.Context, query port.PaymentQuery) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PaymentIntentResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_GetIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntent'
type MockPaymentUseCases_GetIntent_Call struct {
	*mock.Call
}

// GetIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentUseCases_Expecter) GetIntent(ctx interface{}, query interface{}) *MockPaymentUseCases_GetIntent_Call {
	return &MockPaymentUseCases_GetIntent_Call{Call: _e.mock.On("GetIntent", ctx, query)}
}

func (_c *MockPaymentUseCases_GetIntent_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentUseCases_GetIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentUseCases_GetIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentUseCases_GetIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_GetIntent_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)) *MockPaymentUseCases_GetIntent_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayout provides a mock function with given fields: ctx, query
func (_m *MockPaymentUseCases) GetPayout(ctx context.Context, query port.PaymentQuery) (port.PayoutResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PayoutResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PayoutResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_GetPayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayout'
type MockPaymentUseCases_GetPayout_Call struct {
	*mock.Call
}

// GetPayout is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentUseCases_Expecter) GetPayout(ctx interface{}, query interface{}) *MockPaymentUseCases_GetPayout_Call {
	return &MockPaymentUseCases_GetPayout_Call{Call: _e.mock.On("GetPayout", ctx, query)}
}

func (_c *MockPaymentUseCases_GetPayout_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentUseCases_GetPayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentUseCases_GetPayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentUseCases_GetPayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_GetPayout_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PayoutResult, error)) *MockPaymentUseCases_GetPayout_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefund provides a mock function with given fields: ctx, query
func (_m *MockPaymentUseCases) GetRefund(ctx context.Context, query port.PaymentQuery) (port.RefundResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetRefund")
	}

	var r0 port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.RefundResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.RefundResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.RefundResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_GetRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefund'
type MockPaymentUseCases_GetRefund_Call struct {
	*mock.Call
}

// GetRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentUseCases_Expecter) GetRefund(ctx interface{}, query interface{}) *MockPaymentUseCases_GetRefund_Call {
	return &MockPaymentUseCases_GetRefund_Call{Call: _e.mock.On("GetRefund", ctx, query)}
}

func (_c *MockPaymentUseCases_GetRefund_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentUseCases_GetRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentUseCases_GetRefund_Call) Return(_a0 port.RefundResult, _a1 error) *MockPaymentUseCases_GetRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_GetRefund_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.RefundResult, error)) *MockPaymentUseCases_GetRefund_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopup provides a mock function with given fields: ctx, tenant, topupID
func (_m *MockPaymentUseCases) GetTopup(ctx context.Context, tenant valueobject.TenantID, topupID string) (port.TopupResult, error) {
	ret := _m.Called(ctx, tenant, topupID)

	if len(ret) == 0 {
		panic("no return value specified for GetTopup")
	}

	var r0 port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.TopupResult, error)); ok {
		return rf(ctx, tenant, topupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.TopupResult); ok {
		r0 = rf(ctx, tenant, topupID)
	} else {
		r0 = ret.Get(0).(port.TopupResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, topupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_GetTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopup'
type MockPaymentUseCases_GetTopup_Call struct {
	*mock.Call
}

// GetTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - topupID string
func (_e *MockPaymentUseCases_Expecter) GetTopup(ctx interface{}, tenant interface{}, topupID interface{}) *MockPaymentUseCases_GetTopup_Call {
	return &MockPaymentUseCases_GetTopup_Call{Call: _e.mock.On("GetTopup", ctx, tenant, topupID)}
}

func (_c *MockPaymentUseCases_GetTopup_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, topupID string)) *MockPaymentUseCases_GetTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentUseCases_GetTopup_Call) Return(_a0 port.TopupResult, _a1 error) *MockPaymentUseCases_GetTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_GetTopup_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.TopupResult, error)) *MockPaymentUseCases_GetTopup_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntents provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentUseCases) ListIntents(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListIntents")
	}

	var r0 []port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.PaymentIntentResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.PaymentIntentResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.PaymentIntentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_ListIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntents'
type MockPaymentUseCases_ListIntents_Call struct {
	*mock.Call
}

// ListIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentUseCases_Expecter) ListIntents(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentUseCases_ListIntents_Call {
	return &MockPaymentUseCases_ListIntents_Call{Call: _e.mock.On("ListIntents", ctx, tenant, limit)}
}

func (_c *MockPaymentUseCases_ListIntents_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentUseCases_ListIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentUseCases_ListIntents_Call) Return(_a0 []port.PaymentIntentResult, _a1 error) *MockPaymentUseCases_ListIntents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_ListIntents_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.PaymentIntentResult, error)) *MockPaymentUseCases_ListIntents_Call {
	_c.Call.Return(run)
	return _c
}

// ListPayouts provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentUseCases) ListPayouts(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.PayoutResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPayouts")
	}

	var r0 []port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.PayoutResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.PayoutResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.PayoutResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_ListPayouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayouts'
type MockPaymentUseCases_ListPayouts_Call struct {
	*mock.Call
}

// ListPayouts is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentUseCases_Expecter) ListPayouts(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentUseCases_ListPayouts_Call {
	return &MockPaymentUseCases_ListPayouts_Call{Call: _e.mock.On("ListPayouts", ctx, tenant, limit)}
}

func (_c *MockPaymentUseCases_ListPayouts_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentUseCases_ListPayouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentUseCases_ListPayouts_Call) Return(_a0 []port.PayoutResult, _a1 error) *MockPaymentUseCases_ListPayouts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_ListPayouts_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.PayoutResult, error)) *MockPaymentUseCases_ListPayouts_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefunds provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentUseCases) ListRefunds(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.RefundResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.RefundResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.RefundResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.RefundResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockPaymentUseCases_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentUseCases_Expecter) ListRefunds(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentUseCases_ListRefunds_Call {
	return &MockPaymentUseCases_ListRefunds_Call{Call: _e.mock.On("ListRefunds", ctx, tenant, limit)}
}

func (_c *MockPaymentUseCases_ListRefunds_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentUseCases_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentUseCases_ListRefunds_Call) Return(_a0 []port.RefundResult, _a1 error) *MockPaymentUseCases_ListRefunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_ListRefunds_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.RefundResult, error)) *MockPaymentUseCases_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopups provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentUseCases) ListTopups(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.TopupResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTopups")
	}

	var r0 []port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.TopupResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.TopupResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.TopupResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentUseCases_ListTopups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopups'
type MockPaymentUseCases_ListTopups_Call struct {
	*mock.Call
}

// ListTopups is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentUseCases_Expecter) ListTopups(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentUseCases_ListTopups_Call {
	return &MockPaymentUseCases_ListTopups_Call{Call: _e.mock.On("ListTopups", ctx, tenant, limit)}
}

func (_c *MockPaymentUseCases_ListTopups_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentUseCases_ListTopups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentUseCases_ListTopups_Call) Return(_a0 []port.TopupResult, _a1 error) *MockPaymentUseCases_ListTopups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentUseCases_ListTopups_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.TopupResult, error)) *MockPaymentUseCases_ListTopups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentUseCases creates a new instance of MockPaymentUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentUseCases {
	mock := &MockPaymentUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
