// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockPaymentQueryUseCases is an autogenerated mock type for the PaymentQueryUseCases type
type MockPaymentQueryUseCases struct {
	mock.Mock
}

type MockPaymentQueryUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentQueryUseCases) EXPECT() *MockPaymentQueryUseCases_Expecter {
	return &MockPaymentQueryUseCases_Expecter{mock: &_m.Mock}
}

// GetIntent provides a mock function with given fields: ctx, query
func (_m *MockPaymentQueryUseCases) GetIntent(ctx context.Context, query port.PaymentQuery) (port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetIntent")
	}

	var r0 port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PaymentIntentResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PaymentIntentResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_GetIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntent'
type MockPaymentQueryUseCases_GetIntent_Call struct {
	*mock.Call
}

// GetIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentQueryUseCases_Expecter) GetIntent(ctx interface{}, query interface{}) *MockPaymentQueryUseCases_GetIntent_Call {
	return &MockPaymentQueryUseCases_GetIntent_Call{Call: _e.mock.On("GetIntent", ctx, query)}
}

func (_c *MockPaymentQueryUseCases_GetIntent_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentQueryUseCases_GetIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_GetIntent_Call) Return(_a0 port.PaymentIntentResult, _a1 error) *MockPaymentQueryUseCases_GetIntent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_GetIntent_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PaymentIntentResult, error)) *MockPaymentQueryUseCases_GetIntent_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayout provides a mock function with given fields: ctx, query
func (_m *MockPaymentQueryUseCases) GetPayout(ctx context.Context, query port.PaymentQuery) (port.PayoutResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPayout")
	}

	var r0 port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.PayoutResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.PayoutResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.PayoutResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_GetPayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayout'
type MockPaymentQueryUseCases_GetPayout_Call struct {
	*mock.Call
}

// GetPayout is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentQueryUseCases_Expecter) GetPayout(ctx interface{}, query interface{}) *MockPaymentQueryUseCases_GetPayout_Call {
	return &MockPaymentQueryUseCases_GetPayout_Call{Call: _e.mock.On("GetPayout", ctx, query)}
}

func (_c *MockPaymentQueryUseCases_GetPayout_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentQueryUseCases_GetPayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_GetPayout_Call) Return(_a0 port.PayoutResult, _a1 error) *MockPaymentQueryUseCases_GetPayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_GetPayout_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.PayoutResult, error)) *MockPaymentQueryUseCases_GetPayout_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefund provides a mock function with given fields: ctx, query
func (_m *MockPaymentQueryUseCases) GetRefund(ctx context.Context, query port.PaymentQuery) (port.RefundResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetRefund")
	}

	var r0 port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) (port.RefundResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PaymentQuery) port.RefundResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.RefundResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PaymentQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_GetRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefund'
type MockPaymentQueryUseCases_GetRefund_Call struct {
	*mock.Call
}

// GetRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.PaymentQuery
func (_e *MockPaymentQueryUseCases_Expecter) GetRefund(ctx interface{}, query interface{}) *MockPaymentQueryUseCases_GetRefund_Call {
	return &MockPaymentQueryUseCases_GetRefund_Call{Call: _e.mock.On("GetRefund", ctx, query)}
}

func (_c *MockPaymentQueryUseCases_GetRefund_Call) Run(run func(ctx context.Context, query port.PaymentQuery)) *MockPaymentQueryUseCases_GetRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PaymentQuery))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_GetRefund_Call) Return(_a0 port.RefundResult, _a1 error) *MockPaymentQueryUseCases_GetRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_GetRefund_Call) RunAndReturn(run func(context.Context, port.PaymentQuery) (port.RefundResult, error)) *MockPaymentQueryUseCases_GetRefund_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopup provides a mock function with given fields: ctx, tenant, topupID
func (_m *MockPaymentQueryUseCases) GetTopup(ctx context.Context, tenant valueobject.TenantID, topupID string) (port.TopupResult, error) {
	ret := _m.Called(ctx, tenant, topupID)

	if len(ret) == 0 {
		panic("no return value specified for GetTopup")
	}

	var r0 port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.TopupResult, error)); ok {
		return rf(ctx, tenant, topupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.TopupResult); ok {
		r0 = rf(ctx, tenant, topupID)
	} else {
		r0 = ret.Get(0).(port.TopupResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, topupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_GetTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopup'
type MockPaymentQueryUseCases_GetTopup_Call struct {
	*mock.Call
}

// GetTopup is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - topupID string
func (_e *MockPaymentQueryUseCases_Expecter) GetTopup(ctx interface{}, tenant interface{}, topupID interface{}) *MockPaymentQueryUseCases_GetTopup_Call {
	return &MockPaymentQueryUseCases_GetTopup_Call{Call: _e.mock.On("GetTopup", ctx, tenant, topupID)}
}

func (_c *MockPaymentQueryUseCases_GetTopup_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, topupID string)) *MockPaymentQueryUseCases_GetTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_GetTopup_Call) Return(_a0 port.TopupResult, _a1 error) *MockPaymentQueryUseCases_GetTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_GetTopup_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.TopupResult, error)) *MockPaymentQueryUseCases_GetTopup_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntents provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentQueryUseCases) ListIntents(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.PaymentIntentResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListIntents")
	}

	var r0 []port.PaymentIntentResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.PaymentIntentResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.PaymentIntentResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.PaymentIntentResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_ListIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntents'
type MockPaymentQueryUseCases_ListIntents_Call struct {
	*mock.Call
}

// ListIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentQueryUseCases_Expecter) ListIntents(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentQueryUseCases_ListIntents_Call {
	return &MockPaymentQueryUseCases_ListIntents_Call{Call: _e.mock.On("ListIntents", ctx, tenant, limit)}
}

func (_c *MockPaymentQueryUseCases_ListIntents_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentQueryUseCases_ListIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_ListIntents_Call) Return(_a0 []port.PaymentIntentResult, _a1 error) *MockPaymentQueryUseCases_ListIntents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_ListIntents_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.PaymentIntentResult, error)) *MockPaymentQueryUseCases_ListIntents_Call {
	_c.Call.Return(run)
	return _c
}

// ListPayouts provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentQueryUseCases) ListPayouts(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.PayoutResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPayouts")
	}

	var r0 []port.PayoutResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.PayoutResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.PayoutResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.PayoutResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_ListPayouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayouts'
type MockPaymentQueryUseCases_ListPayouts_Call struct {
	*mock.Call
}

// ListPayouts is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentQueryUseCases_Expecter) ListPayouts(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentQueryUseCases_ListPayouts_Call {
	return &MockPaymentQueryUseCases_ListPayouts_Call{Call: _e.mock.On("ListPayouts", ctx, tenant, limit)}
}

func (_c *MockPaymentQueryUseCases_ListPayouts_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentQueryUseCases_ListPayouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_ListPayouts_Call) Return(_a0 []port.PayoutResult, _a1 error) *MockPaymentQueryUseCases_ListPayouts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_ListPayouts_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.PayoutResult, error)) *MockPaymentQueryUseCases_ListPayouts_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefunds provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentQueryUseCases) ListRefunds(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.RefundResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []port.RefundResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.RefundResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.RefundResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.RefundResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockPaymentQueryUseCases_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentQueryUseCases_Expecter) ListRefunds(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentQueryUseCases_ListRefunds_Call {
	return &MockPaymentQueryUseCases_ListRefunds_Call{Call: _e.mock.On("ListRefunds", ctx, tenant, limit)}
}

func (_c *MockPaymentQueryUseCases_ListRefunds_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentQueryUseCases_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_ListRefunds_Call) Return(_a0 []port.RefundResult, _a1 error) *MockPaymentQueryUseCases_ListRefunds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_ListRefunds_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.RefundResult, error)) *MockPaymentQueryUseCases_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopups provides a mock function with given fields: ctx, tenant, limit
func (_m *MockPaymentQueryUseCases) ListTopups(ctx context.Context, tenant valueobject.TenantID, limit int) ([]port.TopupResult, error) {
	ret := _m.Called(ctx, tenant, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTopups")
	}

	var r0 []port.TopupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) ([]port.TopupResult, error)); ok {
		return rf(ctx, tenant, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, int) []port.TopupResult); ok {
		r0 = rf(ctx, tenant, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.TopupResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, int) error); ok {
		r1 = rf(ctx, tenant, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentQueryUseCases_ListTopups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopups'
type MockPaymentQueryUseCases_ListTopups_Call struct {
	*mock.Call
}

// ListTopups is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - limit int
func (_e *MockPaymentQueryUseCases_Expecter) ListTopups(ctx interface{}, tenant interface{}, limit interface{}) *MockPaymentQueryUseCases_ListTopups_Call {
	return &MockPaymentQueryUseCases_ListTopups_Call{Call: _e.mock.On("ListTopups", ctx, tenant, limit)}
}

func (_c *MockPaymentQueryUseCases_ListTopups_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, limit int)) *MockPaymentQueryUseCases_ListTopups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(int))
	})
	return _c
}

func (_c *MockPaymentQueryUseCases_ListTopups_Call) Return(_a0 []port.TopupResult, _a1 error) *MockPaymentQueryUseCases_ListTopups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentQueryUseCases_ListTopups_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, int) ([]port.TopupResult, error)) *MockPaymentQueryUseCases_ListTopups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentQueryUseCases creates a new instance of MockPaymentQueryUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentQueryUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentQueryUseCases {
	mock := &MockPaymentQueryUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
