// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockPostingQuery is an autogenerated mock type for the PostingQuery type
type MockPostingQuery struct {
	mock.Mock
}

type MockPostingQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostingQuery) EXPECT() *MockPostingQuery_Expecter {
	return &MockPostingQuery_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockPostingQuery) Search(ctx context.Context, filter port.PostingFilter) (port.PostingSearchPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 port.PostingSearchPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PostingFilter) (port.PostingSearchPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PostingFilter) port.PostingSearchPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(port.PostingSearchPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PostingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostingQuery_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockPostingQuery_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter port.PostingFilter
func (_e *MockPostingQuery_Expecter) Search(ctx interface{}, filter interface{}) *MockPostingQuery_Search_Call {
	return &MockPostingQuery_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockPostingQuery_Search_Call) Run(run func(ctx context.Context, filter port.PostingFilter)) *MockPostingQuery_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PostingFilter))
	})
	return _c
}

func (_c *MockPostingQuery_Search_Call) Return(_a0 port.PostingSearchPage, _a1 error) *MockPostingQuery_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostingQuery_Search_Call) RunAndReturn(run func(context.Context, port.PostingFilter) (port.PostingSearchPage, error)) *MockPostingQuery_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostingQuery creates a new instance of MockPostingQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostingQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostingQuery {
	mock := &MockPostingQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
