// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockPostLedgerPosting is an autogenerated mock type for the PostLedgerPosting type
type MockPostLedgerPosting struct {
	mock.Mock
}

type MockPostLedgerPosting_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostLedgerPosting) EXPECT() *MockPostLedgerPosting_Expecter {
	return &MockPostLedgerPosting_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cmd
func (_m *MockPostLedgerPosting) Execute(ctx context.Context, cmd port.PostPostingCommand) (port.PostingResult, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 port.PostingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.PostPostingCommand) (port.PostingResult, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.PostPostingCommand) port.PostingResult); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(port.PostingResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.PostPostingCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostLedgerPosting_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPostLedgerPosting_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd port.PostPostingCommand
func (_e *MockPostLedgerPosting_Expecter) Execute(ctx interface{}, cmd interface{}) *MockPostLedgerPosting_Execute_Call {
	return &MockPostLedgerPosting_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockPostLedgerPosting_Execute_Call) Run(run func(ctx context.Context, cmd port.PostPostingCommand)) *MockPostLedgerPosting_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.PostPostingCommand))
	})
	return _c
}

func (_c *MockPostLedgerPosting_Execute_Call) Return(_a0 port.PostingResult, _a1 error) *MockPostLedgerPosting_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostLedgerPosting_Execute_Call) RunAndReturn(run func(context.Context, port.PostPostingCommand) (port.PostingResult, error)) *MockPostLedgerPosting_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostLedgerPosting creates a new instance of MockPostLedgerPosting. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostLedgerPosting(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostLedgerPosting {
	mock := &MockPostLedgerPosting{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
