// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"

	valueobject "github.com/kadekutama/go-template/internal/domain/valueobject"
)

// MockSecretStore is an autogenerated mock type for the SecretStore type
type MockSecretStore struct {
	mock.Mock
}

type MockSecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretStore) EXPECT() *MockSecretStore_Expecter {
	return &MockSecretStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, tenant, name
func (_m *MockSecretStore) Get(ctx context.Context, tenant valueobject.TenantID, name string) (port.Secret, error) {
	ret := _m.Called(ctx, tenant, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 port.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) (port.Secret, error)); ok {
		return rf(ctx, tenant, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, valueobject.TenantID, string) port.Secret); ok {
		r0 = rf(ctx, tenant, name)
	} else {
		r0 = ret.Get(0).(port.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, valueobject.TenantID, string) error); ok {
		r1 = rf(ctx, tenant, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tenant valueobject.TenantID
//   - name string
func (_e *MockSecretStore_Expecter) Get(ctx interface{}, tenant interface{}, name interface{}) *MockSecretStore_Get_Call {
	return &MockSecretStore_Get_Call{Call: _e.mock.On("Get", ctx, tenant, name)}
}

func (_c *MockSecretStore_Get_Call) Run(run func(ctx context.Context, tenant valueobject.TenantID, name string)) *MockSecretStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(valueobject.TenantID), args[2].(string))
	})
	return _c
}

func (_c *MockSecretStore_Get_Call) Return(_a0 port.Secret, _a1 error) *MockSecretStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretStore_Get_Call) RunAndReturn(run func(context.Context, valueobject.TenantID, string) (port.Secret, error)) *MockSecretStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretStore creates a new instance of MockSecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretStore {
	mock := &MockSecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
