// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockStatementParser is an autogenerated mock type for the StatementParser type
type MockStatementParser struct {
	mock.Mock
}

type MockStatementParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatementParser) EXPECT() *MockStatementParser_Expecter {
	return &MockStatementParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: ctx, format, data
func (_m *MockStatementParser) Parse(ctx context.Context, format port.StatementFormat, data []byte) (port.BankStatement, error) {
	ret := _m.Called(ctx, format, data)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 port.BankStatement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.StatementFormat, []byte) (port.BankStatement, error)); ok {
		return rf(ctx, format, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.StatementFormat, []byte) port.BankStatement); ok {
		r0 = rf(ctx, format, data)
	} else {
		r0 = ret.Get(0).(port.BankStatement)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.StatementFormat, []byte) error); ok {
		r1 = rf(ctx, format, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatementParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockStatementParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - format port.StatementFormat
//   - data []byte
func (_e *MockStatementParser_Expecter) Parse(ctx interface{}, format interface{}, data interface{}) *MockStatementParser_Parse_Call {
	return &MockStatementParser_Parse_Call{Call: _e.mock.On("Parse", ctx, format, data)}
}

func (_c *MockStatementParser_Parse_Call) Run(run func(ctx context.Context, format port.StatementFormat, data []byte)) *MockStatementParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.StatementFormat), args[2].([]byte))
	})
	return _c
}

func (_c *MockStatementParser_Parse_Call) Return(_a0 port.BankStatement, _a1 error) *MockStatementParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatementParser_Parse_Call) RunAndReturn(run func(context.Context, port.StatementFormat, []byte) (port.BankStatement, error)) *MockStatementParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatementParser creates a new instance of MockStatementParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatementParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatementParser {
	mock := &MockStatementParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
