// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockTenantQueryUseCases is an autogenerated mock type for the TenantQueryUseCases type
type MockTenantQueryUseCases struct {
	mock.Mock
}

type MockTenantQueryUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantQueryUseCases) EXPECT() *MockTenantQueryUseCases_Expecter {
	return &MockTenantQueryUseCases_Expecter{mock: &_m.Mock}
}

// GetTenant provides a mock function with given fields: ctx, query
func (_m *MockTenantQueryUseCases) GetTenant(ctx context.Context, query port.TenantQuery) (port.TenantResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetTenant")
	}

	var r0 port.TenantResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TenantQuery) (port.TenantResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TenantQuery) port.TenantResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.TenantResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TenantQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantQueryUseCases_GetTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenant'
type MockTenantQueryUseCases_GetTenant_Call struct {
	*mock.Call
}

// GetTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.TenantQuery
func (_e *MockTenantQueryUseCases_Expecter) GetTenant(ctx interface{}, query interface{}) *MockTenantQueryUseCases_GetTenant_Call {
	return &MockTenantQueryUseCases_GetTenant_Call{Call: _e.mock.On("GetTenant", ctx, query)}
}

func (_c *MockTenantQueryUseCases_GetTenant_Call) Run(run func(ctx context.Context, query port.TenantQuery)) *MockTenantQueryUseCases_GetTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TenantQuery))
	})
	return _c
}

func (_c *MockTenantQueryUseCases_GetTenant_Call) Return(_a0 port.TenantResult, _a1 error) *MockTenantQueryUseCases_GetTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantQueryUseCases_GetTenant_Call) RunAndReturn(run func(context.Context, port.TenantQuery) (port.TenantResult, error)) *MockTenantQueryUseCases_GetTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenants provides a mock function with given fields: ctx
func (_m *MockTenantQueryUseCases) ListTenants(ctx context.Context) ([]entity.TenantData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTenants")
	}

	var r0 []entity.TenantData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.TenantData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.TenantData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TenantData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantQueryUseCases_ListTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenants'
type MockTenantQueryUseCases_ListTenants_Call struct {
	*mock.Call
}

// ListTenants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantQueryUseCases_Expecter) ListTenants(ctx interface{}) *MockTenantQueryUseCases_ListTenants_Call {
	return &MockTenantQueryUseCases_ListTenants_Call{Call: _e.mock.On("ListTenants", ctx)}
}

func (_c *MockTenantQueryUseCases_ListTenants_Call) Run(run func(ctx context.Context)) *MockTenantQueryUseCases_ListTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantQueryUseCases_ListTenants_Call) Return(_a0 []entity.TenantData, _a1 error) *MockTenantQueryUseCases_ListTenants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantQueryUseCases_ListTenants_Call) RunAndReturn(run func(context.Context) ([]entity.TenantData, error)) *MockTenantQueryUseCases_ListTenants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantQueryUseCases creates a new instance of MockTenantQueryUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantQueryUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantQueryUseCases {
	mock := &MockTenantQueryUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
