// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "github.com/kadekutama/go-template/internal/domain/entity"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockTenantUseCases is an autogenerated mock type for the TenantUseCases type
type MockTenantUseCases struct {
	mock.Mock
}

type MockTenantUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantUseCases) EXPECT() *MockTenantUseCases_Expecter {
	return &MockTenantUseCases_Expecter{mock: &_m.Mock}
}

// GetTenant provides a mock function with given fields: ctx, query
func (_m *MockTenantUseCases) GetTenant(ctx context.Context, query port.TenantQuery) (port.TenantResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetTenant")
	}

	var r0 port.TenantResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TenantQuery) (port.TenantResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TenantQuery) port.TenantResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.TenantResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TenantQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCases_GetTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenant'
type MockTenantUseCases_GetTenant_Call struct {
	*mock.Call
}

// GetTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.TenantQuery
func (_e *MockTenantUseCases_Expecter) GetTenant(ctx interface{}, query interface{}) *MockTenantUseCases_GetTenant_Call {
	return &MockTenantUseCases_GetTenant_Call{Call: _e.mock.On("GetTenant", ctx, query)}
}

func (_c *MockTenantUseCases_GetTenant_Call) Run(run func(ctx context.Context, query port.TenantQuery)) *MockTenantUseCases_GetTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TenantQuery))
	})
	return _c
}

func (_c *MockTenantUseCases_GetTenant_Call) Return(_a0 port.TenantResult, _a1 error) *MockTenantUseCases_GetTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCases_GetTenant_Call) RunAndReturn(run func(context.Context, port.TenantQuery) (port.TenantResult, error)) *MockTenantUseCases_GetTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenants provides a mock function with given fields: ctx
func (_m *MockTenantUseCases) ListTenants(ctx context.Context) ([]entity.TenantData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTenants")
	}

	var r0 []entity.TenantData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.TenantData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.TenantData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TenantData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCases_ListTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenants'
type MockTenantUseCases_ListTenants_Call struct {
	*mock.Call
}

// ListTenants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantUseCases_Expecter) ListTenants(ctx interface{}) *MockTenantUseCases_ListTenants_Call {
	return &MockTenantUseCases_ListTenants_Call{Call: _e.mock.On("ListTenants", ctx)}
}

func (_c *MockTenantUseCases_ListTenants_Call) Run(run func(ctx context.Context)) *MockTenantUseCases_ListTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantUseCases_ListTenants_Call) Return(_a0 []entity.TenantData, _a1 error) *MockTenantUseCases_ListTenants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCases_ListTenants_Call) RunAndReturn(run func(context.Context) ([]entity.TenantData, error)) *MockTenantUseCases_ListTenants_Call {
	_c.Call.Return(run)
	return _c
}

// ProvisionTenant provides a mock function with given fields: ctx, req
func (_m *MockTenantUseCases) ProvisionTenant(ctx context.Context, req port.ProvisionTenantRequest) (port.TenantResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionTenant")
	}

	var r0 port.TenantResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ProvisionTenantRequest) (port.TenantResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ProvisionTenantRequest) port.TenantResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TenantResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ProvisionTenantRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCases_ProvisionTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionTenant'
type MockTenantUseCases_ProvisionTenant_Call struct {
	*mock.Call
}

// ProvisionTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.ProvisionTenantRequest
func (_e *MockTenantUseCases_Expecter) ProvisionTenant(ctx interface{}, req interface{}) *MockTenantUseCases_ProvisionTenant_Call {
	return &MockTenantUseCases_ProvisionTenant_Call{Call: _e.mock.On("ProvisionTenant", ctx, req)}
}

func (_c *MockTenantUseCases_ProvisionTenant_Call) Run(run func(ctx context.Context, req port.ProvisionTenantRequest)) *MockTenantUseCases_ProvisionTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ProvisionTenantRequest))
	})
	return _c
}

func (_c *MockTenantUseCases_ProvisionTenant_Call) Return(_a0 port.TenantResult, _a1 error) *MockTenantUseCases_ProvisionTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCases_ProvisionTenant_Call) RunAndReturn(run func(context.Context, port.ProvisionTenantRequest) (port.TenantResult, error)) *MockTenantUseCases_ProvisionTenant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTenantSettings provides a mock function with given fields: ctx, req
func (_m *MockTenantUseCases) UpdateTenantSettings(ctx context.Context, req port.UpdateTenantSettingsRequest) (port.TenantResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTenantSettings")
	}

	var r0 port.TenantResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.UpdateTenantSettingsRequest) (port.TenantResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.UpdateTenantSettingsRequest) port.TenantResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TenantResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.UpdateTenantSettingsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantUseCases_UpdateTenantSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTenantSettings'
type MockTenantUseCases_UpdateTenantSettings_Call struct {
	*mock.Call
}

// UpdateTenantSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.UpdateTenantSettingsRequest
func (_e *MockTenantUseCases_Expecter) UpdateTenantSettings(ctx interface{}, req interface{}) *MockTenantUseCases_UpdateTenantSettings_Call {
	return &MockTenantUseCases_UpdateTenantSettings_Call{Call: _e.mock.On("UpdateTenantSettings", ctx, req)}
}

func (_c *MockTenantUseCases_UpdateTenantSettings_Call) Run(run func(ctx context.Context, req port.UpdateTenantSettingsRequest)) *MockTenantUseCases_UpdateTenantSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.UpdateTenantSettingsRequest))
	})
	return _c
}

func (_c *MockTenantUseCases_UpdateTenantSettings_Call) Return(_a0 port.TenantResult, _a1 error) *MockTenantUseCases_UpdateTenantSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantUseCases_UpdateTenantSettings_Call) RunAndReturn(run func(context.Context, port.UpdateTenantSettingsRequest) (port.TenantResult, error)) *MockTenantUseCases_UpdateTenantSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantUseCases creates a new instance of MockTenantUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantUseCases {
	mock := &MockTenantUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
