// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockTransferCommandUseCases is an autogenerated mock type for the TransferCommandUseCases type
type MockTransferCommandUseCases struct {
	mock.Mock
}

type MockTransferCommandUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferCommandUseCases) EXPECT() *MockTransferCommandUseCases_Expecter {
	return &MockTransferCommandUseCases_Expecter{mock: &_m.Mock}
}

// CancelTransfer provides a mock function with given fields: ctx, query
func (_m *MockTransferCommandUseCases) CancelTransfer(ctx context.Context, query port.TransferQuery) (port.TransferResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelTransfer")
	}

	var r0 port.TransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) (port.TransferResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) port.TransferResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.TransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferCommandUseCases_CancelTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTransfer'
type MockTransferCommandUseCases_CancelTransfer_Call struct {
	*mock.Call
}

// CancelTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.TransferQuery
func (_e *MockTransferCommandUseCases_Expecter) CancelTransfer(ctx interface{}, query interface{}) *MockTransferCommandUseCases_CancelTransfer_Call {
	return &MockTransferCommandUseCases_CancelTransfer_Call{Call: _e.mock.On("CancelTransfer", ctx, query)}
}

func (_c *MockTransferCommandUseCases_CancelTransfer_Call) Run(run func(ctx context.Context, query port.TransferQuery)) *MockTransferCommandUseCases_CancelTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferQuery))
	})
	return _c
}

func (_c *MockTransferCommandUseCases_CancelTransfer_Call) Return(_a0 port.TransferResult, _a1 error) *MockTransferCommandUseCases_CancelTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferCommandUseCases_CancelTransfer_Call) RunAndReturn(run func(context.Context, port.TransferQuery) (port.TransferResult, error)) *MockTransferCommandUseCases_CancelTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatchTransfer provides a mock function with given fields: ctx, req
func (_m *MockTransferCommandUseCases) CreateBatchTransfer(ctx context.Context, req port.BatchTransferRequest) (port.BatchTransferResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchTransfer")
	}

	var r0 port.BatchTransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchTransferRequest) (port.BatchTransferResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchTransferRequest) port.BatchTransferResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.BatchTransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.BatchTransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferCommandUseCases_CreateBatchTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatchTransfer'
type MockTransferCommandUseCases_CreateBatchTransfer_Call struct {
	*mock.Call
}

// CreateBatchTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.BatchTransferRequest
func (_e *MockTransferCommandUseCases_Expecter) CreateBatchTransfer(ctx interface{}, req interface{}) *MockTransferCommandUseCases_CreateBatchTransfer_Call {
	return &MockTransferCommandUseCases_CreateBatchTransfer_Call{Call: _e.mock.On("CreateBatchTransfer", ctx, req)}
}

func (_c *MockTransferCommandUseCases_CreateBatchTransfer_Call) Run(run func(ctx context.Context, req port.BatchTransferRequest)) *MockTransferCommandUseCases_CreateBatchTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BatchTransferRequest))
	})
	return _c
}

func (_c *MockTransferCommandUseCases_CreateBatchTransfer_Call) Return(_a0 port.BatchTransferResult, _a1 error) *MockTransferCommandUseCases_CreateBatchTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferCommandUseCases_CreateBatchTransfer_Call) RunAndReturn(run func(context.Context, port.BatchTransferRequest) (port.BatchTransferResult, error)) *MockTransferCommandUseCases_CreateBatchTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransfer provides a mock function with given fields: ctx, req
func (_m *MockTransferCommandUseCases) CreateTransfer(ctx context.Context, req port.TransferRequest) (port.TransferResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 port.TransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRequest) (port.TransferResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRequest) port.TransferResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferCommandUseCases_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type MockTransferCommandUseCases_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.TransferRequest
func (_e *MockTransferCommandUseCases_Expecter) CreateTransfer(ctx interface{}, req interface{}) *MockTransferCommandUseCases_CreateTransfer_Call {
	return &MockTransferCommandUseCases_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, req)}
}

func (_c *MockTransferCommandUseCases_CreateTransfer_Call) Run(run func(ctx context.Context, req port.TransferRequest)) *MockTransferCommandUseCases_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferRequest))
	})
	return _c
}

func (_c *MockTransferCommandUseCases_CreateTransfer_Call) Return(_a0 port.TransferResult, _a1 error) *MockTransferCommandUseCases_CreateTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferCommandUseCases_CreateTransfer_Call) RunAndReturn(run func(context.Context, port.TransferRequest) (port.TransferResult, error)) *MockTransferCommandUseCases_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferCommandUseCases creates a new instance of MockTransferCommandUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferCommandUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferCommandUseCases {
	mock := &MockTransferCommandUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
