// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockTransferUseCases is an autogenerated mock type for the TransferUseCases type
type MockTransferUseCases struct {
	mock.Mock
}

type MockTransferUseCases_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferUseCases) EXPECT() *MockTransferUseCases_Expecter {
	return &MockTransferUseCases_Expecter{mock: &_m.Mock}
}

// CancelTransfer provides a mock function with given fields: ctx, query
func (_m *MockTransferUseCases) CancelTransfer(ctx context.Context, query port.TransferQuery) (port.TransferResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CancelTransfer")
	}

	var r0 port.TransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) (port.TransferResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) port.TransferResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.TransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_CancelTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTransfer'
type MockTransferUseCases_CancelTransfer_Call struct {
	*mock.Call
}

// CancelTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.TransferQuery
func (_e *MockTransferUseCases_Expecter) CancelTransfer(ctx interface{}, query interface{}) *MockTransferUseCases_CancelTransfer_Call {
	return &MockTransferUseCases_CancelTransfer_Call{Call: _e.mock.On("CancelTransfer", ctx, query)}
}

func (_c *MockTransferUseCases_CancelTransfer_Call) Run(run func(ctx context.Context, query port.TransferQuery)) *MockTransferUseCases_CancelTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferQuery))
	})
	return _c
}

func (_c *MockTransferUseCases_CancelTransfer_Call) Return(_a0 port.TransferResult, _a1 error) *MockTransferUseCases_CancelTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_CancelTransfer_Call) RunAndReturn(run func(context.Context, port.TransferQuery) (port.TransferResult, error)) *MockTransferUseCases_CancelTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatchTransfer provides a mock function with given fields: ctx, req
func (_m *MockTransferUseCases) CreateBatchTransfer(ctx context.Context, req port.BatchTransferRequest) (port.BatchTransferResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchTransfer")
	}

	var r0 port.BatchTransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchTransferRequest) (port.BatchTransferResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchTransferRequest) port.BatchTransferResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.BatchTransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.BatchTransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_CreateBatchTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatchTransfer'
type MockTransferUseCases_CreateBatchTransfer_Call struct {
	*mock.Call
}

// CreateBatchTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.BatchTransferRequest
func (_e *MockTransferUseCases_Expecter) CreateBatchTransfer(ctx interface{}, req interface{}) *MockTransferUseCases_CreateBatchTransfer_Call {
	return &MockTransferUseCases_CreateBatchTransfer_Call{Call: _e.mock.On("CreateBatchTransfer", ctx, req)}
}

func (_c *MockTransferUseCases_CreateBatchTransfer_Call) Run(run func(ctx context.Context, req port.BatchTransferRequest)) *MockTransferUseCases_CreateBatchTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BatchTransferRequest))
	})
	return _c
}

func (_c *MockTransferUseCases_CreateBatchTransfer_Call) Return(_a0 port.BatchTransferResult, _a1 error) *MockTransferUseCases_CreateBatchTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_CreateBatchTransfer_Call) RunAndReturn(run func(context.Context, port.BatchTransferRequest) (port.BatchTransferResult, error)) *MockTransferUseCases_CreateBatchTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransfer provides a mock function with given fields: ctx, req
func (_m *MockTransferUseCases) CreateTransfer(ctx context.Context, req port.TransferRequest) (port.TransferResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 port.TransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRequest) (port.TransferResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferRequest) port.TransferResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(port.TransferResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type MockTransferUseCases_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.TransferRequest
func (_e *MockTransferUseCases_Expecter) CreateTransfer(ctx interface{}, req interface{}) *MockTransferUseCases_CreateTransfer_Call {
	return &MockTransferUseCases_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, req)}
}

func (_c *MockTransferUseCases_CreateTransfer_Call) Run(run func(ctx context.Context, req port.TransferRequest)) *MockTransferUseCases_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferRequest))
	})
	return _c
}

func (_c *MockTransferUseCases_CreateTransfer_Call) Return(_a0 port.TransferResult, _a1 error) *MockTransferUseCases_CreateTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_CreateTransfer_Call) RunAndReturn(run func(context.Context, port.TransferRequest) (port.TransferResult, error)) *MockTransferUseCases_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchStatus provides a mock function with given fields: ctx, query
func (_m *MockTransferUseCases) GetBatchStatus(ctx context.Context, query port.BatchStatusQuery) (port.BatchStatusResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchStatus")
	}

	var r0 port.BatchStatusResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchStatusQuery) (port.BatchStatusResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.BatchStatusQuery) port.BatchStatusResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.BatchStatusResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.BatchStatusQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_GetBatchStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchStatus'
type MockTransferUseCases_GetBatchStatus_Call struct {
	*mock.Call
}

// GetBatchStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.BatchStatusQuery
func (_e *MockTransferUseCases_Expecter) GetBatchStatus(ctx interface{}, query interface{}) *MockTransferUseCases_GetBatchStatus_Call {
	return &MockTransferUseCases_GetBatchStatus_Call{Call: _e.mock.On("GetBatchStatus", ctx, query)}
}

func (_c *MockTransferUseCases_GetBatchStatus_Call) Run(run func(ctx context.Context, query port.BatchStatusQuery)) *MockTransferUseCases_GetBatchStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.BatchStatusQuery))
	})
	return _c
}

func (_c *MockTransferUseCases_GetBatchStatus_Call) Return(_a0 port.BatchStatusResult, _a1 error) *MockTransferUseCases_GetBatchStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_GetBatchStatus_Call) RunAndReturn(run func(context.Context, port.BatchStatusQuery) (port.BatchStatusResult, error)) *MockTransferUseCases_GetBatchStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransfer provides a mock function with given fields: ctx, query
func (_m *MockTransferUseCases) GetTransfer(ctx context.Context, query port.TransferQuery) (port.TransferView, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetTransfer")
	}

	var r0 port.TransferView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) (port.TransferView, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferQuery) port.TransferView); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.TransferView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_GetTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfer'
type MockTransferUseCases_GetTransfer_Call struct {
	*mock.Call
}

// GetTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.TransferQuery
func (_e *MockTransferUseCases_Expecter) GetTransfer(ctx interface{}, query interface{}) *MockTransferUseCases_GetTransfer_Call {
	return &MockTransferUseCases_GetTransfer_Call{Call: _e.mock.On("GetTransfer", ctx, query)}
}

func (_c *MockTransferUseCases_GetTransfer_Call) Run(run func(ctx context.Context, query port.TransferQuery)) *MockTransferUseCases_GetTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferQuery))
	})
	return _c
}

func (_c *MockTransferUseCases_GetTransfer_Call) Return(_a0 port.TransferView, _a1 error) *MockTransferUseCases_GetTransfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_GetTransfer_Call) RunAndReturn(run func(context.Context, port.TransferQuery) (port.TransferView, error)) *MockTransferUseCases_GetTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransfers provides a mock function with given fields: ctx, filter
func (_m *MockTransferUseCases) ListTransfers(ctx context.Context, filter port.TransferFilter) (port.TransferPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTransfers")
	}

	var r0 port.TransferPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferFilter) (port.TransferPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.TransferFilter) port.TransferPage); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(port.TransferPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.TransferFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransferUseCases_ListTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransfers'
type MockTransferUseCases_ListTransfers_Call struct {
	*mock.Call
}

// ListTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter port.TransferFilter
func (_e *MockTransferUseCases_Expecter) ListTransfers(ctx interface{}, filter interface{}) *MockTransferUseCases_ListTransfers_Call {
	return &MockTransferUseCases_ListTransfers_Call{Call: _e.mock.On("ListTransfers", ctx, filter)}
}

func (_c *MockTransferUseCases_ListTransfers_Call) Run(run func(ctx context.Context, filter port.TransferFilter)) *MockTransferUseCases_ListTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.TransferFilter))
	})
	return _c
}

func (_c *MockTransferUseCases_ListTransfers_Call) Return(_a0 port.TransferPage, _a1 error) *MockTransferUseCases_ListTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransferUseCases_ListTransfers_Call) RunAndReturn(run func(context.Context, port.TransferFilter) (port.TransferPage, error)) *MockTransferUseCases_ListTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferUseCases creates a new instance of MockTransferUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferUseCases {
	mock := &MockTransferUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
