// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
	repository "github.com/kadekutama/go-template/internal/domain/repository"
)

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

type MockTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTx) EXPECT() *MockTx_Expecter {
	return &MockTx_Expecter{mock: &_m.Mock}
}

// Cursor provides a mock function with no fields
func (_m *MockTx) Cursor() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cursor")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTx_Cursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cursor'
type MockTx_Cursor_Call struct {
	*mock.Call
}

// Cursor is a helper method to define mock.On call
func (_e *MockTx_Expecter) Cursor() *MockTx_Cursor_Call {
	return &MockTx_Cursor_Call{Call: _e.mock.On("Cursor")}
}

func (_c *MockTx_Cursor_Call) Run(run func()) *MockTx_Cursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Cursor_Call) Return(_a0 string) *MockTx_Cursor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Cursor_Call) RunAndReturn(run func() string) *MockTx_Cursor_Call {
	_c.Call.Return(run)
	return _c
}

// Holds provides a mock function with no fields
func (_m *MockTx) Holds() repository.HoldRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Holds")
	}

	var r0 repository.HoldRepository
	if rf, ok := ret.Get(0).(func() repository.HoldRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.HoldRepository)
		}
	}

	return r0
}

// MockTx_Holds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Holds'
type MockTx_Holds_Call struct {
	*mock.Call
}

// Holds is a helper method to define mock.On call
func (_e *MockTx_Expecter) Holds() *MockTx_Holds_Call {
	return &MockTx_Holds_Call{Call: _e.mock.On("Holds")}
}

func (_c *MockTx_Holds_Call) Run(run func()) *MockTx_Holds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Holds_Call) Return(_a0 repository.HoldRepository) *MockTx_Holds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Holds_Call) RunAndReturn(run func() repository.HoldRepository) *MockTx_Holds_Call {
	_c.Call.Return(run)
	return _c
}

// Idempotency provides a mock function with no fields
func (_m *MockTx) Idempotency() port.IdempotencyStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Idempotency")
	}

	var r0 port.IdempotencyStore
	if rf, ok := ret.Get(0).(func() port.IdempotencyStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.IdempotencyStore)
		}
	}

	return r0
}

// MockTx_Idempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Idempotency'
type MockTx_Idempotency_Call struct {
	*mock.Call
}

// Idempotency is a helper method to define mock.On call
func (_e *MockTx_Expecter) Idempotency() *MockTx_Idempotency_Call {
	return &MockTx_Idempotency_Call{Call: _e.mock.On("Idempotency")}
}

func (_c *MockTx_Idempotency_Call) Run(run func()) *MockTx_Idempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Idempotency_Call) Return(_a0 port.IdempotencyStore) *MockTx_Idempotency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Idempotency_Call) RunAndReturn(run func() port.IdempotencyStore) *MockTx_Idempotency_Call {
	_c.Call.Return(run)
	return _c
}

// Outbox provides a mock function with no fields
func (_m *MockTx) Outbox() port.EventOutbox {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outbox")
	}

	var r0 port.EventOutbox
	if rf, ok := ret.Get(0).(func() port.EventOutbox); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(port.EventOutbox)
		}
	}

	return r0
}

// MockTx_Outbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outbox'
type MockTx_Outbox_Call struct {
	*mock.Call
}

// Outbox is a helper method to define mock.On call
func (_e *MockTx_Expecter) Outbox() *MockTx_Outbox_Call {
	return &MockTx_Outbox_Call{Call: _e.mock.On("Outbox")}
}

func (_c *MockTx_Outbox_Call) Run(run func()) *MockTx_Outbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Outbox_Call) Return(_a0 port.EventOutbox) *MockTx_Outbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Outbox_Call) RunAndReturn(run func() port.EventOutbox) *MockTx_Outbox_Call {
	_c.Call.Return(run)
	return _c
}

// Postings provides a mock function with no fields
func (_m *MockTx) Postings() repository.PostingRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Postings")
	}

	var r0 repository.PostingRepository
	if rf, ok := ret.Get(0).(func() repository.PostingRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PostingRepository)
		}
	}

	return r0
}

// MockTx_Postings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Postings'
type MockTx_Postings_Call struct {
	*mock.Call
}

// Postings is a helper method to define mock.On call
func (_e *MockTx_Expecter) Postings() *MockTx_Postings_Call {
	return &MockTx_Postings_Call{Call: _e.mock.On("Postings")}
}

func (_c *MockTx_Postings_Call) Run(run func()) *MockTx_Postings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTx_Postings_Call) Return(_a0 repository.PostingRepository) *MockTx_Postings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTx_Postings_Call) RunAndReturn(run func() repository.PostingRepository) *MockTx_Postings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTx creates a new instance of MockTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTx {
	mock := &MockTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
