// Code generated by mockery v2.53.7. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "github.com/kadekutama/go-template/internal/application/port"
)

// MockWebhookDispatcher is an autogenerated mock type for the WebhookDispatcher type
type MockWebhookDispatcher struct {
	mock.Mock
}

type MockWebhookDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookDispatcher) EXPECT() *MockWebhookDispatcher_Expecter {
	return &MockWebhookDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, message
func (_m *MockWebhookDispatcher) Dispatch(ctx context.Context, message port.WebhookMessage) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.WebhookMessage) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockWebhookDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - message port.WebhookMessage
func (_e *MockWebhookDispatcher_Expecter) Dispatch(ctx interface{}, message interface{}) *MockWebhookDispatcher_Dispatch_Call {
	return &MockWebhookDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, message)}
}

func (_c *MockWebhookDispatcher_Dispatch_Call) Run(run func(ctx context.Context, message port.WebhookMessage)) *MockWebhookDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.WebhookMessage))
	})
	return _c
}

func (_c *MockWebhookDispatcher_Dispatch_Call) Return(_a0 error) *MockWebhookDispatcher_Dispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookDispatcher_Dispatch_Call) RunAndReturn(run func(context.Context, port.WebhookMessage) error) *MockWebhookDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookDispatcher creates a new instance of MockWebhookDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookDispatcher {
	mock := &MockWebhookDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
